### ISSUE TITLE
Error while initiating a sst-app

### ISSUE THREAD

**Issue by devfromfinland** [serverless-stack/serverless-stack#10]
Hi
I'm following the instruction on this page to initiate sst-app https://serverless-stack.com/chapters/building-a-cdk-app-with-sst.html

However, I keep encountering this error npm ERR! Unexpected end of JSON input while parsing near '...kedSize":449192,"npm-'

How could I fix this?

![image](https://user-images.githubusercontent.com/62564734/95780613-e33da480-0cd4-11eb-8ebf-6480f339967c.png)

**Comment by jayair** [comment]
Can you also post your npm version? And maybe upload the debug log that was generated?

**Comment by devfromfinland** [comment]
Hi, my npm version is 6.14.5 and here is the generated log file
[2020-10-12T18_45_15_312Z-debug.log](https://github.com/serverless-stack/serverless-stack/files/5370205/2020-10-12T18_45_15_312Z-debug.log)

**Comment by jayair** [comment]
Thanks. I couldn't find anything specific about this issue in the logs. But a quick Google search turned this up:

https://stackoverflow.com/a/47896884/3369702

Can you give that a try?

**Comment by thdxr** [comment]
Hey @devfromfinland is this still an issue? I'm going to close the issue for now - let us know if you'd like to reopen it
