### ISSUE TITLE
TypeGraphQL example

### ISSUE THREAD

**Issue by giacomorebonato** [serverless-stack/serverless-stack#1006]
## Question

Hi, I am trying to use TypeGraphQL with serverless-stack.
My understanding is that esbuild doesn't support `emitDecoratorMetadata` hence [esbuild-plugin-tsc](https://github.com/thomaschaaf/esbuild-plugin-tsc) should be use to address this need.

This is how my API is declared:

```ts
    const graphqlApi = new sst.ApolloApi(this, 'graphql-api', {
      server: {
        handler: 'src/graphql.handler',
        environment: {
          NODE_ENV,
          MONGODB_URL,
          ADMIN_EMAIL
        },
        bundle: {
          esbuildConfig: {
            plugins: 'config/esbuild.js'
          }
        }
      }
    })
```

And this my `esbuild.js`:

```js
const esbuildPluginTsc = require('esbuild-plugin-tsc')

module.exports = {
  plugins: [esbuildPluginTsc()]
}
```

After this setup I would have expected TypeGraphQL to be able to infer field types without declaring them again explicitly again in the `@Field` decorator.

```
Uncaught Exception 	{"errorType":"Error","errorMessage":"Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for 'userId' of 'UserProfile2' class.","stack":["Error: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for 'userId' of 'UserProfile2' class.","
```

May I ask if this is the current state of things or a better configuration can be achieved?
I'd like to contribute with an example once I understand :)

Thanks.

### Relevant discussions

[Add support for bundlers other than esbuild #219](https://github.com/serverless-stack/serverless-stack/discussions/219)

**Comment by giacomorebonato** [comment]
OK, I think that I solved it... I was using the wrong esbuild plugin.
This is the correct one:

```js
const { esbuildDecorators } = require('@anatine/esbuild-decorators')

module.exports = {
  plugins: [esbuildDecorators()]
}
```

Taken [straight from the documentation](https://docs.serverless-stack.com/constructs/Function#plugins) :)

Thanks!

**Comment by fwang** [comment]
Oh nice! Glad it's working.
