### ISSUE TITLE
Strange "ignoring extra certs" warning message when in `sst start` mode, upon 1st function invocation

### ISSUE THREAD

**Issue by ffxsam** [serverless-stack/serverless-stack#1008]
When running `sst start`, the first time a function is invoked, this warning message is displayed:

`Warning: Ignoring extra certs from /etc/pki/tls/certs/ca-bundle.crt, load failed: error:02001002:system library:fopen:No such file or directory`

This appears to have cropped up without any updates to the `@serverless-stack/*` packages.

https://serverless-stack.slack.com/archives/C01JG3B20RY/p1636072195234900

**Comment by fwang** [comment]
Yeah I can confirm that I ran into this as well.
