### ISSUE TITLE
Identity is null when trying Authorization with Cognito

### ISSUE THREAD

**Issue by giacomorebonato** [serverless-stack/serverless-stack#1011]
I am struggling to make an authenticated http request (curl or Postman) authenticating with a Cognito token to a Lambda exposed through an API Gateway.
This is how my API is declared in the stack:

```ts
    const graphqlApi = new sst.ApolloApi(this, 'graphql-api', {
      defaultAuthorizationType: sst.ApiAuthorizationType.NONE,
      server: {
        handler: 'src/graphql.handler',
      }
    })

    auth.attachPermissionsForAuthUsers([graphqlApi])
    auth.attachPermissionsForUnauthUsers([graphqlApi])
    graphqlApi.attachPermissions(PermissionType.ALL)
```

While on frontend I am going to use Amplify libraries, I'd like for testing purposes to understand how I can build an authenticated request.
Hence I created (only for testing purposes) a login end point that returns JWT token for a given user:

```ts
const accessToken = result.getAccessToken().getJwtToken()

return { accessToken }
```

Now I don't understand how I can use this token to make an authenticated http request.
I have tried putting this token into the Authorization header (also with Bearer upfront), but context identity is always null.

Could you help me out understanding what I am doing wrong even though this is not an issue with this framework?
I'll be happy to contribute with an example once I understand.

Many thanks.

**Comment by giacomorebonato** [comment]
I see that making an IAM authorized request to an API Gateway is doable, but more tough that I imagined.

* https://serverless-stack.com/examples/how-to-add-cognito-authentication-to-a-serverless-api.html
* https://www.npmjs.com/package/@cm-madlabs/aws-apigateway-sigv4

I am probably going to look for alternatives.
Cognito has a lot of things ready to use (2fa, forgotten password, React UI, etc...), but a pity that it's tricky to integrate with API Gateway.

**Comment by fwang** [comment]
Hey @giacomorebonato, sorry to hear you are running into issues with API auth. Cognito can be very confusing to configure sometimes.

In the Serverless Stack guide, we have a step by step example of setting up IAM auth for the API (both backend and frontend) - https://serverless-stack.com/chapters/configure-aws-amplify.html

We are also in the process of adding an example for setting up JWT auth for the API. I will keep you posted when that example is published.

**Comment by giacomorebonato** [comment]
Thanks for feedback!
Cognito is very confusing indeed!
