### ISSUE TITLE
Errors when deploying to AWS GovCloud 

### ISSUE THREAD

**Issue by mlerner-ml** [serverless-stack/serverless-stack#1048]
**What I'm trying to do?**
Deploy base SST app to AWS GovCloud

**What Happens?**
Error at `Template format error: Unrecognized resource types: [AWS::CDK::Metadata]`.
This is the first few lines of the Cloudformation file generated with `sst build`

**Comment by fwang** [comment]
Hey @mlerner-ml, thanks for bringing this up.

I submitted a request to AWS for GovCloud access. I will give this and #1049 once I get my hands to the GovCloud region.

I will follow up!

**Comment by mlerner-ml** [comment]
Wonderful. Thanks!
