### ISSUE TITLE
AppSyncApi: support custom domain

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#1071]
References:
- https://aws.amazon.com/blogs/mobile/use-a-custom-domain-with-aws-appsync-amazon-cloudfront-and-amazon-route-53/
- https://theburningmonk.com/2020/09/how-to-set-up-custom-domain-names-for-appsync/

---
Requests:
- Gerald https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1637296836207300?thread_ts=1637284298.206900&cid=C01HQQVC8TH
- Mischa https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1648541259207479

**Comment by sionelt** [comment]
Custom domain for AppSync was recently released. How to setup on the console: https://aws.amazon.com/blogs/mobile/introducing-custom-domain-names-for-aws-appsync-apis/. Hopefully cloudformation/AWS CDK support soon.

**Comment by fwang** [comment]
Thanks @sionelt! Yup, we have our eyes on CDK support for it :)
https://github.com/aws/aws-cdk/issues/18040

**Comment by joekendal** [comment]
+1

**Comment by tomaszdudek7** [comment]
Not sure if it proves any useful but there's also a similar feature request for Serverless Framework (and its AppSync plugin) here: https://github.com/sid88in/serverless-appsync-plugin/issues/454

**Comment by davideicardi** [comment]
Now that https://github.com/aws/aws-cdk/issues/18040 is available do you think it will be possible to use custom domain inside serverless stack? How?

**Comment by revmischa** [comment]
Custom domain support in CDK is released now - would love this feature in SST!
