### ISSUE TITLE
Testing Stacks with routes using Jest

### ISSUE THREAD

**Issue by EliasLeguizamon123** [serverless-stack/serverless-stack#1075]
Hi everyone, I am quite new using serverless stack and I have read the sst documentation in the section to test Stack's but the example you have does not help me to test stacks that have routes with requests to a DB.

i have a stack file called CommonStack: 

```
export default class commonStack extends Stack {
  constructor(scope, id, props,layers) {
    super(scope, id, props);
    this.addDefaultFunctionLayers(layers);
    this.addDefaultFunctionEnv(createStackEnv(process.env));
    props.api.addRoutes(this, {
        "GET    /countries/{id}": "common/service/country/get.main",
        "POST   /countries/": "common/service/country/post.main"
      });
    }
  }
```
also, inside get.js i have my petition to prisma BD
```
export async function main(event) {
    const prisma = new PrismaClient()
    const idCountry = Number(event.pathParameters.id)
    if (!idCountry) {
        return response(400, { message: 'Bad Request' })
    }

    const country = await prisma.country.findFirst({ where: { id: idCountry } })

    return response(200, country);
}
```
my problem is that within the sst documentation there is no example to test this type of stack, can someone help me understand how to run tests correctly?

**Comment by thdxr** [comment]
This falls under the integration test category.  Typically you'd run `sst start` to bring up everything locally. Then you can write tests that hit the endpoints and check whatever needs to be checked.

I personally use cypress for this and test through my frontend

**Comment by EliasLeguizamon123** [comment]
Ok, thank you @thdxr ! i will read about it!
