### ISSUE TITLE
Update CDK to v2

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#1076]
Requests:
- George Evans https://serverless-stack.slack.com/archives/C01JG3B20RY/p1637667182209400
- Adam Fanello https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1641312840248600

**Comment by paambaati** [comment]
Just FYI, CDK v2 is now out!

**Comment by fwang** [comment]
Thanks for the heads up @paambaati! We are planning to update to v2 this month.

**Comment by RichiCoder1** [comment]
Excited for this, expecting this to greatly alleviate a lot of update-and-sync related package churn.

**Comment by mwawrusch** [comment]
I am waiting for this as well. We have been burned hard by the serverless folks when it comes to fixing mission critical bugs (we use a multi account setup with serverless components which sometimes deploys to the wrong AWS account) and need to migrate to a working solution. Would love to use yours but need V2 support.

Thanks.

**Comment by fwang** [comment]
Got it! Will get started on this next week.

**Comment by RichiCoder1** [comment]
Not to be that developer, but is there any update on this? Any way I/we can provide assistance?

**Comment by fwang** [comment]
Hey @RichiCoder1, I'm working on it as we speak 😎

**Comment by fwang** [comment]
Hey everyone, we just released v0.57.0 with CDK v1.138.0, the latest version for CDK v1. We will cut another release soon with CDK v2.4.0 in the coming days.

If you have an existing SST project, it is recommenced that you update to v0.57.0 first. CDK v1.138.0 and CDK v2.4.0 are feature parity, so it will be a smoother transition when updating to the upcoming release.

**Comment by fwang** [comment]
Updated to CDK v2 in [v0.59.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.59.0). See release notes for steps to update.
