### ISSUE TITLE
Disabling linting

### ISSUE THREAD

**Issue by drieshooghe** [serverless-stack/serverless-stack#108]
I'm working on a Typescript monorepo project where we use SST from an `/infrastructure` directory.
In our eslint configuration on root level we specify where our tsconfig lives, but the linting step resolves this path from the `node_modules/@serverless-stack/cli` directory instead of the project root.

```bash
  0:0  error  Parsing error: Cannot read file 'projectroot/node_modules/@serverless-stack/cli/tsconfig.json'
```

On top of that, we already do our linting before we pass the app to the Seed pipeline. It would be nice to disable linting altogether.

**Comment by fwang** [comment]
@ drieshooghe You can now disable lint in [v0.9.4](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.9.4) by adding `"lint": false` to your `sst.json`.
