### ISSUE TITLE
Linting fails due to upstream configuration difference

### ISSUE THREAD

**Issue by lookitsatravis** [serverless-stack/serverless-stack#11]
Hello! I'm getting the following error after a basic `yarn create serverless-stack resources`. I installed the stack into a subdirectory of a project which has it's own ESLint configuration. I get the following error during `yarn build`:

```
❯ yarn build                                                                                                                                               took   4s   12.18.3   2.4.0
yarn run v1.22.10
$ sst build
Preparing @serverless-stack/resources
Linting source

Oops! Something went wrong! :(

ESLint: 7.11.0

ESLint couldn't determine the plugin "@typescript-eslint" uniquely.

- /Users/me/some-app/infrastructure/node_modules/@serverless-stack/cli/node_modules/@typescript-eslint/eslint-plugin/dist/index.js (loaded in "--config")
- /Users/me/some-app/node_modules/@typescript-eslint/eslint-plugin/dist/index.js (loaded in "../.eslintrc.js » plugin:@typescript-eslint/recommended » ./configs/base")

Please remove the "plugins" setting from either config or remove either plugin installation.

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Seems this can be resolved by making sure the CLI's ESLint process [treats itself as the root](https://github.com/eslint/eslint/issues/13385#issuecomment-640852278) via `--resolve-plugins-relative-to .` This could also be solved by allowing me to specify my own ESLint config to `sst`, or by letting end users skip linting altogether.

**Comment by jayair** [comment]
Ah let me have a look at this. Is your SST app installed one directory inside your project root?

**Comment by lookitsatravis** [comment]
Yes, so my project looks a bit like this:

```
my-app/
├─ infrastructure/
│  ├─ sst.json
│  ├─ package.json
├─ .eslintrc.js
├─ node_modules/
├─ package.json
```

I'm using that ESLint config for other files in the same repo. I suppose it's worth it to mention that I'm using Yarn workspaces and the `infrastructure` directory is included in that configuration. I patched it locally via [patch-package](https://github.com/ds300/patch-package) with the following patch:

```diff
# patch file named @serverless-stack+cli+0.4.2.patch

diff --git a/node_modules/@serverless-stack/cli/scripts/config/cdkHelpers.js b/node_modules/@serverless-stack/cli/scripts/config/cdkHelpers.js
index f473dba..ddc8b4a 100644
--- a/node_modules/@serverless-stack/cli/scripts/config/cdkHelpers.js
+++ b/node_modules/@serverless-stack/cli/scripts/config/cdkHelpers.js
@@ -128,6 +128,8 @@ function lint() {
       ".js,.ts",
       "--fix",
       "lib/**",
+      "--resolve-plugins-relative-to",
+      ".",
     ],
     { stdio: "inherit", cwd: paths.appPath }
   );

```

**Comment by jayair** [comment]
Yup makes sense. Thanks for sharing the patch.

Just pushed out a new release with it:

https://github.com/serverless-stack/serverless-stack/releases/tag/v0.4.3
