### ISSUE TITLE
Deploying multiple Next.js apps deletes Cloudformation resources needed for other apps

### ISSUE THREAD

**Issue by 3stacks** [serverless-stack/serverless-stack#1101]
Hi all, I've been having a really hard time getting my set-up deploying. It may be that it is too complicated for SST, or that I'm missing some obvious configurations.

I've made a gist here outlining the general structure of my stacks: https://gist.github.com/3stacks/87d0be7fe7939d3e23bde06b6a4ecf20

I have a large monorepo with 3 aspects:
- a static marketing site
- HTTP api deploying on lambda
- many Next.js projects

The nature of the project is that I need to spin up and sunset new Nextjs projects fairly frequently. I'm currently maintaining 10 Next.js projects.

I would like to be able to deploy all of the Next projects independently in staging and production environments, so I added a switch to try to build and deploy the respective project in isolation. The main reason for the strange structure is that I needed to have the Cloudfront Cache Policies shared between all of the Next projects. By instantiating the cache policies at the root in the `index.ts` I would get errors about having to instantiate the cache policies in a stack context.

I originally had a different Next stack for each Next app but I ran into the 20 cache policy limit instantly.

Am I barking up the wrong tree here? Is this too complicated of a use case for SST? (I'll concede the point that it's probably unnecessarily complicated ;) )

I appreciate any help. If I do end up getting this working I would be happy to create an example for the repo if it might be helpful.

**Comment by fwang** [comment]
Hey @3stacks

> By instantiating the cache policies at the root in the `index.ts` I would get errors about having to instantiate the cache policies in a stack context
All resources/constructs need to be instantiated inside a stack, so SST knows which CloudFormation stack a resource belongs to.

What you can do is to create the `cachePolicies` for one project, and re-use them in other projects. It'd look something like this:
```js
let cachePolicies;
if (projectName === "project-1") {
  cachePolicies = {
    staticCachePolicy: new cloudfront.CachePolicy(this, "StaticCache", NextjsSite.staticCachePolicyProps),
    imageCachePolicy: new cloudfront.CachePolicy(this, "ImageCache", NextjsSite.imageCachePolicyProps),
    lambdaCachePolicy: new cloudfront.CachePolicy(this, "LambdaCache", NextjsSite.lambdaCachePolicyProps),
  };
}
else {
  cachePolicies = {
    staticCachePolicy: new cloudfront.CachePolicy.fromCachePolicyId(this, "StaticCache", "xxxxxxx"),
    imageCachePolicy: new cloudfront.CachePolicy.fromCachePolicyId(this, "ImageCache", "xxxxxxx"),
    lambdaCachePolicy: new cloudfront.CachePolicy.fromCachePolicyId(this, "LambdaCache", "xxxxxxx"),
  };
}
```

Let me know if that makes sense.

**Comment by 3stacks** [comment]
Hey @fwang , thanks for the reply. 

Yep that seems to make sense. I did try to do something similar by instantiating the one set of cache policies at the top of the file and passing it to all of the stacks, but kept running into problems. So it sounds like it would make sense to have a sort of "bootstrapping" project you deploy first and then use those resources.

Thanks again!

**Comment by 3stacks** [comment]
I'm having further issues related to this. I managed to get several apps deployed sharing the same cache policies, but on subsequent deployments it seems to be attempting to create a new Cloudfront distribution, but because there's already an existing cloudfront distribution with the custom domain the deployment fails. 

am I supposed to be caching some build context so it will stop creating new resources?

**Comment by 3stacks** [comment]
Seems to have been a transient issue. Working like a treat now
