### ISSUE TITLE
(CLI) sst update updates SST packages correctly, but seems stuck on 1.126.0 for CDK packages

### ISSUE THREAD

**Issue by dkershner6** [serverless-stack/serverless-stack#1108]
It should (at time of writing) update the CDK packages to `1.132.0` as opposed to `1.126.0`.  SST packages correctly update to `0.53.3`.

**Comment by dkershner6** [comment]
> Hey @dkershner6, just to clarify, were the @serverless-stack packages updated to 0.53.3 but the CDK packages updated to 1.126.0?

This exactly.

Apologies, I am as bad at writing bug tickets as an end user!

**Comment by fwang** [comment]
Haha, got it! Let me loop in @thdxr, he's more familiar with the update command.

**Comment by dkershner6** [comment]
I think it might just be something about versioning of the CLI itself not being able to go past, itself.  It DOES do it for the sst packages, but it DOES NOT do it for the CDK packages, and it DOES NOT report that it did it for either.

As in, the report says:
```
 % sst update
Updating @serverless-stack/cli to latest
Updating @serverless-stack/resources to latest
Updating @aws-cdk/assert@1.126.0
Updating @aws-cdk/aws-dynamodb@1.126.0
Updating @aws-cdk/aws-lambda@1.126.0
Updating @aws-cdk/aws-logs@1.126.0
Updating @aws-cdk/aws-sns@1.126.0
Updating @aws-cdk/aws-sns-subscriptions@1.126.0
Updating @aws-cdk/aws-sqs@1.126.0
Updating @aws-cdk/aws-ssm@1.126.0
Updating @aws-cdk/core@1.126.0
Updating @aws-cdk/custom-resources@1.126.0
Updating aws-cdk@1.126.0
SST: 0.46.1
CDK: 1.126.0
```

But in actuality, SST was updated to `0.53.4`

**Comment by thdxr** [comment]
This was a bug in older versions of SST which I believe has been fixed

**Comment by dkershner6** [comment]
> This was a bug in older versions of SST which I believe has been fixed

Works for me, I haven't experienced it in the newer versions (although...you wouldnt, for obvious reasons).  Closing nonetheless.
