### ISSUE TITLE
Error message isn't visible when the theme is solarized dark

### ISSUE THREAD

**Issue by Manitej66** [serverless-stack/serverless-stack#1135]
When the terminal theme is set to `solarized dark` in iTerm2, the error messages aren't visible.

![image](https://user-images.githubusercontent.com/61357713/145340511-e8998545-ce79-4724-ba98-e8f2d423f961.png)

Expected:

![image](https://user-images.githubusercontent.com/61357713/145340549-da5ef90d-0512-457f-b5cc-75a0d36aa8a9.png)

**Comment by fwang** [comment]
It was due to font color
