### ISSUE TITLE
ApolloApi with lambda layer took 1h 34m to deploy

### ISSUE THREAD

**Issue by iquabius** [serverless-stack/serverless-stack#1153]
I just finished deploying an `ApolloApi` which uses Prisma.

**It took 1h 34m** even though the change was simply adding a custom domain.

![image](https://user-images.githubusercontent.com/3139777/145889658-cbd7dfd9-d99c-47c2-ae1f-d4dad1191374.png)

By looking at [sst-debug.log](https://github.com/serverless-stack/serverless-stack/files/7707235/sst-debug.log) and the last modified times of files in `.build/cdk.out` I think the prisma layer was rebuilt but it looks like the majority of the time was spent building and zipping (possibly uploading) the lambda code:

```sh
# UTC-04:00 time
❯ tree -ahLD 2 .build/cdk.out/
.build/cdk.out/
├── [ 17M Dec 13 15:06]  asset.6fd5340521eb3bc5ab2862754cbcea74cb0a4275a1b49c5d2f751fae8653421d.zip
├── [4.0K Dec 13 15:57]  asset.aedcdb18abacdd4fbf2c73d9456eb412ead3c153d2a104348b545c99c778592b
│   ├── [4.0K Dec 13 15:57]  apps
│   ├── [4.0K Dec 13 15:57]  node_modules
│   ├── [  76 Dec 13 15:57]  package.json
│   └── [1.1K Dec 13 15:57]  package-lock.json
├── [4.0K Dec 13 16:34]  .cache
│   └── [4.4M Dec 13 16:35]  aedcdb18abacdd4fbf2c73d9456eb412ead3c153d2a104348b545c99c778592b.zip
├── [  20 Dec 13 16:34]  cdk.out
├── [ 57K Dec 13 16:34]  manifest.json
├── [ 18K Dec 13 16:34]  prod-ZAula-DataGraphStack.template.json
└── [ 41K Dec 13 16:34]  tree.json

4 directories, 8 files
```

- 51 min building `.build/cdk.out/asset.aedcdb18*` directory!?
- 38 min zipping (and uploading) the file `.build/cdk.out/.cache/aedcdb18*.zip`!?

Here's the state of CDKToolkit's bucket after the deployment finished (UTC-03:00 time). Last friday I upgraded Prisma and made a full deployment including the lambda layer and I'm pretty sure it did not take this long:

![image](https://user-images.githubusercontent.com/3139777/145888828-2c38d39c-7648-4ad6-bdf2-188c0d755bb2.png)

related issue: #1121

**Comment by fwang** [comment]
Hey @iquabius, both the time for building and zipping seem surprisingly long.

If you run `sst build`, does it takes ~50min to build every time?

**Comment by iquabius** [comment]
It doesn't happen every time. I remember deploying last Friday and I'm pretty sure it didn't take take long.

But I run `npx sst build --verbose` and it took 40m 15s:

[sst-debug.log](https://github.com/serverless-stack/serverless-stack/files/7712619/sst-debug.log)

I think it may be a problem with my computer but I'm not sure. CPU and memory usage and seems reasonable:

![image](https://user-images.githubusercontent.com/3139777/146023021-cca8a947-3ad7-475a-8abd-36035d9a58ee.png)

Here's my setup:

```sh
zaula on  update-sst-and-cdk [$!?] via  v14.14.0 on ☁️  (us-west-2) took 4s
❯ neofetch
         eeeeeeeeeeeeeeeee            iqb@Naka
      eeeeeeeeeeeeeeeeeeeeeee         --------
    eeeee  eeeeeeeeeeee   eeeee       OS: elementary OS 5.1.7 Hera x86_64
  eeee   eeeee       eee     eeee     Host: Inspiron 15-3567
 eeee   eeee          eee     eeee    Kernel: 4.15.0-159-generic
eee    eee            eee       eee   Uptime: 4 days, 4 hours, 33 mins
eee   eee            eee        eee   Packages: 2379
ee    eee           eeee       eeee   Shell: fish 3.3.1
ee    eee         eeeee      eeeeee   Resolution: 1366x768, 2560x1080
ee    eee       eeeee      eeeee ee   DE: Pantheon
eee   eeee   eeeeee      eeeee  eee   WM: Mutter(Gala)
eee    eeeeeeeeee     eeeeee    eee   CPU: Intel i5-7200U (4) @ 3.100GHz
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee    GPU: Intel HD Graphics 620
  eeeeeeee eeeeeeeeeeee      eeee     Memory: 14014MiB / 15827MiB
    eeeee                 eeeee 
      eeeeeee         eeeeeee                                 
         eeeeeeeeeeeeeeeee 
```

**Comment by iquabius** [comment]
I reinstalled all my node dependencies and the build took 15m 29s:

```sh
mv node_modules node_modules.bak
npm i
npx sst build --verbose
```

[sst-debug.log](https://github.com/serverless-stack/serverless-stack/files/7713784/sst-debug.log)

**Comment by iquabius** [comment]
This problem is gone.

The deploy has been taking less than 10 minutes for a few weeks now.

I have no idea what was the issue.
