### ISSUE TITLE
Permissions not being set as expected with S3 and DynamoDB

### ISSUE THREAD

**Issue by ryanmalesic** [serverless-stack/serverless-stack#116]
S3 and DynamoDB have different IAM resource strings depending whether referring to buckets vs items (S3) and tables vs index (DynamoDB). Below is an example of what currently needs done to add permissions to the index of a table. 

```
api.attachPermissions([
    table,
    new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ["dynamodb:*"],
        resources: [`${table.dynamodbTable.tableArn}/index/*`],
    }),
])
```
The [table] should automatically set the permissions to the indices, or there some be some shorter way to specify the indices / specific index to set permissions on.

S3 has the same issue. There is a difference between the bucket and items resources. Granting with ```attachPermissions([bucket])``` only grants permissions on the bucket, not item based permissions like GetItem and PutItem. Currently, the way to work around this issue is below. 

```
new iam.PolicyStatement({
    effect: iam.Effect.ALLOW,
    actions: ["s3:*"],
    resources: [`${bucket.bucketArn}`, `${bucket.bucketArn}/*`],
}),
```

**Comment by fwang** [comment]
I see! Let me give it a quick try.
