### ISSUE TITLE
Upgrade to CDK 2.0?

### ISSUE THREAD

**Issue by thyming** [serverless-stack/serverless-stack#1160]
CDK 2 is now GA, but provides a large set of incompatibilities (mostly trivial to fix in source). Is there a plan to upgrade these libraries to CDK 2?

**Comment by thdxr** [comment]
Yes! We're working on it this month and will do a release early next year

**Comment by mwawrusch** [comment]
Happy New Year! 

Checking in regarding an ETA for this. We have put a project on hold till this is resolved so any ETA would be helpful for planning consistancy.

**Comment by fwang** [comment]
Hey @mwawrusch thanks for checking in.

We are working on this! Should have this ready over the next week or two.

**Comment by fwang** [comment]
Related to #1076

**Comment by thyming** [comment]
closing in favor of #1076, sorry for the duplicate!

**Comment by fwang** [comment]
@thyming oh no worries! I'm working on this as we speak.

**Comment by fwang** [comment]
Hey everyone, we just released v0.57.0 with CDK v1.138.0, the latest version for CDK v1. We will cut another release soon with CDK v2.4.0 in the coming days.

If you have an existing SST project, it is recommenced that you update to v0.57.0 first. CDK v1.138.0 and CDK v2.4.0 are feature parity, so it will be a smoother transition when updating to the upcoming release.

**Comment by fwang** [comment]
Updated to CDK v2 in [v0.59.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.59.0). See release notes for steps to update.
