### ISSUE TITLE
sst-env requires the package consuming the environment variables to be a subdirectory of the sst project

### ISSUE THREAD

**Issue by Ivo-Evans** [serverless-stack/serverless-stack#1161]
This behaviour is incompatible with certain monorepo setups where the `sst.json` is in a sibling directory. My suggestion is to keep the default behaviour, but allow users to customise the path with a command line argument.

Spec:
- [ ] The user should be able to use a command line argument called `path` to customise the path to the sst.json
- [ ] The `path` argument should use a relative url, so that sst-env commands can be shared by different team members working on the same project
- [ ] If there is no `path` argument, `sst-env` should work as before

Some work has already been done on this [here](https://github.com/Ivo-Evans/serverless-stack/tree/customise-directory), and if the spec is right, and no other work is being done which overlaps with it, I can submit a PR

**Comment by alistairstead** [comment]
I would really appreciate this being integrated as an option.

**Comment by fkjellberg** [comment]
I ran into the same issue trying to use SST in an existing monorepo where the React frontend has to be in a sibling directory. It would be great if this can be fixed in an upcoming release.

**Comment by fwang** [comment]
This is released in v0.65.2!

Thanks @Ivo-Evans!
