### ISSUE TITLE
Add an example to how to use RDS

### ISSUE THREAD

**Issue by paulocastellano** [serverless-stack/serverless-stack#118]
it would be excellent if we had an example of how to use relational banks using RDS.

For people who are learning how the serverless world works, it would be of great use.

**Comment by fwang** [comment]
@paulocastellano Totally. Can you share:
- What framework are you currently using for your non-serverless setup?
- What's the use case you have in mind for your serverless setup? ie.Api + Lambda + RDS
- Type of DB engine? ie. Postgres vs MySQL vs Aurora

Let me know. It helps us build a context around the example.
