### ISSUE TITLE
Usage of NodeJsFunction

### ISSUE THREAD

**Issue by hoegertn** [serverless-stack/serverless-stack#119]
If this tool specializes in NodeJS runtimes, is there a special reason not to use the lambda-nodejs implementation for your functions?

**Comment by jayair** [comment]
The CDK NodeJs construct you mean? We have to internally wire up the Live Lambda Environment and switch it out when we deploy it. So that requires us to handle the implementation.

**Comment by thdxr** [comment]
Hey @hoegertn going to close this issue for now.  Let us know if you have any further questions and we can reopen
