### ISSUE TITLE
Unable to access forked CDK CLI

### ISSUE THREAD

**Issue by mailletf** [serverless-stack/serverless-stack#12]
Hello,

I've got a stack built with SST that I can deploy. When trying to run a command with CDK, I get nothing back as if it isn't executed.

```
$ npx sst cdk list
Preparing @serverless-stack/resources
Linting source
Compiling with Babel
```

`list` can be replaced by any other CDK command and I get the same result.

npx version is 10.2.2, SST is 0.4.3 and I'm on OSX.

**Comment by jayair** [comment]
Sorry for the really late reply! I must've missed this somehow. We'll have a look at this shortly.

**Comment by jayair** [comment]
We'll be fixing this in an upcoming release.

**Comment by jayair** [comment]
This should be fixed in https://github.com/serverless-stack/serverless-stack/releases/tag/v0.5.0

Give it a try and reopen if you are having problems?
