### ISSUE TITLE
NextjsSite bug: Regeneration Lambda times out, causing excessive usage

### ISSUE THREAD

**Issue by christiankaindl** [serverless-stack/serverless-stack#1251]
## Setup
We are using SST's [NextjsSite](https://docs.serverless-stack.com/constructs/NextjsSite) construct to deploy a Next.js site to AWS.

## Issue/bug description
Recently we noticed that the "regeneration" Lambda (created by [NextjsSite here](https://github.com/serverless-stack/serverless-stack/blob/2f0f16934787b435639111c73efd39de665013c4/packages/resources/src/NextjsSite.ts#L480)) has way too many invocations for the amount of users which our site has (see below). After a quick investigation we found the issue: the lambda was timing out almost every single request. This in turn caused each regeneration item to be put back into the SQS queue of the NextjsSite construct, where it was tried again and again until after 4 days (default SQS `retentionPeriod`, per item)--**accumulating more and more items in the queue** as there is no Dead Letter Queue configured in the NextjsSite construct.

The `memorySize` of the CDK Lambda construct defaults to 128 ([source](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lambda.FunctionProps.html#memorysize)), which it seems is not enough to server render our app. As a workaround we increased the memory size of the regeneration Lambda manually in the AWS console.
See before/after:

Left before, right after our manual memory increase to the regeneration Lambda:
<img width="1088" alt="Screen Shot 2022-01-11 at 17 15 24" src="https://user-images.githubusercontent.com/15364860/148981237-4f8f0b6f-edf5-44ab-8a97-153d900fdee6.png">

We got almost **500 errors per 15 minutes** (our site has only 200-400 users per _day_). Green is the success rate in %, red is the error count per 15 mins:
<img width="792" alt="Screen Shot 2022-01-11 at 17 46 57" src="https://user-images.githubusercontent.com/15364860/148985542-17d407f6-6948-4575-b696-8317a7f9ef42.png">

## Workaround
For now, we increased the memory configuration by hand (to 1024MB) which fixed both the timeouts and the queue exploding in size. The increased memory together with a Dead Letter Queue would be the best solution in my opinion. Would it be possible to expose the SQS queue props and the the regeneration lambda props as options?

## Possible solutions
- **Fix in SST construct**. This would mean either raising the default regeneration Lambda memory size (breaking change), or adding an option to configure a Dead Letter Queue, so that errorred regenerations don't stay in the queue forever.
- **Fix in user land**. Currently not really possible, because the generated CDK resources [are private](https://github.com/serverless-stack/serverless-stack/blob/2f0f16934787b435639111c73efd39de665013c4/packages/resources/src/NextjsSite.ts#L117) on the NextjsSite construct. So the only real fix at the moment is to maintain a fork, but it would be awesome if the generated SQS queue and regeneration Lambda resources could be customized, so that users can modify them after creation. E.g. Adding a Dead Letter Queue to the regeneration queue, or increasing the regeneration lambda memory size.

In any case, I'd be happy to contribute a fix if that is appreciated. And thank you for such an awesome project!!

**Comment by fwang** [comment]
Hey @christiankaindl, a couple of changes in v0.60.9:
- u can configure regeneration queue via the `sqsRegenerationQueue` prop
- u can configure regeneration function via the `defaultFunctionProps` prop
- default memorySize for the regeneration function is changed to 1024MB
