### ISSUE TITLE
secretmanager.Secret.secretName translates to Fn::Split

### ISSUE THREAD

**Issue by q42jaap** [serverless-stack/serverless-stack#1257]
I'm generating a `secretsmanager.Secret` in a seperate stack (`SecretsStack`) and using it in the `ApiStack`:

```
import * as secretsmanager from '@aws-cdk/aws-secretsmanager';
export class SecretsStack extends sst.Stack {
  public someSecret: secretsmanager.Secret

  constructor(scope: Construct) {
    super(scope, 'SecretsStack')

    this.someSecret = new secretsmanager.Secret(this, 'Secret')
  }
}
```

Then I use `someSecret` in the `ApiStack`:
```
    const api = new Api(this, 'SomeApi', {
      defaultFunctionProps: {
        environment: {
          SOME_SECRET_NAME: secretsStack.someSecret.secretName,
...
```

The generated CF looks like this:
```
SOME_SECRET_NAME:
  Fn::Select:
    - 6
    - Fn::Split:
      - ":"
      - Fn::ImportValue: mystage-myproject-SecretsStack:ExportsOutputRefSecretA720EF052D953DED
```

However, the secretName is wrong: the actual name isn't the last part of the ARN, it's shorter:
```
Secret name
SecretA720EF05-qXGVonf5vBIT
Secret ARN
arn:aws:secretsmanager:eu-central-1::secret:SecretA720EF05-qXGVonf5vBIT-kdVTH4
```
Notice the `-kdVTH4` at the end.

I'm not sure if I'm doing something wrong or whether this is a bug.

**Comment by q42jaap** [comment]
I've tried to reproduce this with vanilla cdk, and this issue occurs also in `@aws-cdk/aws-secretmanager@1.139.0`.

This seems to be fixed in `aws-cdk-lib@`: the generated output splits on `-` and uses `Fn::Select 0` and `Fn::Select 1`.

Looking forward to the v2 update!

**Comment by fwang** [comment]
Hey @q42jaap, we updated SST to use CDK v2 in `0.59.0`, and have been iron out kinks here and there. The latest version `0.60.8` is stable.

Give that a try and please re-open this if the issue persist.
