### ISSUE TITLE
SST deploys lots of resources, when I really just want one stack (per stage) to be deployed

### ISSUE THREAD

**Issue by riyadshauk** [serverless-stack/serverless-stack#1260]
Is there a way to fix this problem? I was using the VSCode debugger, which was redeploying for me as I saved/made changes. Going along in this fashion isn't feasible.
![Screen Shot 2022-01-13 at 2 15 44 PM](https://user-images.githubusercontent.com/8068555/149418016-1e939e9e-b24e-4a12-8974-ab9087f46f44.png)
.

**Comment by riyadshauk** [comment]
Is the solution to eventually call `sst remove` to delete all those resources in one swoop when done developing? Side question, but does `sst remove` work when the stack changes (new resources/constructs are added) locally from what's been deployed, and a resource isn't found on AWS to delete. I've seen an error get reported, but I'm assuming it went ahead and deleted everything that was created that is part of the local stack code. Moreover, if a resource is removed from the local stack code, does `sst remove` know that it should delete the originally provisioned resource?

**Comment by riyadshauk** [comment]
Furthermore, how can I verify if every resource created is actually deleted in AWS (or not deleted) as a result of running `sst remove`?

**Comment by jayair** [comment]
@riyadshauk Just from eyeballing those resources, are they not a part of your app? Can you share what's in your app?

**Comment by riyadshauk** [comment]
Good point, my mistake, I think you're probably right.

And for checking which resources are actually there, this suffices for me for now https://console.aws.amazon.com/cloudformation
