### ISSUE TITLE
telemetry incompatible with node-fetch 3

### ISSUE THREAD

**Issue by cptflammin** [serverless-stack/serverless-stack#1264]
Upgrading to node-fetch 3 causes sst to raise an error when launching
npm run start
This seems to be related to sst telemetry
Disabling telemetry does not solve the issue, how can we get rid of it?

Error [ERR_REQUIRE_ESM]: require() of ES Module
[….]/_trials/sst-ts/node_modules/node-fetch/src/index.js from
[….]/_trials/sst-ts/node_modules/@serverless-stack/core/dist/telemetry/post-payload.js not supported.
Instead change the require of index.js in
[….]//_trials/sst-ts/node_modules/@serverless-stack/core/dist/telemetry/post-payload.js to a dynamic import() which is available in all CommonJS modules.

How to reproduce:
1. install sst app with typescript
2. npm i node-fetch
3. npm run start

**Comment by fwang** [comment]
Hey @cptflammin, this should be fixed. We switched to using `https` instead of `node-fetch`.

Give `0.60.8` a try and please re-open this if the error persists.
