### ISSUE TITLE
Storing Secrets in Apollo GraphQL Serverless Stack Example

### ISSUE THREAD

**Issue by ngoctranfire** [serverless-stack/serverless-stack#1283]
Hi there, 
I am trying to figure out how to deal with fetching SSM secrets according to this documentation:
```
https://serverless-stack.com/chapters/storing-secrets-in-serverless-apps.html
```
IT seems that this document is a bit outdated so I referred to these Docs instead: https://docs.serverless-stack.com/environment-variables

I am trying to do the following to try and fetch my Secret from SSM. However, I am not sure how do I pass this so that it is able to be used in my lambda function. Is it possible for me to do that so that it is only fetched once before the function is deployed and then it is able to be used in the function? Here is what I'm doing:

```
import {ApolloServer, Config, CreateHandlerOptions} from "apollo-server-lambda";
import {LambdaContextFunctionParams} from "apollo-server-lambda/dist/ApolloServer";

import schema from "./graphql/schema";
import AWS from "aws-sdk";
import {GetParameterRequest} from "aws-sdk/clients/ssm";

const IS_LOCAL = !!process.env.IS_LOCAL;

const server = new ApolloServer(<Config<LambdaContextFunctionParams>>{
  schema,
  playground: {
    endpoint: "/dev/graphql"
  },
  introspection: IS_LOCAL,
});

const ssm = new AWS.SSM();
console.log(`Here is my secret anonkeyPath=${process.env.MY_SECRET_KEY}`);
const mySecretKeyPromise = ssm.getParameter(<GetParameterRequest>{
  Name: process.env.MY_SECRET_KEY,
  WithDecryption: true,
}).promise();

async function getSecretKey(): Promise<string | undefined> {
  try {
    const mySecretKey: string | undefined = (await mySecretKeyPromise).Parameter?.Value;
    if (mySecretKey == undefined) {
      console.error("Anonymous secret Key was null");
    }
    return mySecretKey;
  } catch (error) {
    console.error("There was an error trying to fetch the super Anonymous Key", error);
    return undefined;
  }
}

// console.log(`Here is my event=`, event, `context=`, context);

const superSecretKey = getSecretKey();

console.log(`Here is my secret anonymous key=${superSecretKey}`);
export const handler = server.createHandler(<CreateHandlerOptions>{
  cors: {
    origin: true,
    credentials: true
  },
});
```
I'd love for some pointers and guidance on this!

**Comment by fwang** [comment]
Hi @ngoctranfire, essentially you make an AWS SDK call to SSM to fetch the value inside index file, and you can pass the value to your stacks.

I added an example in the doc - https://docs.serverless-stack.com/environment-variables#working-with-secrets
And here's a sample repo - https://github.com/fwang/sst-load-ssm

**Comment by ngoctranfire** [comment]
@fwang Thanks so much for such a detailed and awesome response. This has fixed my issue. I actually just passed it from the index.js (where I got my parameter store values) and passed it into the Environment Props. Your example was super helpful to help me get this setup. It was a lot simpler than I expected!
