### ISSUE TITLE
Can we configure the `lib/` folder?

### ISSUE THREAD

**Issue by mmkal** [serverless-stack/serverless-stack#1289]
Hi there! We have an existing project already using the `lib` folder which we'd like to add sst to. Can we set the entrypoint to `sst/index.ts` or similar? We achieve this in cdk by configuring in `cdk.json`:

```json
{
  "app": "ts-node cdk/app.ts",
  "context": {
    ...
  }
}
```

So `sst/something.ts` would be our preference not just to avoid `lib` conflict, but to make the analogy clear and ease the learning curve.

**Comment by fwang** [comment]
Hey @mmkal you can set the "main" field in "sst.json". Here's an example https://docs.serverless-stack.com/installation#project-config

**Comment by mmkal** [comment]
Ah perfect, thank you. Not sure how I missed that.
