### ISSUE TITLE
AWS CDK Update

### ISSUE THREAD

**Issue by justindra** [serverless-stack/serverless-stack#13]
The AWS CDK is up to `1.78.0` and this one is still on `1.61.0`, Any chance we can get that updated to be closer to recent?

**Comment by jayair** [comment]
Hi @justindra, yup we'll be updating it shortly.

**Comment by jayair** [comment]
Updated to 1.79.0.

https://github.com/serverless-stack/serverless-stack/releases/tag/v0.4.4
