### ISSUE TITLE
npm init fails to create TypeScript project

### ISSUE THREAD

**Issue by ozeebee** [serverless-stack/serverless-stack#133]
Hi, 
As described in the [documentation](https://docs.serverless-stack.com/installation), I'm trying to create a TypeScript project with `npm init`:
```
npm init serverless-stack@latest sst-test1 --language typescript
```
But it creates instead a JavaScript project:
```
➜ npm init serverless-stack@latest sst-test1 --language typescript

Initializing a new Serverless Stack JavaScript project
Creating sst-test1/ directory
Adding project files
Installing packages
...
```
Only JS files and no `.tsconfig`.

My environment: 
* Node 14.15.5
* npm 7.5.4

Note that this works when using the `npx` command though...
```
➜ npx create-serverless-stack@latest sst-test1 --language typescript

Initializing a new Serverless Stack TypeScript project
Creating sst-test1/ directory
Adding project files
Installing packages
```

**Comment by jayair** [comment]
Oh that's weird. Maybe the options aren't getting passed in in the CLI. We'll take a look.

**Comment by ozeebee** [comment]
non node/npm arguments should be passed after dash-dash "--"
So in this case, the command should be:
```
npm init serverless-stack@latest my-sst-app -- --language typescript
```

**Comment by jayair** [comment]
Yeah that makes sense. We'll update the docs with it.
