### ISSUE TITLE
mongodb example has problem transpiling the Lambda handler

### ISSUE THREAD

**Issue by spendres** [serverless-stack/serverless-stack#1333]
Current version of example builds with package.json in src, but then upon lambda invocation produces following runtime error:

There was a problem transpiling the Lambda handler: > error: Cannot use "external" without "bundle"

**Comment by thdxr** [comment]
That example probably needs to be updated.  Can you try specifying bundle like this
```
bundle: {
  nodeModules: ["mongodb"]
}
```

**Comment by spendres** [comment]
I had to modify /stacks/MyStacks.js to specify the bundle like this:
bundle: {
  nodeModules: ["src/mongodb"]
}

The example uses a package.json in the src directory to work around esbuild
incompatibilities and that is where the mongodb module resides.

Thanks!

**Comment by fwang** [comment]
@Manitej66 Not sure if you've tried out the MongoDB example. Can you give it a try and see if you can reproduce the issue?

**Comment by Manitej66** [comment]
Sure, will test it

**Comment by Manitej66** [comment]
I can confirm this issue, will update the example.
