### ISSUE TITLE
mongodb example connection string instructions

### ISSUE THREAD

**Issue by spendres** [serverless-stack/serverless-stack#1344]
The instructions include this connection string: 

>mongodb+srv://mongodb:<password>@serverlessinstance0.j9n6s.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

But the example uses the database named 'demo', so the string should be either:

>mongodb+srv://mongodb:(password)@serverlessinstance0.j9n6s.mongodb.net/demo?retryWrites=true&w=majority

or;

>mongodb+srv://(username):(password)@serverlessinstance0.j9n6s.mongodb.net/demo?retryWrites=true&w=majority

...where (username) and (password) are provided by Mongo's admin interface for the serverless instance. Your user may be assigned the username 'mongodb' or some other username.

**Comment by fwang** [comment]
@jayair you looked at the Mongo example recently. Can you take a look at this?

**Comment by Manitej66** [comment]
This is fixed
