### ISSUE TITLE
Create an AAAA record for React sites

### ISSUE THREAD

**Issue by pupeno** [serverless-stack/serverless-stack#1354]
When creating a React site with a customDomain SST creates an A record for it. I'd like to request to also create an AAAA record for it.

**Comment by pupeno** [comment]
I created a pull request. I haven't really tested the code. I'm not sure if this sort of change is welcome/wanted. Happy to put more effort if that's the case. I'm pretty sure it'll work, since the API for creating AAAA records is identical to creating A records. But I also think SST should be consistently supporting IPv6 everywhere it can, so maybe searching for other places where this could be done as well would be a good idea. I'm happy to do that as well.

If this is a welcome change, I'll figure out how to run these changes locally on my computer, test them, etc.

**Comment by fwang** [comment]
Thanks @pupeno!

Also fixed for API and NextjsSite.
