### ISSUE TITLE
SSL local interface assumes 'us-east-2'

### ISSUE THREAD

**Issue by NigelThorne** [serverless-stack/serverless-stack#1359]
When I have a bucket in my stack 
```
    const bucket = new sst.Bucket(this, "Bucket", {
      s3Bucket: {
        // Delete all the files
        autoDeleteObjects: true,
        // Remove the bucket when the stack is removed
        removalPolicy: RemovalPolicy.DESTROY,
      },
      notifications: [
        {
          function: {
            handler: "src/import_UP_file.main",
            bundle: {
              nodeModules: ["stream", "json-bigint", "JSONStream"],
            },  
            environment: {
              queueUrl: queue.sqsQueue.queueUrl,
            },
          },
          notificationProps: {
            events: [EventType.OBJECT_CREATED],
          },
        },
      ],
    });
```
![image](https://user-images.githubusercontent.com/5942/153755111-667815aa-434e-4aeb-af97-60a70c928915.png)

The local UI shows pending events... but my stack is all in `ap-southeast-2` and the link to the pending event is `https://ap-southeast-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#xray:traces/1-xxxxxxxxx-xxxxxxxxxxxxxxxxxx85649` 

 Note the `region=us-east-2`. Thats what seems wrong.

**Comment by fwang** [comment]
@NigelThorne thanks for bringing this up!

Just pushed out an update, should be fixed now.
