### ISSUE TITLE
OpenSearch domain error in AppSyncApi defaultFunctionProps

### ISSUE THREAD

**Issue by jbrown** [serverless-stack/serverless-stack#1362]
I have declared an `opensearch.Domain`, a `sst.Table` and an `sst.AppSyncApi` in my stack. The table has a stream consumer that receives the domain's `domainEndpoint` in its environment without any errors. Then I tried to do same in the api `defaultFunctionProps` but it throws an error `Unable to retrieve DomainEndpoint attribute for AWS::OpenSearchService::Domain, with error message Internal error occurred.` If I refactor the api and instead of passing it in `defaultFunctionProps` to all resolver functions I just set the environment of a single resolver directly it does not error. So there is some difference between `defaultFunctionProps` and directly setting the environment for a resolver function.

**Comment by fwang** [comment]
Hi @jbrown, can you share a snippet of how you are creating the `opensearch.Domain` and how you are passing it into the `sst.AppSyncApi`?

**Comment by jbrown** [comment]
@fwang I'm fairly new to CDK so it's entirely possible I'm doing something wrong. I can't make my codebase public but I'm happy to jump on a screenshare if you can't recreate.

```javascript
this.searchDomain = new opensearch.Domain(this, 'Domain', {
  version: opensearch.EngineVersion.OPENSEARCH_1_0,
  enableVersionUpgrade: true,
  useUnsignedBasicAuth: true,
  enforceHttps: true,
  fineGrainedAccessControl: {
    masterUserName: 'admin',
    masterUserPassword: cdk.SecretValue.plainText('Password-123'),
  },
  capacity: {
    dataNodeInstanceType: 't3.small.search',
    dataNodes: 1,
  }
})

this.table = new sst.Table(this, 'dynamodb', {
  // ...
  stream: true,
  consumers: {
    consumer: {
      handler: 'src/table/consumer.main',
      environment: {
        OPENSEARCH_PASSWORD: this.searchDomain.masterUserPassword.toString(),
        OPENSEARCH_ENDPOINT: this.searchDomain.domainEndpoint, // no errors here
      }
    }
  }
})

this.api = new sst.AppSyncApi(this, 'api', {
  // ...
  defaultFunctionProps: {
    environment: {
      OPENSEARCH_PASSWORD: this.searchDomain.masterUserPassword.toString(),
      OPENSEARCH_ENDPOINT: this.searchDomain.domainEndpoint, // Error: Unable to retrieve DomainEndpoint attribute for AWS::OpenSearchService::Domain, with error message Internal error occurred.
    },
  },
  resolvers: {
    'Query someQuery': {
      handler: 'src/query/someQuery.main',
      environment: {
        OPENSEARCH_PASSWORD: this.searchDomain.masterUserPassword.toString(),
        OPENSEARCH_ENDPOINT: this.searchDomain.domainEndpoint, // no errors if I set it here instead and remove it from defaultFunctionProps
      }
    }
  }
})
```

**Comment by fwang** [comment]
hmm.. that is really weird. Can you do a `sst build` and send me the CloudFormation template file in `.build/cdk.out`?

^^feel free to DM me on Slack if it contains sensitive info https://serverless-stack.com/slack

**Comment by fwang** [comment]
@jbrown thanks for sharing the template. To be honest, I don't spot anything weird.

I read the CDK thread https://github.com/aws/aws-cdk/issues/18239, and it makes me want to say this is a CloudFormation bug. Such that when you set `this.searchDomain.domainEndpoint` inside `defaultFunctionProps`, could it be that CloudFormation is doing multiple lookups and it is likely that one of them fail.

**Comment by jbrown** [comment]
@fwang Yep, throttling leading to intermittent errors. My AppSyncApi had ~20 lambda resolvers so this definitely explains it. I saw that you assigned this to yourself, feel free to close it as your discretion. Thanks for your help looking into it!

**Comment by fwang** [comment]
Sounds good! Let me know if u find a solution/workaround for this. I'd want to bake that into SST.
