### ISSUE TITLE
Access Cognito Resources from a lamda function?

### ISSUE THREAD

**Issue by dmueller39** [serverless-stack/serverless-stack#1370]
I'd like to access the cognito usernames in a lambda function. Based on my understanding the best way to do that is to use a CognitoIdentityServiceProvider. This means the lambda function will need the permission to access this resource. The text on [this page](https://serverless-stack.com/chapters/customize-the-serverless-iam-policy.html) seems to indicate that the administrator access is all that is needed on the IAM role level. However the lambda functions have custom permissions policies attached to them that do not include cognito resource access.

Is there a way to configure access to cognito in lambda?

I am happy to supply more details.

**Comment by fwang** [comment]
Hi @dmueller39, how are you configuring the custom permissions for your Lambda functions? Try adding "cognito:*" to that list as a test, and see if it works.

**Comment by dmueller39** [comment]
Thanks for the suggestion! After revisiting this with fresher eyes, I noticed the `this.api.attachPermissions` in the `ApiStack.js` file. This appears to attach the permissions to all lambda functions which is fine. I only wanted the get user name permission which i added like this:
```
    this.api.attachPermissions([
      table,
      "cognito-idp:AdminGetUser",
    ]);
```
The specific permission was noted in the error message in my terminal that was running sst:
> ... is not authorized to perform: cognito-idp:AdminGetUser on ...

Thanks!

**Comment by dmueller39** [comment]
As a follow up to this, I am noticing that the most reliable way to get information about the currently logged in user is to send the access token from the client to the lambda function. The accessToken allows lambda to call the GetUser api on the cognito service. Does this seem reasonable? It feels like an anti pattern to explicitly add the access token to all the requests, when the request is already getting authenticated. Any thoughts on this?

**Comment by dmueller39** [comment]
To save others time:

- A requirement for the app we are building is to use the username from the login as public identification in the app. This is similar to how user names are treated in Reddit/Twitter/GitHub.
- Cognito Identity does not map from the identityId (`event.requestContext.authorizer.iam.cognitoIdentity.identityId`) to the username in any useful way. Describe identity will give you the current identity, but doesn't take the extra step of providing the username of the user from the user pool. https://github.com/aws/aws-sdk-js/blob/master/clients/cognitoidentity.d.ts#L45
- The CognitoIdentityServiceProvider GetUser can only query the current user based on the access token. Securely retrieving the username requires passing the accessToken to the lambda function from the client:`const accessToken = (await Auth.currentSession()).getAccessToken().getJwtToken();`(Don't use autocomplete for this one, it suggested getIdToken() for me, and I burned an hour trying to figure that out.

**Comment by fwang** [comment]
@dmueller39 Thanks for sharing. Glad you got it to work!
