### ISSUE TITLE
can i set api.url?

### ISSUE THREAD

**Issue by dengjie-ys** [serverless-stack/serverless-stack#1372]
Can I set their api.url the same in different stacks?

**Comment by dengjie-ys** [comment]
i have two stacks, after deploy, they have different api.url.Is there a way for different stacks to use the same url?

**Comment by fwang** [comment]
Hi @dengjie-ys, yeah, you can create the `Api` in one stack, and then pass it to another stack to add more routes to it. Here's an example https://docs.serverless-stack.com/constructs/Api#sharing-an-api-across-stacks

Let me know if that works for you.

**Comment by dengjie-ys** [comment]
Thanks a lot, this is the answer I want！
