### ISSUE TITLE
How to turn off bundle minification for GraphQLApi instance?

### ISSUE THREAD

**Issue by wavesrcool** [serverless-stack/serverless-stack#1394]
Hello,

As per the documentation [https://docs.serverless-stack.com/constructs/Function#minify] there is a boolean parameter to turn off JS bundle minification for functions.

We require to run with bundle minification turned off for a GraphQL API as our GraphQL type names are being altered in production by the minification.

Any help with how minification can be turned off would be most welcome.

Thank you.

**Comment by fwang** [comment]
Hi @wavesrcool, does this work for you:
```js
new GraphQLApi(this, "Api", {
  server: {
    handler: "src/graphql.handler",
    bundle: {
      minify: false,
    },
  },
});
```

**Comment by wavesrcool** [comment]
This has worked perfectly, thank you.
