### ISSUE TITLE
Change SST logicalPrefixedName naming to match serverless 3.0 update

### ISSUE THREAD

**Issue by brucek** [serverless-stack/serverless-stack#14]
Serverless 3.0 is changing the naming convention to ${service}-${stage}:

https://www.serverless.com/framework/docs/deprecations#api-gateway-naming-will-be-changed-to-service-stage

however, the logicalPrefixedName function is not in sync:

https://github.com/serverless-stack/serverless-stack/blob/45d957853be0017ac84bbe315ef1d132b2648fb3/packages/resources/src/App.ts#L56

the SST scoped naming should also honor this as well so all stacks and resources are aligned:

https://github.com/serverless/serverless/blob/03859c04720f9071d0590b5d0ad1fa0e2c6770b3/lib/plugins/aws/lib/naming.js#L253

**Comment by jayair** [comment]
Hmm the `logicalPrefixedName` wasn't meant to be in sync with Serverless. It was more meant to ensure uniqueness when deployed to different stages.

What's your use case for keeping them in sync?

**Comment by brucek** [comment]
oh really?  as a new serverless user, I am following https://serverless-stack.com/chapters/building-a-cdk-app-with-sst.html to get started

With the serverless 3.0 update, I now have a bunch of AWS infrastructure stacks named ${stage}-${service} while my main serverless stack is called ${service}-${stage}.  It seems like a better situation to have all the stacks listed together in the AWS CloudFormation console, and it seemed like Serverless would be the logical lead on naming, and/or that the same logic for making that change would apply here.

**Comment by brucek** [comment]
Here is the source issue in Serverless and their rationale (seems like the same logic: keep them listed together in AWS console):  https://github.com/serverless/serverless/issues/2918

**Comment by jayair** [comment]
Yeah their naming used to be a bit all over the place before. This is a bit of a bigger change for sst since it affects existing apps. But we are trying to figure out if there is a way to migrate some services over from Serverless Framework and this naming scheme is a part of that.

**Comment by thdxr** [comment]
Going to close this issue for now, @brucek let us know if this is still a problem for you and we can re-open it
