### ISSUE TITLE
Support for DynamoDB global tables?

### ISSUE THREAD

**Issue by mostthingsweb** [serverless-stack/serverless-stack#1440]
It doesn't seem like Global Tables are supported. CDK does support them though: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-dynamodb.Table.html

Is this planned?

**Comment by fwang** [comment]
Hey @mostthingsweb, SST is actually built on top of CDK with full flexibility. I just added an example of enabling Global Tables here https://docs.serverless-stack.com/constructs/Table#enabling-global-tables

Let me know if that works for you.

**Comment by introtochaosbook** [comment]
> Hey @mostthingsweb, SST is actually built on top of CDK with full flexibility. I just added an example of enabling Global Tables here https://docs.serverless-stack.com/constructs/Table#enabling-global-tables
> 
> Let me know if that works for you.

Looks like it works, thanks!

**Comment by mostthingsweb** [comment]
> Hey @mostthingsweb, SST is actually built on top of CDK with full flexibility. I just added an example of enabling Global Tables here https://docs.serverless-stack.com/constructs/Table#enabling-global-tables
> 
> Let me know if that works for you.

It worked :). Thanks for the quick documentation update!
