### ISSUE TITLE
Attempting to remove a stack which doesn't exist produces a cryptic error message?

### ISSUE THREAD

**Issue by jamesrusso** [serverless-stack/serverless-stack#15]
I am getting a strange error message when attempting to remove a stack which does not exist. I would think the desired result would be just letting the user know that the stack does not exist. 

SST: 0.4.4
CDK: 1.79.0

Preparing @serverless-stack/resources
Linting source
Detected tsconfig.json
Compiling TypeScript
Removing stacks
doesnotexist-aeroluxmaps-infrastructure-website: destroying...
doesnotexist-aeroluxmaps-infrastructure-dynamodb: destroying...

 ✅  doesnotexist-aeroluxmaps-infrastructure-dynamodb: destroyed
 **_❌  doesnotexist-aeroluxmaps-infrastructure-dynamodb failed: TypeError: Cannot destructure property 'status' of '(intermediate value)' as it is undefined._**
 ✅  doesnotexist-aeroluxmaps-infrastructure-website: destroyed
 **_❌  doesnotexist-aeroluxmaps-infrastructure-website failed: TypeError: Cannot destructure property 'status' of 
'(intermediate value)' as it is undefined._**

**Comment by jayair** [comment]
Yeah the error messages there don't make sense. We'll have a look into it.

**Comment by jamesrusso** [comment]
Great project and tutorial, really helping my workflow..

**Comment by thdxr** [comment]
Hey @jamesrusso going to close this issue for now.  If it's still an issue for you let us know and we can reopen it
