### ISSUE TITLE
Support subscription filter for SNS subscribers

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#151]
Requested by Sione on Slack

**Comment by aarvay** [comment]
+1. Need this for a project I'm working right now.

Is it possible to filter messages in SNS somehow today?

**Comment by fwang** [comment]
Hey @aarvay I'm working on this. I can cut a released later today.

**Comment by aarvay** [comment]
Thanks @fwang, that'd be great 👍🏽

**Comment by fwang** [comment]
Support for subscription filter has been added to v0.9.12. Here’s an example on how to set subscription filter https://docs.serverless-stack.com/constructs/Topic#configuring-a-subscriber

To update:
```
$ npm install --save --save-exact @serverless-stack/cli@0.9.12 @serverless-stack/resources@0.9.12
```
