### ISSUE TITLE
deploy --outputs-file with full path goes to wrong place

### ISSUE THREAD

**Issue by drewfish** [serverless-stack/serverless-stack#1526]
Hi,

I'm doing `sst deploy --outputs-file {path}` where I've specified a full path to the outputs file. However, it interprets that path as relative to service, which leads to quite unexpected results.

I suspect that the issue might be the use of `path.join()` here:
https://github.com/serverless-stack/serverless-stack/blob/89c3ff9/packages/cli/scripts/deploy.js#L28
In this case `path.resolve()` might be a better choice. (It works like `path.join()` for relative paths, but handles full paths well.)

**Comment by fwang** [comment]
Hey @drewfish a PR would be great!

If I recall, this is the only place we take a path. But if u come across others, feel free to apply the same fix or lemme know and I will put it in.
