### ISSUE TITLE
Same domain for multiple stages

### ISSUE THREAD

**Issue by ryanmalesic** [serverless-stack/serverless-stack#156]
api.{app}.com/dev for the dev stage and api.{app}.com/prod for prod stage currently fails on the second deploy because the ApiDomainName "api.{app}.com already exists in stack arn:aws:cloudformation...". 

Can this be corrected here, or is this an aws issue?

**Comment by fwang** [comment]
Yeah, in your setup, both stages tries to create a `Custom Domain` in Api Gateway called `api.{app}.com`. Because you deployed `dev` first, so `dev` managed to create it. And it fails for `prod` because the domain already exists in your Api Gateway account.

While I think we should try to handle this use case by allowing different stages to share a `Custom Domain`. It's not a clean solution. Image now `prod` reuses the domain that was created by `dev`, if you remove your `dev` stage, the custom domain would be removed (because it was created by `dev`), hence affect your `prod` api.

Usually, I recommend avoid such pattern. Try use different domains in this case, ie. `{stage}.api.{app}.com`. Or conditionally use `api.{app}.com` for prod, and `{stage}.api.{app}.com` for other stages.

Does that make sense?

**Comment by ryanmalesic** [comment]
Yeah it makes sense. i was working through the apig code and the "sharing" of a domain concept. there is a way to lookup exiting domains and it works fine, however it seems that it isn't even possible to have multiple stacks with the same domain. it can't create multiple A records with the same domain to the various apigs.

i will convert to nested subdomains as you suggested. thanks!

**Comment by fwang** [comment]
Ah yup. Again your use case is totally legit. Go with the subdomain approach for now, until we come up with a good design to share domains across stages.

**Comment by SethThomas** [comment]
How is this approach impacted by sharing Route 53 domains across different AWS accounts?   I want dev-api.mydomain.com pointing to my development resources in one AWS account, and api.mydomain.com pointing to my production resources in my separate AWS production account. 

I'm defining my custom domain as follows:

```Javascript
const stage = this.node.root.stage;
    const sdomain = stage == "prod" ? "api" : "dev-api";
    this.api = new sst.Api(this, "api", {
      customDomain: `${sdomain}.mydomain.com`,
      defaultAuthorizationType: sst.ApiAuthorizationType.AWS_IAM,
      defaultFunctionProps: {
        environment: {
          tableName: tableName,
          region: tableRegion
        }
      },
      routes: {
        // routes defined here
      }
    });
```

My CI environment (Seed) has separate IAM credentials for my development and production accounts. 

My development API builds and deploys successfully, but the Cleanup phase fails while generating artifacts for the production downstream stage.  This prevents me from promoting my development build to production.  I suspect this has something to do with how I'm defining the customDomain in SST.  The relevant snippet from the build logs:

```
Reading hosted zone <PROD_ACCT_ID>:us-west-2:mydomain.com
[AWS route53 200 0.387s 0 retries] listHostedZonesByName({ DNSName: 'mydomain.com' })
Found the following zones [{"Id":"/hostedzone/Z0974876HMVPO9LBHXW6","Name":"api.mydomain.com.","CallerReference":"34fd2cd1-2fd4-49d5-ac01-0b3c51bf2b12","Config":{"Comment":"","PrivateZone":false},"ResourceRecordSetCount":4},{"Id":"/hostedzone/Z05776761BGIRSM2PVWP7","Name":"api.mydomain.com.","CallerReference":"a4d80565-9fba-4a4a-97da-03b061decf4b","Config":{"Comment":"","PrivateZone":false},"ResourceRecordSetCount":4}]
Found the following matched name zones []
Setting "hosted-zone:account=917647775495:domainName=mydomain.com:region=us-west-2" context to {"$providerError":"Found zones: [] for dns:mydomain.com, privateZone:undefined, vpcId:undefined, but wanted exactly 1 zone","$dontSaveContext":true}
```

and the ultimate error message:
```

Not making progress trying to resolve environmental context. Giving up.
[Error at /prod-signup-and-run-api-stack/api] Found zones: [] for dns:mydomain.com, privateZone:undefined, vpcId:undefined, but wanted exactly 1 zone
  Annotations.addMessage (/tmp/seed/source/node_modules/@aws-cdk/core/lib/annotations.ts:92:25)
  Annotations.addError (/tmp/seed/source/node_modules/@aws-cdk/core/lib/annotations.ts:51:10)
  Function.getValue (/tmp/seed/source/node_modules/@aws-cdk/core/lib/context-provider.ts:111:31)
  Function.fromLookup (/tmp/seed/source/node_modules/@aws-cdk/aws-route53/lib/hosted-zone.ts:124:65)
  new Api (/tmp/seed/source/node_modules/@serverless-stack/resources/src/Api.ts:182:45)
  new ApiStack (/tmp/seed/source/lib/ApiStack.js:17:16)
  Object.handler (/tmp/seed/source/lib/index.js:18:20)
  Object.<anonymous> (/tmp/seed/source/.build/run.js:64:16)
  Module._compile (internal/modules/cjs/loader.js:1138:30)
  Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
  Module.load (internal/modules/cjs/loader.js:986:32)
  Function.Module._load (internal/modules/cjs/loader.js:879:14)
  Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
  internal/main/run_main_module.js:17:47
Error: Found errors
    at StackCollection.processMetadataMessages (/tmp/seed/source/node_modules/sst-cdk/lib/api/cxapp/cloud-assembly.ts:201:13)
    at CdkToolkit.validateStacks (/tmp/seed/source/node_modules/sst-cdk/lib/cdk-toolkit.ts:536:12)
    at CdkToolkit.selectStacksForDiff (/tmp/seed/source/node_modules/sst-cdk/lib/cdk-toolkit.ts:506:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at CdkToolkit.synth (/tmp/seed/source/node_modules/sst-cdk/lib/cdk-toolkit.ts:381:20)
    at Object.synth (/tmp/seed/source/node_modules/sst-cdk/lib/serverless-stack.ts:86:15)
    at Object.synth (/tmp/seed/source/node_modules/@serverless-stack/core/index.js:17:10)
    at synth (/tmp/seed/source/node_modules/@serverless-stack/cli/scripts/util/cdkHelpers.js:396:15)
    at Object.module.exports [as build] (/tmp/seed/source/node_modules/@serverless-stack/cli/scripts/build.js:31:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Error: Found errors
ERROR: Failed to generate artifact for downstream stage prod.
INFO: Saving source code cache...
INFO: Saving dependency cache...
```

**Comment by SethThomas** [comment]
I got past the error by manually creating a hosted zone through the AWS console that matches the hosted zone the build was looking for: `mydomain.com`

I'm not sure if this was the expected behavior, as I was under the impression that setting the `customDomain` field in the Api construct would create this for me.  🤷‍♂️
