### ISSUE TITLE
Cli: cdk binary not found when using PNPM

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#1578]
---
Requests:
- Will & Rob https://serverless-stack.slack.com/archives/C01JG3B20RY/p1648227833729619?thread_ts=1648212923.236929

**Comment by frekje-wm** [comment]
PR: #1582

**Comment by wweaver** [comment]
@fwang is there an ETA on when the pnpm cdk fix will be available?

cc @robbydooo

**Comment by fwang** [comment]
Hey @wweaver, v0.69.6 and v1.0.0-beta.20 have the fix. Sorry about the delay.

**Comment by wweaver** [comment]
Thanks @fwang! I'll check it out.

**Comment by wweaver** [comment]
Thanks @fwang, tested out that version and it seems to work for us!
