### ISSUE TITLE
Error with bootstrap-template in deploy step

### ISSUE THREAD

**Issue by ipatka** [serverless-stack/serverless-stack#16]
I added a new service to my deployment pipeline which builds a static site and uploads it to s3. I'm getting an error that I haven't seen on any other services and I'm not sure where to start debugging this one

```
====================
🚀 Deploy
====================
$ cd /tmp/seed/source
INFO: before_deploy hook not found. You can define it in your build spec.
INFO: Learn more about adding a build spec - seed.run/docs/adding-a-build-spec
$ cd /tmp/seed/source/clients/web/web-infra
INFO: Deploying 1 stack...
❌ dev-web-infra-my-stack: ENOENT: no such file or directory, open '/var/task/bootstrap-template.yaml'
```

**Comment by ipatka** [comment]
I think this is resolved. This may have been an unclear error for the fact that my output directory for my static site was not the correct directory containing the HTML.

FWIW this is my `beforeBuild` script prior to deploying the static site

```
  - if [ $SEED_SERVICE_NAME = "web-infra" ]; then cd /tmp/seed/source/clients/web && npm ci && npm run build && npm run export; fi
  ```

**Comment by jayair** [comment]
Glad you figured it out. Let's leave this open for now, so we can add some debug info for this error.

**Comment by ipatka** [comment]
Getting this again when doing the prod deploy. New theory is that this is due to this error

```
dev-web-infra-static-site failed: Error: This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://[ACCOUNT_ID]/us-east-1")
```

locally it gets caught and runs `cdk bootstrap` but it might be missing that on Seed

**Comment by ipatka** [comment]
Ok I think I got it now. Here is my pre-deploy step. This is needed before deploying a stack with assets.

```
before_deploy:
  - >
    if [ $SEED_SERVICE_NAME = "web-infra" ]; then
      cd /tmp/seed/source/clients/web/web-infra && npm ci && \
      env CDK_NEW_BOOTSTRAP=1 npx cdk bootstrap \
      --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
      aws://$ACCOUNT_ID/us-east-1;
    fi
```
