### ISSUE TITLE
Output from type checking doesn't seem to appear

### ISSUE THREAD

**Issue by olivvybee** [serverless-stack/serverless-stack#1615]
After creating a new application using `npx create-serverless-stack test-app --language typescript` we aren't seeing any output from type checking when running `npm start` or `npm run build`.

For example here I've purposefully introduced a typescript error into the default `lambda.ts` and VSCode correctly flags it as an issue, but there's no output in the console about any type errors:

<img width="1132" alt="Screenshot 2022-04-11 at 15 27 26" src="https://user-images.githubusercontent.com/661493/162761954-6018a391-850c-4a43-ab76-8cc152596153.png">

As you can see there is a runtime error when I invoke the function, but no output from the type checker.

Even explicitly setting `"typeCheck": true` in `sst.json` doesn't seem to enable type checking.

The [CLI documentation](https://docs.serverless-stack.com/packages/cli#build-process) implies that type checking should be happening by default in a typescript project.

This is with `@serverless-stack/cli` at version `0.69.5`.

Are we missing something?

**Comment by olivvybee** [comment]
Thanks for the info, it's probably worth updating the docs with a comment to that effect because we were scratching our heads trying to work out where/when the type checking was happening.

**Comment by thdxr** [comment]
@olivvybee thanks for pointing it out will update!
