### ISSUE TITLE
Function: support Lambda Function URL

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#1616]
Waiting for CDK to add support https://github.com/aws/aws-cdk/issues/19798

---
Requests:
- Sakar https://serverless-stack.slack.com/archives/C01JVDJQU2C/p1649688275488629

**Comment by AndrewBarba** [comment]
@fwang Looks like CDK support is available, any update on this?

**Comment by dkershner6** [comment]
This is implemented, can be closed.

**Comment by fwang** [comment]
Released in v1.0.4
