### ISSUE TITLE
Question: Supported RDS Databases (and versions) List

### ISSUE THREAD

**Issue by brifiction** [serverless-stack/serverless-stack#1654]
Hello SST Community! I have a question about support for more database servers and versions:

Do we know if `mysql8.x` or microsoft sql server or more are supported (besides the mentioned three below code block)? 
 
If so, is there a list of databases and its versions somewhere to refer to? Similar to how we look up `docker` images & its versions available - see [docker php tags example](https://hub.docker.com/_/php?tab=tags&page=1).

Below documentation snippet only mentions `mysql5.6`, `mysql5.7` and `postgresql10.14`:

```
engine

Type : string

Supported engine are mysql5.6, mysql5.7, and postgresql10.14.
```

And config example of what I would like to use:

```
import { RDS } from "@serverless-stack/resources";

new RDS(this, "Database", {
  engine: "mysql8.x",
  defaultDatabaseName: "awesomecompany_mysql8",
});
```

The main reason why I ask this question, it's because AWS CDK and AWS-related online documentation have not been very helpful in querying and looking for answers. 

Any kind of help that can point me into the right direction is much appreciated always 😃

**Comment by karmux** [comment]
It's limited by https://github.com/aws/aws-cdk/issues/20197.

**Comment by brifiction** [comment]
Thanks @karmux . I checked out the thread link you've shared, and participated in the `+1` vote, as suggested by `skinny85` on that thread.

![image](https://user-images.githubusercontent.com/9148451/170391845-6e8c6147-9c9c-469f-a847-c92b51c5505b.png)

Cheers, I'll close this issue at this time. Once `aws-cdk` above has traction, we'll watch for your upcoming SST change logs 👍
