### ISSUE TITLE
Api: route function authorization not applied

### ISSUE THREAD

**Issue by hans-m-song** [serverless-stack/serverless-stack#1659]
Per-route function authorization settings do not seem to be respected.

Refer to this [slack thread](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1650938206160669) for more details (let me know if you want me to repost them here).

After inserting this line [here](https://github.com/serverless-stack/serverless-stack/blob/v0/packages/resources/src/Api.ts#L651):

```typescript
console.log({ routeProps, authorizationType, authorizer: !!authorizer, authorizationScopes })
```

An api with a custom authorizer set as default would yield an output like:

```
{
  routeProps: {
    function: {
      handler: 'src/handlers/receivers/generic.handler',
      authorizationType: 'NONE'
    }
  },
  authorizationType: 'CUSTOM',
  authorizer: true,
  authorizationScopes: undefined
}
```

Which leads me to believe [this snippet](https://github.com/serverless-stack/serverless-stack/blob/v0/packages/resources/src/Api.ts#L623-L626) should look like this:

```typescript
const authorizationType =
  routeProps.authorizationType ||
  routeProps.function?.authorizationType ||
  this.defaultAuthorizationType ||
  ApiAuthorizationType.NONE;
```

My versions:

```
SST: 0.69.7
CDK: 2.15.0
```

(I know... still on v0...)

**Comment by hans-song-fctg** [comment]
Just discovered that this seems to cause it to be properly recognised and works as expected (without any changes)

```typescript
new sst.Api(this, "Api", {
  defaultAuthorizationType: sst.ApiAuthorizationType.CUSTOM,
  defaultAuthorizer: new HttpLambdaAuthorizer(...),
  "GET /private": {
    function: {
      handler: "src/handlers/receivers/generic.handler"
    },
  },
  "GET /public": {
    function: {
      handler: "src/handlers/receivers/generic.handler"
    },
    authorizationType: sst.ApiAuthorizationType.NONE
  }
}
```
