### ISSUE TITLE
[improvements] `sst remove` to use id specified in the code

### ISSUE THREAD

**Issue by justindra** [serverless-stack/serverless-stack#166]
Currently when I run `sst remove [stackName]`, that `stackName` needs to be the actual name in Cloudformation.

It would be great if we can set the `stackName` to what we define in the code itself. So for the example below, we should be able to just use `my-stack`, instead of `dev-service-name-my-stack`.

```ts
new MyStack(app, 'my-stack');
```

**Comment by fwang** [comment]
@justindra Agreed. Assigning it to me.

**Comment by krivachy** [comment]
Hey @fwang is this something I can help out with? I'd really like to see this improved as right now it's a bit of pain to do any local commands. For example we have a stack that only applies DB migrations and I'd like to add an `npm remove:migrations` that maps to `sst remove migrations-stack`, but right now it's quite hard/impossible as it depends on the stage!

For the implementation: is it ok if I change the implementation to match deploy's implementation?
For tests: where can I find an example test for CLIs?

**Comment by fwang** [comment]
Hey @krivachy That'd be great!

I think deploy also expects the full stack name, ie. `sst deploy migrations-stack` won't work. Is that what you are seeing as well?

If you look at how we are removing the debug stack on `sst remove`, we just need to prefix the stack name that we get from the cli the same way - https://github.com/serverless-stack/serverless-stack/blob/master/packages/cli/scripts/remove.js#L16

I think we don't need to support both format ie. `dev-my-app-migrations-stack` and `migration-stack`, just supporting the shorthand format makes sense.

**Comment by fwang** [comment]
Added support for this in v0.10.11. Both of these work:
```
sst remove dev-service-name-my-stack
sst remove my-stack
```

Similarly for deploy:
```
sst deploy dev-service-name-my-stack
sst deploy my-stack
```
