### ISSUE TITLE
Allow API custom domain name to be token

### ISSUE THREAD

**Issue by adikari** [serverless-stack/serverless-stack#1662]
Following is the example from the v1 documentation:

```
new Api(stack, "Api", {
  customDomain: {
    isExternalDomain: true,
    domainName: "api.domain.com",
    cdk: {
      certificate: Certificate.fromCertificateArn(this, "MyCert", certArn),
    },
  },
});
```

I would like to populate the custom domain name from a stack import value or any CDK Token.  However, when I pass the token value, I am getting this error.

```
Error: The domain name needs to be in lowercase
```

Expected: 

I would like to populate `domainName` value using cloudformation output from another stack.

```
domainName: Fn.importValue(`${scope.stage}-custom-domain-WildcardCertificateArn`); 
```

**Comment by fwang** [comment]
Hey @adikari, this is fixed in [1.2.20](https://github.com/serverless-stack/serverless-stack/releases/tag/v1.2.20).
