### ISSUE TITLE
sst-env does not update during development

### ISSUE THREAD

**Issue by justindra** [serverless-stack/serverless-stack#1667]
When using the `StaticSite` construct and `sst-env` to pass through ENV Variables, it works great on initial deployment, but not afterwards.

Steps:
* `sst start`
* `sst-env -- expo start`
* env var works great here :)
* Add a new env variable into stack
* sst recognizes that there is a new change, `Hit Enter to deploy`
* Hit Enter and wait until deployment finishes
* Close running react-app
* `sst-env -- expo start`
* The new env variable is not added in.

It looks like that `.build/static-site-environment-output-values.json` is not updated on the last deployment. But `.build/static-site-environment-output-keys.json` is updated with the new key in there.

**Comment by Manitej66** [comment]
You need to restart the `sst start` command as well to reflect changes.

**Comment by justindra** [comment]
@Manitej66 yes. But it would be nicer if we don't have to re-run that.

**Comment by fwang** [comment]
@justindra this would require `sst-env` to kill and restart the `export start` process. Does that make sense?

Curious to hear what @thdxr and @jayair think.

**Comment by justindra** [comment]
So I don't think `sst-env` would need to do that. As I am happy to re-run that. The issue is currently, we need to re-run both `sst start` as well as `sst-env -- expo start`. And since `sst start` also runs the build for the mobile/static site, that build is being run twice, just to get a new ENV var. 

Ideally I just need to re-run `sst-env -- expo start` and then it works. And `sst start` is still running in the background as per usual for both the console and the live lambda env.

**Comment by fwang** [comment]
Alright, added this in v1.2.20.

The `.build/static-site-environment-output-values.json` file nows get updated with the new values from redeploys.
