### ISSUE TITLE
Stage from environment variable

### ISSUE THREAD

**Issue by kamsar** [serverless-stack/serverless-stack#1668]
I've got a stage name in an environment variable that I'd like to push into SST, similar to setting `AWS_ACCESS_KEY_ID`.

Currently `--stage` accepts explicit values or falls back to `.sst/stage` - would it be desirable to allow overriding the parameter with an environment variable as well? (something like `SST_STAGE`?)

If this sounds good I'd be happy to work on a PR.

**Comment by fwang** [comment]
Hey @kamsar, does this work for you `sst start  --stage $SST_STAGE`?

**Comment by kamsar** [comment]
I was going to say no, as we have a mix of Mac and Windows devs (`$SST_STAGE` syntax wouldn't work on Windows), but I realized that `cross-env-shell` also normalizes this syntax not just setting an env before starting a process.

With [cross-env](https://www.npmjs.com/package/cross-env) I can use:

```
cross-env-shell sst start --stage $SST_STAGE
```

And it works as-is.
