### ISSUE TITLE
Add support for bundlers other than esbuild

### ISSUE THREAD

**Issue by KinnersleyM** [serverless-stack/serverless-stack#168]
Currently esbuild is used to bundle lambda functions. This works great for most cases however in some more advanced cases, more customisation would be appreciated.

My use case is for using TypeGraphQL in a lambda function. Whilst esbuild does have TypeScript support, it has it's [limitations](https://esbuild.github.io/content-types/#typescript-caveats). Most notably for my case, it does not support the [`emitDecoratorMetadata`](https://www.typescriptlang.org/tsconfig#emitDecoratorMetadata) option in `tsconfig.json`. 

I'm not sure what the best approach here would be but a couple come to mind.

- Allow for a custom build script.
  - I believe the AWS CDK allows for custom docker images but they are slow. If we could define a series of steps in a `build.ts` or something similar then that would allow for some really cool customisation. For instance, TypeGraphQL has a `buildSchema` function which builds a GraphQL schema from TypeScript Classes and Decorators. Doing this at build time would prevent it happening on every cold start.
- An option to specify bundler e.g. `webpack`, `gulp` etc.

I'm happy to contribute to this.

**Comment by fwang** [comment]
Hey @KinnersleyM thanks for the details! I'm leaning towards option 1. @jayair what do u think?

As a side note for `buildSchema`, is it something that can be run before or after sst build, or does it have to be run as part of the build step?

**Comment by KinnersleyM** [comment]
> As a side note for buildSchema, is it something that can be run before or after sst build, or does it have to be run as part of the build step?

Typically, I think it happens at runtime but I could be wrong, I have only just started using it. I think the process is something like this:

1. Code is bundled with `webpack` or `tsc`
2. Code runs on server
3. GraphQL server provider (Apollo in my case) takes a schema option.
4. `buildSchema` is passed to apollo server which transforms JavaScript classes (including the transpiled decorators) into a graphql schema.

Again I could be wrong as it seems like an oversight to not have a way of doing this at build time (or reasons I'm not thinking of).
Here is some example code from my project which uses TypeGraphQL with Apollo Server Lambda:
```ts
import "reflect-metadata";
import { ApolloServer, Config } from "apollo-server-lambda";
import { BuildSchemaOptions, buildSchemaSync } from "type-graphql";
import { UserResolver } from "./resolvers";
import { GraphQLSchema } from "graphql";
import DynamoTable from "./data";

const schemaOptions: BuildSchemaOptions = { resolvers: [UserResolver] };
const schema: GraphQLSchema = buildSchemaSync(schemaOptions);

const serverConfig: Config = {
  schema,
  dataSources: () => ({
    dynamoTable: new DynamoTable(),
  }),
  introspection: true,
  playground: {
    endpoint: "/dev/graphql",
  },
};

const server = new ApolloServer({
  schema,
  ...serverConfig,
});

// Apollo Server Lambda package does not currently support async handlers so callback version must be used.
export const graphqlHandler = server.createHandler({
  cors: {
    origin: "*",
    credentials: true,
  },
});
```

**Comment by KinnersleyM** [comment]
I have recently found [this esbuild plugin](https://github.com/thomaschaaf/esbuild-plugin-tsc) that allows you to use `tsc` for bundling some typescript files with decorators. If we could specify plugin usage for esbuild that would be awesome.
