### ISSUE TITLE
The engine mode serverless you requested is currently unavailable

### ISSUE THREAD

**Issue by karmux** [serverless-stack/serverless-stack#1701]
This stack code

```
    new RDS(stack, "RDS", {
        cdk: {
            cluster: {
                clusterIdentifier: "myservice",
            },
        },
        defaultDatabaseName:  "myservice",
        engine: "postgresql10.14",
    });
```

gives

```
arn-aws-iam--123456789012-root-myapp-MyServiceStack | CREATE_FAILED | AWS::RDS::DBCluster | RDSCluster073E86B4 | The engine mode serverless you requested is currently unavailable. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: d843bf6c-de9d-4a6e-bdc7-57faa1d84a29; Proxy: null)
```

when I start or deploy.

**Comment by karmux** [comment]
Fixed it by changing `region` in `sst.json`. My previous region was also available for Aurora PostgreSQL according to [Amazon Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.RegionsAndAvailabilityZones.html).

**Comment by lucashm** [comment]
I'm still having this issue, which region did you use to fix it? @karmux 

It would be cool to support newer versions as well...

**Comment by karmux** [comment]
> 

I chose eu-central-1.
