### ISSUE TITLE
Cross-region deployment hangs at creating EdgeLambdaBucket

### ISSUE THREAD

**Issue by stefanullinger** [serverless-stack/serverless-stack#1759]
Hi,

coming from https://github.com/serverless-stack/serverless-stack/issues/1736 deploying to eu-central-1 using v1.2.11 starts fine now, but does not finish completely.
Unfortunately, the stack is waiting for the `EdgeLambdaBucket` to be created, but this never finishes.

Can someone explain what this type `Custom::SSTEdgeLambdaBucket` is? I can not find any reference in the code. How does it work? What is created here?
https://github.com/serverless-stack/serverless-stack/blob/6c94940d2548426f32503dea338d891f02d6676a/packages/resources/src/nextjs-site/cross-region-helper.ts#L39

I was waiting for more than 30 minutes now, but it still says "CREATE_IN_PROGRESS" for `EdgeLambdaBucket` in the cloudformation console.

`npx sst deploy
Using stage: dev
Preparing your SST app
Building Next.js site frontend
info  - Checking validity of types...
info  - Creating an optimized production build...
info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/3)
info  - Generating static pages (3/3)
info  - Finalizing page optimization...

Page                                       Size     First Load JS
┌ ○ /                                      418 B          75.4 kB
├   /_app                                  0 B            74.9 kB
├ ○ /404                                   193 B          75.1 kB
├ λ /api/count                             0 B            74.9 kB
└ λ /api/hello                             0 B            74.9 kB
+ First Load JS shared by all              74.9 kB
  ├ chunks/framework-1f10003e17636e37.js   45 kB
  ├ chunks/main-fc7d2f0e2098927e.js        28.7 kB
  ├ chunks/pages/_app-43ac001d99fedbd3.js  493 B
  ├ chunks/webpack-69bfa6990bb9e155.js     769 B
  └ css/af0ab7b04913654a.css               266 B

λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)

Deploying stacks
Checking deploy status...
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFormation::Stack | dev-foresight-MyStack | User Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFront::CachePolicy | SiteStaticsCache29AFAE7C
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | EdgeLambdaBucketProviderServiceRoleB21F58C0
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::DynamoDB::Table | CounterTable4A83EFB3
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFront::CachePolicy | SiteImageCache3A336C80
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | SiteS3HandlerServiceRoleC6C74D2E
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | LambdaCodeReplacerProviderServiceRole89EC96F4
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | EdgeLambdaProviderServiceRoleDABCB773
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFront::CachePolicy | SiteLambdaCacheD9743183
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::S3::Bucket | SiteS3Bucket43E5BB2F
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | SiteCloudFrontInvalidatorServiceRoleDDAB0C91
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFront::OriginRequestPolicy | SiteImageOriginRequestFA9A64F5
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | SiteEdgeLambdaRole462A26EE
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::LayerVersion | SiteAwsCliLayerAA2A8F93
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | SiteS3UploaderServiceRole44D5D155
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | EdgeLambdaVersionProviderServiceRole2CCF7CE4
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::DynamoDB::Table | CounterTable4A83EFB3 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | SiteS3HandlerServiceRoleC6C74D2E | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | LambdaCodeReplacerProviderServiceRole89EC96F4 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | EdgeLambdaProviderServiceRoleDABCB773 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | EdgeLambdaBucketProviderServiceRoleB21F58C0 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | SiteS3UploaderServiceRole44D5D155 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | SiteCloudFrontInvalidatorServiceRoleDDAB0C91 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | SiteEdgeLambdaRole462A26EE | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::S3::Bucket | SiteS3Bucket43E5BB2F | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | EdgeLambdaVersionProviderServiceRole2CCF7CE4 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFront::OriginRequestPolicy | SiteImageOriginRequestFA9A64F5 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::CloudFront::OriginRequestPolicy | SiteImageOriginRequestFA9A64F5
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFront::CachePolicy | SiteStaticsCache29AFAE7C | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::CloudFront::CachePolicy | SiteStaticsCache29AFAE7C
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::LayerVersion | SiteAwsCliLayerAA2A8F93 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::LayerVersion | SiteAwsCliLayerAA2A8F93
Checking deploy status...
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Role | SiteCloudFrontInvalidatorServiceRoleDDAB0C91
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Role | LambdaCodeReplacerProviderServiceRole89EC96F4
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Role | CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Role | EdgeLambdaBucketProviderServiceRoleB21F58C0
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Role | SiteS3HandlerServiceRoleC6C74D2E
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Role | SiteS3UploaderServiceRole44D5D155
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Role | SiteEdgeLambdaRole462A26EE
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFront::CachePolicy | SiteLambdaCacheD9743183 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Role | EdgeLambdaProviderServiceRoleDABCB773
dev-foresight-MyStack | CREATE_COMPLETE | AWS::CloudFront::CachePolicy | SiteLambdaCacheD9743183
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Role | EdgeLambdaVersionProviderServiceRole2CCF7CE4
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFront::CachePolicy | SiteImageCache3A336C80 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::CloudFront::CachePolicy | SiteImageCache3A336C80
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | LambdaCodeReplacerProviderServiceRoleDefaultPolicyF7C11370
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | EdgeLambdaBucketProviderServiceRoleDefaultPolicyA855DE0C
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | SiteCloudFrontInvalidatorServiceRoleDefaultPolicyE1A60DB3
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | EdgeLambdaVersionProviderServiceRoleDefaultPolicy70F41469
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | EdgeLambdaProviderServiceRoleDefaultPolicy0CCD7673
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | EdgeLambdaBucketProviderServiceRoleDefaultPolicyA855DE0C | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | SiteCloudFrontInvalidatorServiceRoleDefaultPolicyE1A60DB3 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | LambdaCodeReplacerProviderServiceRoleDefaultPolicyF7C11370 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::S3::Bucket | SiteS3Bucket43E5BB2F
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | EdgeLambdaVersionProviderServiceRoleDefaultPolicy70F41469 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | EdgeLambdaProviderServiceRoleDefaultPolicy0CCD7673 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::SQS::Queue | SiteRegenerationQueue946B71BD
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | SiteS3UploaderServiceRoleDefaultPolicyB8D2BE10
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | SiteS3UploaderServiceRoleDefaultPolicyB8D2BE10 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::SQS::Queue | SiteRegenerationQueue946B71BD | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::DynamoDB::Table | CounterTable4A83EFB3
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::Function | CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Policy | EdgeLambdaBucketProviderServiceRoleDefaultPolicyA855DE0C
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Policy | SiteCloudFrontInvalidatorServiceRoleDefaultPolicyE1A60DB3
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Policy | LambdaCodeReplacerProviderServiceRoleDefaultPolicyF7C11370
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Policy | EdgeLambdaVersionProviderServiceRoleDefaultPolicy70F41469
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Policy | EdgeLambdaProviderServiceRoleDefaultPolicy0CCD7673
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | EdgeLambdaBucketProviderCBE2EFD7
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | SiteCloudFrontInvalidatorA6E15674
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | LambdaCodeReplacerProvider8234F5E4
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Policy | SiteS3UploaderServiceRoleDefaultPolicyB8D2BE10
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | EdgeLambdaVersionProviderC834A935
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | EdgeLambdaProviderA390C7CF
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | EdgeLambdaBucketProviderCBE2EFD7 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | EdgeLambdaVersionProviderC834A935 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | EdgeLambdaProviderA390C7CF | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | SiteS3UploaderFFD523E8
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | SiteCloudFrontInvalidatorA6E15674 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | LambdaCodeReplacerProvider8234F5E4 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | SiteS3UploaderFFD523E8 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::Function | EdgeLambdaVersionProviderC834A935
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::Function | EdgeLambdaBucketProviderCBE2EFD7
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::Function | EdgeLambdaProviderA390C7CF
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::Function | SiteCloudFrontInvalidatorA6E15674
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::SSTEdgeLambdaBucket | EdgeLambdaBucket
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::Function | LambdaCodeReplacerProvider8234F5E4
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::Function | SiteS3UploaderFFD523E8
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::SSTLambdaCodeUpdater | SiteMainLambdaCodeReplacer67B07E50
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::SSTLambdaCodeUpdater | SiteRegenerationLambdaCodeReplacerFCE81B07
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::SSTLambdaCodeUpdater | SiteApiLambdaCodeReplacerE085652A
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | SiteS3HandlerServiceRoleDefaultPolicy11A86135
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | SiteS3HandlerServiceRoleDefaultPolicy11A86135 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::SSTLambdaCodeUpdater | SiteMainLambdaCodeReplacer67B07E50 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | Custom::SSTLambdaCodeUpdater | SiteMainLambdaCodeReplacer67B07E50
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::SSTLambdaCodeUpdater | SiteRegenerationLambdaCodeReplacerFCE81B07 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | Custom::SSTLambdaCodeUpdater | SiteRegenerationLambdaCodeReplacerFCE81B07
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::SSTLambdaCodeUpdater | SiteApiLambdaCodeReplacerE085652A | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | Custom::SSTLambdaCodeUpdater | SiteApiLambdaCodeReplacerE085652A
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | SiteRegenerationFunctionServiceRole00933BB6
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Role | SiteRegenerationFunctionServiceRole00933BB6 | Resource creation Initiated
Checking deploy status...
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Policy | SiteS3HandlerServiceRoleDefaultPolicy11A86135
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | SiteS3Handler5F76C26E
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Role | SiteRegenerationFunctionServiceRole00933BB6
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | SiteS3Handler5F76C26E | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::Function | SiteS3Handler5F76C26E
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::SSTBucketDeployment | SiteS3Deployment00C6B5D8
Checking deploy status...
dev-foresight-MyStack | CREATE_COMPLETE | AWS::SQS::Queue | SiteRegenerationQueue946B71BD
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | SiteRegenerationFunctionServiceRoleDefaultPolicy7892BFA2
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::SSTBucketDeployment | SiteS3Deployment00C6B5D8 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | Custom::SSTBucketDeployment | SiteS3Deployment00C6B5D8
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | SiteRegenerationFunctionServiceRoleDefaultPolicy7892BFA2 | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFront::CloudFrontOriginAccessIdentity | SiteDistributionOrigin1S3Origin76FD4338
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::CloudFront::CloudFrontOriginAccessIdentity | SiteDistributionOrigin1S3Origin76FD4338 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::CloudFront::CloudFrontOriginAccessIdentity | SiteDistributionOrigin1S3Origin76FD4338
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::S3::BucketPolicy | SiteS3BucketPolicy5FFCCBA0
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::S3::BucketPolicy | SiteS3BucketPolicy5FFCCBA0 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::S3::BucketPolicy | SiteS3BucketPolicy5FFCCBA0
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::S3AutoDeleteObjects | SiteS3BucketAutoDeleteObjectsCustomResource51C4527F
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Policy | SiteRegenerationFunctionServiceRoleDefaultPolicy7892BFA2
dev-foresight-MyStack | CREATE_IN_PROGRESS | Custom::S3AutoDeleteObjects | SiteS3BucketAutoDeleteObjectsCustomResource51C4527F | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | Custom::S3AutoDeleteObjects | SiteS3BucketAutoDeleteObjectsCustomResource51C4527F
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | SiteRegenerationFunction999203A6
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::Function | SiteRegenerationFunction999203A6 | Resource creation Initiated
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::Function | SiteRegenerationFunction999203A6
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | SiteEdgeLambdaRoleDefaultPolicyC118405A
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::EventSourceMapping | SiteRegenerationFunctionSqsEventSourcedevforesightMyStackSiteRegenerationQueue95E0500AD37C8762
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::IAM::Policy | SiteEdgeLambdaRoleDefaultPolicyC118405A | Resource creation Initiated
dev-foresight-MyStack | CREATE_IN_PROGRESS | AWS::Lambda::EventSourceMapping | SiteRegenerationFunctionSqsEventSourcedevforesightMyStackSiteRegenerationQueue95E0500AD37C8762 | Resource creation Initiated
Checking deploy status...
Checking deploy status...
dev-foresight-MyStack | CREATE_COMPLETE | AWS::IAM::Policy | SiteEdgeLambdaRoleDefaultPolicyC118405A
dev-foresight-MyStack | CREATE_COMPLETE | AWS::Lambda::EventSourceMapping | SiteRegenerationFunctionSqsEventSourcedevforesightMyStackSiteRegenerationQueue95E0500AD37C8762
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...
Checking deploy status...`

Thanks in advance!
Stefan

**Comment by stefanullinger** [comment]
So, after an hour, CloudFormation started a rollback:

> 2022-05-29 14:12:19 UTC+0200
> EdgeLambdaBucket
> CREATE_FAILED
> 
> CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [33ad6237-4e45-4b3e-b2a7-0e399412fd1b]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

**Comment by nevolgograd** [comment]
bump to this issue

**Comment by fwang** [comment]
Sees related to #1775. We are looking into it.

**Comment by stefanullinger** [comment]
Indeed, this looks very similar! Sorry, I was checking the existing issues before adding mine, but totally missed that one.

I will close this issue now, and hope we find a fix for #1775 soon!
Thanks in advance!

**Comment by fwang** [comment]
No worries! Leaving a note here that @thdxr shared a snapshot build with the fix in #1775. Let us know if it fixes the issue and we will release it.
