### ISSUE TITLE
Monorepo example link broken

### ISSUE THREAD

**Issue by thetoxicavenger** [serverless-stack/serverless-stack#1761]
On https://docs.serverless-stack.com/advanced/monorepo-project-structure, the [monorepo starter repo](https://docs.serverless-stack.com/advanced/monorepo-project-structure) returns 404.

**Comment by fwang** [comment]
@thetoxicavenger thanks for pointing it out. We temporarily commented out the chapter, as we are putting together a new full-stack monorepo starter - https://github.com/serverless-stack/serverless-stack/tree/master/examples/ideal-stack

We are calling it the Ideal Stack, and we will be adding more docs/learning resources around it in the coming weeks.

**Comment by thetoxicavenger** [comment]
@fwang TYSM!
