### ISSUE TITLE
NextjsSite hangs on deploy (ESM issue I think)

### ISSUE THREAD

**Issue by revmischa** [serverless-stack/serverless-stack#1775]
I have a new [frontend stack](https://github.com/jetbridge/sst-prisma/blob/master/stacks/frontend.ts) using NextjsSite

When I try to deploy it - it just hangs forever. No error message. EdgeLambdaBucket custom resource appears to be the problem. It takes hours to time out.

Using latest SST.

Slack thread: https://serverless-stack.slack.com/archives/C01JG3B20RY/p1654126838160149

![image](https://user-images.githubusercontent.com/245131/171674405-2ed83058-2293-412a-ba48-13024680796e.png)

![image](https://user-images.githubusercontent.com/245131/171674420-c7745052-cfc8-4bab-b358-e9d2b0c8ad6a.png)

**Comment by revmischa** [comment]
i didn't find a match for the physical ID in CW but I found /aws/lambda/mish-myapp-frontend-EdgeLambdaBucketProviderCBE2EF-n5Au2yqOFDIN

which has the error:
```json
    "errorMessage": "Must use import to load ES Module: /var/task/s3-bucket.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/s3-bucket.js from /var/runtime/UserFunction.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename s3-bucket.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/package.json.\n",
    "code": "ERR_REQUIRE_ESM",
    "stack": [
        "Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/s3-bucket.js",
        "require() of ES modules is not supported.",
        "require() of /var/task/s3-bucket.js from /var/runtime/UserFunction.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.",
        "Instead rename s3-bucket.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/package.json.",
        "",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)"
    ]
}

```

```
2022-06-02T05:36:47.654Z undefined ERROR Uncaught Exception {"errorType":"Error","errorMessage":"Must use import to load ES Module: /var/task/s3-bucket.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/s3-bucket.js from /var/runtime/UserFunction.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename s3-bucket.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/package.json.\n","code":"ERR_REQUIRE_ESM","stack":["Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/s3-bucket.js","require() of ES modules is not supported.","require() of /var/task/s3-bucket.js from /var/runtime/UserFunction.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.","Instead rename s3-bucket.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/package.json.",""," at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)"," at Module.load (internal/modules/cjs/loader.js:863:32)"," at Function.Module._load (internal/modules/cjs/loader.js:708:14)"," at Module.require (internal/modules/cjs/loader.js:887:19)"," at require (internal/modules/cjs/helpers.js:74:18)"," at _tryRequire (/var/runtime/UserFunction.js:75:12)"," at _loadUserApp (/var/runtime/UserFunction.js:95:12)"," at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)"," at Object.<anonymous> (/var/runtime/index.js:43:30)"," at Module._compile (internal/modules/cjs/loader.js:999:30)"]}	
```

**Comment by stefanullinger** [comment]
Hey @thdxr & @fwang, I am sorry, but how can I install this snapshot build?

**Comment by revmischa** [comment]
> Hey @thdxr & @fwang, I am sorry, but how can I install this snapshot build?

Try setting the version in package.json or doing `yarn sst update 0.0.0-20220608144900`

**Comment by stefanullinger** [comment]
Hey, thanks - I was now able to install this version and in the Lambda console I can see the code is correct now (no require in there). But the CloudWatch logs still show the same error message:

`/aws/lambda/prod-foresight-MyStack-EdgeLambdaBucketProviderCBE-M76PApgY08Di

2022-06-09T06:25:41.163Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Error",
    "errorMessage": "Must use import to load ES Module: /var/task/s3-bucket.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/s3-bucket.js from /var/runtime/UserFunction.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename s3-bucket.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/package.json.\n",
    "code": "ERR_REQUIRE_ESM",
    "stack": [
        "Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/s3-bucket.js",
        "require() of ES modules is not supported.",
        "require() of /var/task/s3-bucket.js from /var/runtime/UserFunction.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.",
        "Instead rename s3-bucket.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/package.json.",
        "",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)"
    ]
}
`


I saw there is a similar issue in other projects: https://github.com/dherault/serverless-offline/issues/1014#issuecomment-810440099 ... which also mentions this post on StackOverflow: https://stackoverflow.com/questions/66676555/nodejs-14-x-native-aws-lambda-import-export-support/66688901#66688901

As all the Lambda functions seem to be using the nodejs12.x runtime, would it be possible to update it, to use the nodejs14.x or 16.x runtime?

**Comment by fwang** [comment]
Hey @stefanullinger, can you give [1.2.20](https://github.com/serverless-stack/serverless-stack/releases/tag/v1.2.20) a try?

**Comment by stefanullinger** [comment]
Hey @fwang, awesome - just tried it and it works smoothly!🥳
I saw you've changed the runtime to nodejs 16.x - is this the only change that was necessary?

Thanks a lot to all people involved! 👏

**Comment by remotealex** [comment]
I'm still getting the same error on a fresh deploy. My lambdas still look like they're on `12.x`. Am I looking at the right ones? 🤔

**Comment by stefanullinger** [comment]
Yeah! ... Updating was easy using the command @revmischa provided. I used `npx sst update 1.2.20`... I am so happy now guys! 👏

**Comment by revmischa** [comment]
I updated to latest sst using `npx sst update` - 
```
➜  sst-prisma git:(master) pnpm ls @serverless-stack/cli                  <aws:tombo-dev>
Legend: production dependency, optional only, dev only

myapp@0.1.0 /Users/cyber/dev/sst-prisma

dependencies:
@serverless-stack/cli 1.2.11
➜  sst-prisma git:(master) pnpm ls @serverless-stack/resources            <aws:tombo-dev>
Legend: production dependency, optional only, dev only

myapp@0.1.0 /Users/cyber/dev/sst-prisma

dependencies:
@serverless-stack/resources 1.2.11
```

I still see nodejs12.x being used as the runtime for the resource

```json
  "EdgeLambdaBucketProviderCBE2EFD7": {
   "Type": "AWS::Lambda::Function",
   "Properties": {
    "Code": {
     "S3Bucket": "cdk-hnb659fds-assets-887085912587-us-west-2",
     "S3Key": "d886ca7d58b9c9a3581bf3f70b2b1c145f2bf9e4aece62ba8dddce71bb4a523b.zip"
    },
    "Role": {
     "Fn::GetAtt": [
      "EdgeLambdaBucketProviderServiceRoleB21F58C0",
      "Arn"
     ]
    },
    "Handler": "s3-bucket.handler",
    "MemorySize": 1024,
    "Runtime": "nodejs12.x",  //  <-----
```

**Comment by revmischa** [comment]
Working for me now, thanks!
