### ISSUE TITLE
Error on SST Console with starter code

### ISSUE THREAD

**Issue by abmohan** [serverless-stack/serverless-stack#1777]
The TypeScript starter repo's `lambda.ts` file has a line that reads `Hello, World! Your request was received at ${event.requestContext.time}.`. 

This produces the following error when invoked through the SST Console

<img width="1215" alt="Screen Shot 2022-06-03 at 11 38 24" src="https://user-images.githubusercontent.com/585648/171926135-7a42432e-20d1-4331-956f-a31d09ed4228.png">

Removing `${event.requestContext.time}` fixes the error. Thought I'd flag that here, as it might be the first experience many folks have with the tool.

**Comment by fwang** [comment]
Hey @abmohan, I'm not able to reproduce this. `event.requestContext` should always be defined when invoked from an API Gateway HTTP API.

Was there any changes made to the starter?

**Comment by Manitej66** [comment]
Hey @abmohan did you invoked the lambda from the **functions** tab or **API** tab? if you use **functions** tab it'll throw you an error for `event.requestContext`.

**Comment by abmohan** [comment]
@Manitej66 that makes sense! 🤦  I used the functions tab.
