### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by abmohan** [serverless-stack/serverless-stack#1778]
In the second code snippet on https://docs.serverless-stack.com/constructs/Auth#sharing-auth-across-stacks, you have:

`import { Api, Stack } from "@serverless-stack/resources";` on line 1, whereas line 4 reads `export function ApiStack(ctx: StackContext) {`. 

It looks like the import on line 1 should have been `StackContext` instead of `Stack`.

**Comment by fwang** [comment]
Nice catch @abmohan! Updated.
