### ISSUE TITLE
feature-request: Set profiles/regions between stacks

### ISSUE THREAD

**Issue by justindra** [serverless-stack/serverless-stack#2]
It would be great to set specific Region or profile for particular nested stacks. 

Use Case:

Cloudfront Requires the SSL Certificate be hosted in the `us-east-1` region. Most people would be hosting everything else in other regions.

**Comment by jayair** [comment]
Ah do you have a simple repo or some sample code that I can try this out? I'll have a look.

**Comment by justindra** [comment]
@jayair Here is what I ended up doing for my project. I can separate it out in a different repo if that would make it easier for you.
https://github.com/justindra/townhub/tree/master/infrastructure/ssl

As a note, after investigating it a little bit more, its actually a limitation of CloudFormation and therefore AWS CDK as well. That you can't actually perform any cross-region deployments in the same stack. I believe other tools like Terraform and Pulumi goes around this by not using CloudFormation and instead using the AWS SDKs directly. 

I do have some ideas on doing this using CustomResources and basically calling those SDKs in a Lambda function, so not sure how that would fit into a tool like the SST but keen to hear your thoughts on it too.

**Comment by jayair** [comment]
I see. Thanks for sharing the repo.

So you ended up not using Nested stacks then? And your custom deploy script does two deploys, one to `us-east-1` for the SSL?

**Comment by justindra** [comment]
Yea, so Nested stacks wasn't able to do it, as it complains saying that it needs to be in the same region for both stacks to be nested with each other. This seems like an AWS Limitation so not sure how you would get around this.

Yep, I ended up doing just a custom deploy script so one can send it to the `us-east-1` region and the other can send it to the region of your choice.

**Comment by justindra** [comment]
@jayair FYI, AWS has fixed this issue and you can now do this through the CDK.

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-certificatemanager-readme.html#cross-region-certificates

**Comment by jayair** [comment]
Thanks for following up @justindra!
