### ISSUE TITLE
Add a doc on using CDK constructs alongside SST constructs

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#204]
Currently, there is a migration guide from CDK to SST. The word **migration** can be misleading, and be interpreted as CDK constructs have to be migrated or imported into an SST app.

Having a doc showing how to use CDK constructs in SST when SST doesn’t have the construct the reader needs.

**Comment by rupertlssmith** [comment]
I had a prpoblem defining a VPC inside an sst stack:

```
export default class BuildJobStack extends sst.Stack {
  constructor(scope, id, props) {
    super(scope, id, props);
     const vpc = new ec2.Vpc(this, "eco-vpc", {
      maxAzs: 1
    });
```
Error says:

```
npx sst build
Preparing your SST app
Transpiling source
Synthesizing CDK
[Error at /dev-eco-server-build-job] You are not authorized to perform this operation.
```

Seems it has to be defined inside a cdk stack instead:

```
export default class BuildJobStack extends cdk.Stack {
  constructor(scope, id, props) {
    super(scope, id, props);
     const vpc = new ec2.Vpc(this, "eco-vpc", {
      maxAzs: 1
    });
```
