### ISSUE TITLE
Support for esbuild plugins in Function resource

### ISSUE THREAD

**Issue by KinnersleyM** [serverless-stack/serverless-stack#217]
`esbuild` supports a [plugins](https://esbuild.github.io/plugins/#using-plugins) feature that allows you to customise the build process. This would be helpful for the Function resource to allow for more customisation in the build process.

**Comment by KinnersleyM** [comment]
This should be a fairly simple one, I can have a crack at it this week, it would also allow for a specific usecase I mentioned [here](https://github.com/serverless-stack/serverless-stack/issues/168)

**Comment by KinnersleyM** [comment]
Closing as I have discovered esbuild plugins are only available in the async build version. As CDK Constructs don't have a way to run async code, it seems this feature is impossible.

**Comment by fabioDMFerreira** [comment]
@KinnersleyM were you able to use this project to compile typescript projects that use decorators?

**Comment by fwang** [comment]
Hey @fabioDMFerreira, esbuild plugins are now supported. Here's an example https://docs.serverless-stack.com/constructs/Function#configure-esbuild-plugins

**Comment by fabioDMFerreira** [comment]
You are right @fwang. I was able to compile my application following your instructions. 

I tried it once, but it didn't work because I have a monorepo with multiple tsconfig files. After pointing the correct tsconfig path it compiled correctly.
```
const { esbuildDecorators } = require("@anatine/esbuild-decorators");

module.exports = [
  esbuildDecorators({tsconfig:'services/api/tsconfig.json'}),
];

```
