### ISSUE TITLE
Custom Resource Provider can't be provisioned with SST

### ISSUE THREAD

**Issue by krivachy** [serverless-stack/serverless-stack#223]
I ran into an issue with SST and creating a custom resource provider. This seems to be SST specific as when I try this exact thing in a clean CDK stack it works, even with esbuild (can push that repo if you're interested as well).

I've created a repo to reproduce this: https://github.com/krivachy/sst-cr-provider-bug

When I do a custom resource provider in a clean SST stack:

```typescript
    const nodejsLambda = new lambda.NodejsFunction(this, 'lambda', {
        entry: 'src/lambda.ts',
    })

    const provider = new cr.Provider(
        this,
        'provider',
        {
          onEventHandler: nodejsLambda,
        }
    );
```

And then `npx sst build`, it fails with:

```text
Preparing your SST app
Detected tsconfig.json
Transpiling source
 > node_modules/@aws-cdk/aws-lambda-nodejs/lib/util.js:73:20: warning: This call to "require" will not be bundled because the argument is not a string literal (surround with a try/catch to silence this warning)
    73 │     const pkgJson = require(pkgPath); // eslint-disable-line @typescript-eslint/no-require-imports
       ╵                     ~~~~~~~

1 warning
Linting source

sst-cr-provider-bug/lib/MyStack.ts
  13:11  warning  'provider' is assigned a value but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)

Running type checker
Synthesizing CDK

Error: ENOENT: no such file or directory, stat 'sst-cr-provider-bug/.build/lib/runtime'
    at Object.statSync (fs.js:1086:3)
    at Object.fingerprint (sst-cr-provider-bug/node_modules/@aws-cdk/core/lib/fs/fingerprint.ts:30:28)
    at Function.fingerprint (sst-cr-provider-bug/node_modules/@aws-cdk/core/lib/fs/index.ts:38:12)
    at AssetStaging.calculateHash (sst-cr-provider-bug/node_modules/@aws-cdk/core/lib/asset-staging.ts:445:27)
    at AssetStaging.stageByCopying (sst-cr-provider-bug/node_modules/@aws-cdk/core/lib/asset-staging.ts:246:28)
    at stageThisAsset (sst-cr-provider-bug/node_modules/@aws-cdk/core/lib/asset-staging.ts:168:35)
    at Cache.obtain (sst-cr-provider-bug/node_modules/@aws-cdk/core/lib/private/cache.ts:24:13)
    at new AssetStaging (sst-cr-provider-bug/node_modules/@aws-cdk/core/lib/asset-staging.ts:191:44)
    at new Asset (sst-cr-provider-bug/node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:128:21)
    at AssetCode.bind (sst-cr-provider-bug/node_modules/@aws-cdk/aws-lambda/lib/code.ts:251:20)

There was an error synthesizing your app.
```

It seems like the CDK custom resource implementation is creating a set of lambda functions under the hood: [@aws-cdk/custom-resources/lib/provider-framework/provider.ts#L16](https://github.com/aws/aws-cdk/blob/v1.91.0/packages/@aws-cdk/custom-resources/lib/provider-framework/provider.ts#L16)

**Comment by krivachy** [comment]
I've been able to work around this in an extremely hacky way 😜 

By adding this to my stack to put the files it wants in the place it's looking for:
```typescript
    import * as fse from 'fs-extra';


    fse.mkdirSync('runtime');
    fse.copySync(
      path.join(
        __dirname,
        '../..',
        'node_modules/@aws-cdk/custom-resources/lib/aws-custom-resource/runtime'
      ),
      path.join(__dirname, 'runtime')
    );
```

Not ideal, but at least this issue isn't blocking me!

**Comment by krivachy** [comment]
This is even less urgent for me as I found out that I don't even need to be using `@aws-cdk/custom-resources`, but can just use a lambda directly (which solves my use-case): https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#custom-resource-providers

**Comment by fwang** [comment]
@krivachy Thanks for putting together a reproducible repo. I'm going to take a look at this soon.

**Comment by fwang** [comment]
Hey @krivachy, I had a chance to play around with the repo you shared. I was able to get it to work after adding the CDK modules the stack uses, ie.
```
    "@aws-cdk/aws-lambda-nodejs": "1.91.0",
    "@aws-cdk/custom-resources": "1.91.0"
```

Here's the PR with the changes - https://github.com/krivachy/sst-cr-provider-bug/pull/1

I didn't look further as in why this solved it. If you got any insights, be sure to keep me posted.

As a side note, you mentioned that you are now creating the custom resource using a Lambda function directly. While reading up on the different ways to create custom resources, I read that you'd need to handle errors manually when creating them this way. Might be something you want to watch out for. You can read more about it here - https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#custom-resource-providers

**Comment by fwang** [comment]
Closing for now. @krivachy please reopen if this comes up again.

**Comment by krivachy** [comment]
Thanks @fwang for looking into this and opening a pull request! Great that it's not an SST issue.

I'm aware that I need to handle errors, but that is handled quite simply with a try-catch around the whole lambda code and [`cfn-response`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html) (there are npm packages out there as well).
