### ISSUE TITLE
Auth resource - Can MFA settings be set? 

### ISSUE THREAD

**Issue by cmaycumber** [serverless-stack/serverless-stack#286]
I'm currently trying to set MFA settings to optional through my code but can't seem to do it with the current Auth resource. My current workaround is just setting it in the console. 

I think it would be nice to set this property somehow or at least default it to optional for added flexibility.

**Comment by fwang** [comment]
Hi @cmaycumber, yeah that make sense. I will put that into one of the coming releases.

**Comment by fwang** [comment]
Hey @cmaycumber, with [v0.12.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.12.0), you can do something like this:
``` js
new Auth(this, "Auth", {
  cognito: {
    userPool: {
      mfa: cognito.Mfa.REQUIRED,
    },
  },
});
```

There is a small breaking change to the Auth construct. You can read about how to upgrade here - https://docs.serverless-stack.com/constructs/Auth#upgrading-to-v0120
