### ISSUE TITLE
Fix the ApolloGraphQL example

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#289]
Link to the example: https://serverless-stack.com/examples/how-to-create-an-apollo-graphql-api-with-serverless.html

Things need to be changed:
1. Change `npm install apollo-server-lambda` to `npm install -s apollo-server-lambda graphql`
2. Add `"esModuleInterop": true,` to tsconfig.json, otherwise `sst build` fails with the error
```
node_modules/apollo-server-core/dist/ApolloServer.d.ts:7:8 - error TS1259: Module '"/Users/frank/Sites/fwang/graphql-apollo/node_modules/@types/ws/index"' can only be default-imported using the 'esModuleInterop' flag

7 import WebSocket from 'ws';
         ~~~~~~~~~

  node_modules/@types/ws/index.d.ts:291:1
    291 export = WebSocket;
        ~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


Found 1 error.
```

**Comment by jayair** [comment]
Couldn't find the need for the `graphql` package but added the `tsconfig.json` change.

https://github.com/AnomalyInnovations/serverless-stack-com/commit/57d08e4309a86460f7be3745c9bf5f525e3f9a70
