### ISSUE TITLE
Export `api.url` in all docs and examples

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#324]
As the subject suggests, update docs and examples for `Api`, `ApiGatewayV1Api`, `ApolloApi` and `AppSyncApi`:
```
this.addOutputs({
  Url: api.url
});
```

**Comment by jayair** [comment]
Also, needs to be fixed in the `create-serverless-stack` templates.

**Comment by jayair** [comment]
Fixed in the examples https://github.com/serverless-stack/examples/commit/563d36a8397d34b49a7da78558273ace96eccb0e
