### ISSUE TITLE
Add defaultFunctionProps to TopicProps

### ISSUE THREAD

**Issue by aarvay** [serverless-stack/serverless-stack#344]
Is there a reason why this is not there already? This would add the ability to configure default props for all topic subscribers. I found myself doing this for every subscriber lambda currently.

**Comment by fwang** [comment]
Hey @aarvay, that makes sense. I will put them in the next release.

**Comment by aarvay** [comment]
Thanks @fwang :)

**Comment by fwang** [comment]
It's now available in v0.14.0. An example here - https://docs.serverless-stack.com/constructs/Topic#specifying-function-props-for-all-the-subscribers
