### ISSUE TITLE
[suggestion/question] - is there a plan to move to monocdk?

### ISSUE THREAD

**Issue by floydding** [serverless-stack/serverless-stack#351]
One short coming of CDK is that you have to make sure all parts are on the same version - you also pointed it out in the official doc. as [monocdk](https://www.npmjs.com/package/monocdk) is coming along (still experimental stage but hopefully it ll be production ready soon), is there a plan to move to monocdk?

**Comment by fwang** [comment]
Hey @floydding, it's definitely on our plan. Once V2 comes out, we are planning to have CDK as a peerDependency.

I haven't played around with monocdk yet. I hope peerDependency works out fine.

**Comment by fwang** [comment]
Updated to CDK v2 in [v0.59.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.59.0). See release notes for steps to update.
