### ISSUE TITLE
Add 'stage' property to Stack construct

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#36]

**Comment by justindra** [comment]
While you are looking at this, would it be possible to add the stage into the Stack? Atm I have to pass in the stage into my custom resources as a prop. It would be nice to be able to acces it from the `Stack` itself instead of having to repetitively pass it in as a prop.

```ts
import { Stack, App, StackProps } from '@serverless-stack/resources';

export class MyStack extends Stack {
    constructor(scope: App, id: string, props?: StackProps) {
        super(scope, id, props);

        new SubStack(this, id, { stage: scope.stage }); // <-- be nice if we can just get the stage from `this`
        new CustomResource1(this, id, { stage: scope.stage });
        new CustomResource2(this, id, { stage: scope.stage });
    }
}

// vs

export class MyStack extends Stack {
    constructor(scope: App, id: string, props?: StackProps) {
        super(scope, id, props);

        new SubStack(this, id);
        new CustomResource1(this, id);
        new CustomResource2(this, id);
    }
}
```

Currently I've got my custom Stack object that does this, but might be nice to have it as part of the framework.

**Comment by fwang** [comment]
Hi @justindra, are you creating a nested stack?

**Comment by justindra** [comment]
@fwang Not at the moment, its just custom TS Classes to tidy up and make some resources more re-usable. E.g. I have a Table class that creates a DDB Table, Lambda Hooks and CFn Outputs. But possibly some nested stacks in the future too.

**Comment by fwang** [comment]
Ah I see. Sorry, I miss read your code.

If we made `stage` available in the `Stack` object, would that work for you? So inside your `SubStack`, you can do `this.stage` instead of `props.stage`.

**Comment by justindra** [comment]
Yep @fwang that would be perfect!

**Comment by fwang** [comment]
@justindra I'm working on supporting `stack.stage` in PR #240 

I'm going to change the title for this issue to this. And I opening a discussion for this instead https://github.com/serverless-stack/serverless-stack/discussions/244
