### ISSUE TITLE
Respect Permission Limitations Locally when Running in Debug Mode

### ISSUE THREAD

**Issue by simonireilly** [serverless-stack/serverless-stack#363]
When running in debug mode the ServiceRole of the lambda is not the source of the credentials. The credentials used are those of the deployer.

## Story

Given my lambda has permissions to only read from a service, then when running `npx sst start` I should not be able to write to the service.

## Details

Operating system: Ubuntu 20.04.2 LTS
Node version: v12.16.3

## Minimal Recreation

See this PR: https://github.com/simonireilly/sst-tester/pull/1

![assumed-credentials-bug-recreation](https://user-images.githubusercontent.com/30017294/118230566-c8f3c100-b485-11eb-80d7-1ae5705c9de7.gif)

**Comment by simonireilly** [comment]
This issue is recreated with the following repository: https://github.com/simonireilly/sst-tester

**Comment by fwang** [comment]
Hmm.. just tried out the repo and I'm getting the AccessDenied error.

I would try the following to dig deeper:
- in Lambda, make an aws sdk call to STS's `getCallerIdentity` or `getAccessKeyInfo` to verify the IAM credentials the sdk is using
- does the Lambda have other non-dynamodb permissions? (ie. make an aws sdk call to list out all SNS topics)

<img width="1072" alt="Screen Shot 2021-05-13 at 3 29 05 PM" src="https://user-images.githubusercontent.com/83515/118177100-3bba5900-b400-11eb-99b8-62b824f7d394.png">

<img width="1432" alt="Screen Shot 2021-05-13 at 3 29 41 PM" src="https://user-images.githubusercontent.com/83515/118177111-3d841c80-b400-11eb-9395-8c9adee06042.png">

**Comment by simonireilly** [comment]
Thanks Frank, what a great suggestion. Get caller identity did indeed show, that the caller is myself, locally:

MR here with a GIF for recreation https://github.com/simonireilly/sst-tester/pull/1


```
[1620972564267] INFO (LambdaLogger/34329 on simon-XPS-15-9500): Caller Identity
    callerIdentity: {
      "$metadata": {
        "httpStatusCode": 200,
        "requestId": "d52cdc62-b7c2-4e65-9fcd-207546f30205",
        "attempts": 1,
        "totalRetryDelay": 0
      },
      "UserId": "AIDAUWGULNAJUAPI2KCBK",
      "Account": "322567890963",
      "Arn": "arn:aws:iam::322567890963:user/simonireilly+cloudguru+user"
    }
    requestId: "fTgTCjQsjoEEMNw="
 ```

So I thought, wow, that's strange. Now, the reason for this seems to be that when `AWS_PRFOILE` is present and the `aws-sdk-js` V3 has access to that environment variable, then it will assume that local users' credentials.

So I have made a simplification and a change here to accurately recreate this:

```
delete(process.env.AWS_PROFILE)
```

Adding this at the top of the file, before constructing my aws-sdk clients ensure that the aws-sdk uses the temporary credentials provided by the framework:

```
ae630edc-a3b8-4f23-b466-44c9beff9d44 ERROR AccessDeniedException: User: arn:aws:sts::322567890963:assumed-role/dev-sst-tester-my-stack-ApiLambdaGETServiceRole210-DGWSDBZSPMWS/dev-sst-tester-my-stack-ApiLambdaGETB1714EF3-1BCWTIG1FF4WE is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:eu-west-1:322567890963:table/dev-sst-tester-Notes
    at deserializeAws_json1_0PutItemCommandError (/home/simon/code/projects/sst-tester/node_modules/@aws-sdk/client-dynamodb/protocols/Aws_json1_0.ts:3618:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /home/simon/code/projects/sst-tester/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:18
    at /home/simon/code/projects/sst-tester/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22
    at StandardRetryStrategy.retry (/home/simon/code/projects/sst-tester/node_modules/@aws-sdk/middleware-retry/src/defaultStrategy.ts:125:38)
    at /home/simon/code/projects/sst-tester/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:21:20
    at /home/simon/code/projects/sst-tester/node_modules/@aws-sdk/lib-dynamodb/src/commands/PutCommand.ts:72:20
    at handler (/home/simon/code/projects/sst-tester/src/lambda.ts:52:3)
    at processEvents (/home/simon/code/projects/sst-tester/node_modules/@serverless-stack/cli/scripts/util/bootstrap.js:86:14) {
  __type: 'com.amazon.coral.service#AccessDeniedException',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'V1TKTBTDP523T4346E4A32S4LJVV4KQNSO5AEMVJF66Q9ASUAAJG',
    attempts: 1,
    totalRetryDelay: 0
  }
}
```
