### ISSUE TITLE
Ability to tag debug resources

### ISSUE THREAD

**Issue by RichiCoder1** [serverless-stack/serverless-stack#374]
Our org is pretty strict about tagging, and I can't actually deploy the debug stack by default due to being able to tag it's resources. It'd be great to (either statically or dynamically) tag debug stack resources.

**Comment by fwang** [comment]
Hey @RichiCoder1, so the debug stack has mostly the following resources:
- 1 DynamoDB table
- 1 S3 bucket
- 1 WebSocket API with 3 Lambda functions

Can you share how you plan to tag them?

**Comment by RichiCoder1** [comment]
Basically we mandate that all resources have a few ids like "environment-id", "application-id", etc... with simple values. Two of the values vary by stage, but otherwise they're relatively static simple values.

**Comment by fwang** [comment]
Got it. Let me think about this and run something by you shortly.

Btw, are you tagging the resources in your with something like this?
```
import * as cdk from "@aws-cdk/core";

cdk.Tags.of(app).add('tagName', 'tagValue');
// or
cdk.Tags.of(apiStack).add('tagName', 'tagValue');
```

**Comment by RichiCoder1** [comment]
Yup! I actually got it to work by editing the debug stack files and adding those statements as a short term solution

**Comment by fwang** [comment]
Yup, I will try to put something together before you needing to update the SST version ;)

**Comment by fwang** [comment]
Hey @RichiCoder1, you can now tag the debug stack in [v0.26.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.26.0)

Here's an example - https://docs.serverless-stack.com/live-lambda-development#tagging-the-debug-stack

Let me know if you have any questions.

**Comment by RichiCoder1** [comment]
Thank you!!
