### ISSUE TITLE
How to mimic the commandHook properties from the NodejsFunction?

### ISSUE THREAD

**Issue by Albert-Gao** [serverless-stack/serverless-stack#383]
1st, Thanks for this awesome lib, very promising idea and works flawlessly,

I have a small problem when deploying

Basically, I want to reproduce the following logic:

```javascript
    // The code that defines your stack goes here
    new NodejsFunction(this, 'prisma', {
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'handler',
      entry: lambdaFn,
      timeout: cdk.Duration.seconds(10),
      memorySize: 1024,
      environment: {
        DB_URL: process.env.DB_URL || '',
      },
      bundling: {
        nodeModules: ['@prisma/client', 'prisma'],
        commandHooks: {
          beforeBundling(_inputDir: string, _outputDir: string) {
            return []
          },
          beforeInstall(_inputDir: string, outputDir: string) {
            return [`cp -R ../prisma ${outputDir}/`]
          },
          afterBundling(_inputDir: string, outputDir: string) {
            return [
              `cd ${outputDir}`,
              `yarn prisma generate`,
              `rm -rf node_modules/@prisma/engines`,
              `rm -rf node_modules/@prisma/client/node_modules node_modules/.bin node_modules/prisma`,
            ]
          },
        },
      },
    })
```

in this procedure, we need to generate something in the node_modules and remove some of the generated sub-folders

We do not have a `commandHooks` but a `copyFiles` in the `bundle` object, but not enough for this case, 
anyway we can mimic this? 
Or if we can skip the build step in `sst deploy`, then we can control what would be uploaded, currently, it will always rebuild the bundle.

Saw some discussion here,
https://github.com/serverless-stack/serverless-stack/pull/205

@thdxr Could you plz share how you solve the prisma-bundling problem in the end? How did define that `new sst.Api()` 
I tried many ways just not work,
Thanks :)

**Comment by fwang** [comment]
Hi @Albert-Gao, yeah I can see these command hooks being useful on `sst deploy`.

Do you need to run them for `sst start`? To add a bit of context, when running `sst start`, functions are built and run locally. The functions are not zipped up and sent to AWS Lambda. And because the functions are run locally, some of the [bundle options](https://docs.serverless-stack.com/constructs/Function#functionbundleprops) like `copyFiles` are ignored, b/c we assume the files you are going to copy exist locally, and the files only need to be copied on `sst deploy`.

So do these command hooks need to run in `sst start`?

**Comment by Albert-Gao** [comment]
No, no need to run for sst start, only for deployment, because thanks to this godlike framework, the sst start can just connect to my local db, so beautiful and elegant....

But when doing deployment, I need to assemble the proper bundle, in this case, I need that commandHook 🤝

**Comment by fwang** [comment]
Ah that makes sense. Let me put something together and run it by you.

Appreciate the kind words! That made my day :)

**Comment by Albert-Gao** [comment]
Thanks, take your time, not a blocker for me at all. Keep the awesome work! 😺 I am back to serverless solely because of your work.

**Comment by Albert-Gao** [comment]
similar issue #119

**Comment by thdxr** [comment]
@Albert-Gao sorry it took me so long to see this - gonna copy paste some code that I have and hopefully you can pick through it.  Some of this might be outdated because of updates in SST but I think it's mostly relevant

This is me creating the Prisma layer
```
  const layer_root = ".build/layer"
  const layer_node = path.join(layer_root, "nodejs")
  const to_copy = [
    "node_modules/@prisma/client",
    "node_modules/@prisma/engines/migration-engine-rhel-openssl-1.0.x",
    "node_modules/@prisma/engines/query-engine-rhel-openssl-1.0.x",
    "node_modules/@prisma/engines/package.json",
    "node_modules/@prisma/engines/dist",
    "node_modules/prisma",
    "node_modules/.prisma",
  ]
  execSync(`rm -rf ${layer_root}`)
  for (let src of to_copy) {
    const parent = path.join(src, "../")
    execSync(`mkdir -p ${layer_node}/${parent}`)
    console.log(`Copying ${src} to ${layer_node}/${parent}`)
    execSync(`cp -a ${src} ${layer_node}/${parent}`)
  }

  const to_delete = [
    "node_modules/prisma/query-engine-rhel-openssl-1.0.x",
    "node_modules/prisma/query-engine-debian-openssl-1.1.x",
    "node_modules/.prisma/query-engine-rhel-openssl-1.0.x",
    "node_modules/.prisma/query-engine-debian-openssl-1.1.x",
  ]
  for (let src of to_delete) {
    execSync(`rm -rf ${src}`)
  }

  const layer = new lambda.LayerVersion(stack, "Prisma", {
    code: lambda.Code.fromAsset(layer_root),
    compatibleRuntimes: [lambda.Runtime.NODEJS_14_X],
  })
  execSync(`rm -rf ${layer_root}`)
  return {
    layers: [layer],
    externalModules: [
      "@prisma/client",
      "prisma",
      ".prisma/client",
      "@prisma/engines",
    ],
  }

```

For when I'm using the function I make sure those modules aren't bundled
```
    bundle: {
      externalModules: props.prisma.externalModules,
    }
```

Here's an example of a custom resource to run migrations
```
export const trigger: CloudFormationCustomResourceHandler = async (
  event,
  _ctx
) => {
  if (event.RequestType === "Delete") return
  const result = execSync(
    `${process.execPath} /opt/nodejs/node_modules/prisma/build/index.js migrate deploy --preview-feature`,
    {
      env: {
        DATABASE_URL: Config.postgres.url(),
      },
    }
  )
  console.log(result.toString())
}
```

**Comment by Albert-Gao** [comment]
ah, layers, then that makes sense now.... 
by making the prisma layers, we can gain the control of building back and we do not need to ship it with every lambda, just need to reuse the layer

THANKS! @thdxr Savior!

**Comment by fwang** [comment]
Hey @Albert-Gao, sorry it took me so long to get back to this. Did @thdxr's solution work for you?

Let me know if you still need the commandHooks!

**Comment by Albert-Gao** [comment]
@fwang Hi, mate, it works! works quite well, however, my current remote database maybe far from Amazon server, so it takes nearly 2 sec to get the response, make it impossible to do any real device testing, will just use sst local dev flow for now, until I have time to setup the whole AWS Aurora Serverless with VPC with Lambda, and a proper migration setup with Prisma..... God....just hurt to even think about it...

So, put in short, might not need in the long run, since Lambda Layer will give me smaller bundle size.
but might need it for the short-term, just because I do not want to touch the giant CDK setup until the prototype is nearly finished. xD

**Comment by thdxr** [comment]
FWIW I ultimately decided to let go of Prisma. I wanted the full serverless experience and ultimately Postgres was never made for that as hard as AWS has tried with serverless Aurora. 

All in on Dynamo now

**Comment by Albert-Gao** [comment]
@thdxr making sense, for me, I need to save stock market information which makes DynamoDB too expensive to use, (BTW, found a DynamoDB price calculator https://twitter.com/albertgao/status/1401037182412808192) I was thinking about separate user data to DynamoDB for a faster lookup as a large cheaper `in-mem` DB, but just do not want to add that complexity.

If DynamoDB suits your use case, that gonna be fantastic DX, for me, I am stuck.

**Comment by fwang** [comment]
In release [v0.30.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.30.0)

**Comment by mladibejn** [comment]
Here's my setup with layer and bash script! Lemme know if I'm missing something :)

bash script to prepare prisma layer
```sh
#!/bin/bash

PRISMA_LAYER_DIR=".build/layers/prisma-client"

function prepare_prisma_client_lambda_layer() {
  echo "Cleaning up workspace ..."
  rm -rf $PRISMA_LAYER_DIR

  echo "Creating Prisma client layer ..."
  mkdir -p "${PRISMA_LAYER_DIR}"/nodejs/node_modules/.prisma
  mkdir -p "${PRISMA_LAYER_DIR}"/nodejs/node_modules/@prisma

  echo "Prepare Prisma Client lambda layer ..."
  cp -r ../../node_modules/.prisma/client "${PRISMA_LAYER_DIR}"/nodejs/node_modules/.prisma
  cp -r ../../node_modules/@prisma "${PRISMA_LAYER_DIR}"/nodejs/node_modules
}
prepare_prisma_client_lambda_layer
```

usage within the sst.Api
```js
  new sst.Api(this, `${SERVICE_NAME}Api`, {
      defaultFunctionProps: {
        srcPath: SRC_PATH,
        bundle: {
          externalModules: ['@prisma/client'],
        },
        layers: [
          new lambda.LayerVersion(this, 'PrismaClientLayer', {
            code: lambda.Code.fromAsset(`${SRC_PATH}/.build/layers/prisma-client`),
          }),
        ],
      },
      httpApi: HttpApi.fromHttpApiAttributes(this, 'Api', {
        httpApiId,
      }),
      routes: {
        [`ANY /{proxy+}`]: 'src/lambda.handler',
      },
  });
```

**Comment by pabacham** [comment]
@mladibejn I use the same approach, but if I share the API between other stacks, then the Prisma layer can not be updated during the deployment process cause the layer is used by "nested" stacks. More details in issue #549
