### ISSUE TITLE
Add an example with Mongo Atlas

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#405]
Harshit shared his code for Mongo Atlas on Slack. Let's add an example.
https://serverless-stack.slack.com/archives/C01JG3B20RY/p1622476904154300?thread_ts=1622474967.154200&cid=C01JG3B20RY

**Comment by jayair** [comment]
Added https://github.com/AnomalyInnovations/serverless-stack-com/pull/552
