### ISSUE TITLE
VSCode does not show `layers` in IntelliSense dropdown for API route definition

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#426]
`layers` shows up in `Api.defaultFunctionProps`:

![DeepinScreenshot_select-area_20210604212110](https://user-images.githubusercontent.com/83515/121308038-98f5dd00-c8ce-11eb-9b44-dda00e8c2489.png)

But, `layers` doesn't show up in route definition in `Api.routes`. Even though `layers` exists as property value.

![DeepinScreenshot_select-area_20210604211754](https://user-images.githubusercontent.com/83515/121308016-94c9bf80-c8ce-11eb-8f43-47d75a9c6ea3.png)

Does anyone have any insights on why this is happening?

**Comment by ffxsam** [comment]
This could be related:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/12532733/128543240-3d2cd928-ad4c-4caf-8bba-073131eedb19.png">

`environments` is definitely a valid property, yet VS Code's IntelliSense doesn't show it as an option.

**Comment by thdxr** [comment]
This has to do with type discrimination.  The way we use union types typescript cannot tell which of these the object is
```
sst.FunctionDefinition | sst.ApiFunctionRouteProps | sst.ApiHttpRouteProps | sst.ApiAlbRouteProps
```

There's tradeoffs to making tsc aware of this that we can discuss

**Comment by fwang** [comment]
@thdxr hmm.. given that we use union types everywhere, this makes intellisense not useable 🤔

**Comment by thdxr** [comment]
I'm going to close this for now as it this will be handled when we rethink our approach to overloading options
