### ISSUE TITLE
How do you specify the ARN of Role to use when invoking CloudFormation

### ISSUE THREAD

**Issue by rshayman** [serverless-stack/serverless-stack#428]
With CDK we could specify the ARN of Role to use when invoking CloudFormation using the  -r, --role-arn options.

**Comment by fwang** [comment]
Hey @rshayman, let me play around with the flag and expose the same flag for SST.

**Comment by rshayman** [comment]
The --no-color option appeared to be passed through so I tried supplying --role-arn option, but no joy.

**Comment by fwang** [comment]
Hey @rshayman, added the flag in v0.27.0 - https://github.com/serverless-stack/serverless-stack/releases/tag/v0.27.0
```
$ sst deploy --role-arn arn:aws:iam::112233445566:role/cdk-cf-deploy-role
```

Give it a try and let me know if it works for you!
