### ISSUE TITLE
Review doc: --increase-timeout flag

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#432]
A few things:
- [x] review doc for the cli option: https://docs.serverless-stack.com/packages/cli#options
- [x] Frank updated the [launch.json config](https://docs.serverless-stack.com/debugging-with-vscode#launch-configurations) to add the `--increase-timeout` flag. We should mention they have 15minutes to debug with breakpoints without timing out the Lambda (except for Apis)
- [x] We should also mention the behavior in the "Live Lambda Development" or the "Working Locally" chapter

**Comment by jayair** [comment]
Updated the examples and docs https://github.com/serverless-stack/serverless-stack/pull/449
