### ISSUE TITLE
The deployment of a project including multiple stacks does not fail if any if the stack deployments fail

### ISSUE THREAD

**Issue by molnarzs** [serverless-stack/serverless-stack#440]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@serverless-stack/cli@0.26.0` for the project I'm working on.

The deployment of a project including multiple stacks does not fail if any if the stack deployments fail, reporting false SUCCESS in CI.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@serverless-stack/cli/bin/scripts.js b/node_modules/@serverless-stack/cli/bin/scripts.js
index 065e687..f1799d9 100755
--- a/node_modules/@serverless-stack/cli/bin/scripts.js
+++ b/node_modules/@serverless-stack/cli/bin/scripts.js
@@ -18,6 +18,7 @@ const fs = require("fs-extra");
 const yargs = require("yargs");
 const chalk = require("chalk");
 const spawn = require("cross-spawn");
+const fp = require('lodash/fp');
 const { logger, initializeLogger } = require("@serverless-stack/core");
 
 const packageJson = require("../package.json");
@@ -353,7 +354,17 @@ switch (script) {
 
     // Prepare app
     prepareCdk(argv, cliInfo, config)
-      .then(() => internals[script](argv, config, cliInfo))
+      .then(() => {
+      const res = internals[script](argv, config, cliInfo);
+       res.then(
+         fp.flow(
+           fp.map('status'),
+           fp.indexOf('failed'),
+           fp.tap(found => process.exit(found >= 0))
+         )
+       );
+       return res;
+      })
       .catch((e) => exitWithMessage(e.message));
 
     break;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by fwang** [comment]
Hey @molnarzs, when 1 or more stacks fail to deploy, the deploy script will throw an error:
https://github.com/serverless-stack/serverless-stack/blob/master/packages/cli/scripts/deploy.js#L38-L40

And the command will exit with error code 1:
https://github.com/serverless-stack/serverless-stack/blob/master/packages/cli/bin/scripts.js#L357

Is the command exiting with error code 0 in your CI?

**Comment by thdxr** [comment]
Hey @molnarzs are you still seeing this problem? I'm going to close the issue for now - let us know if you'd like to reopen it.
