### ISSUE TITLE
StaticSite: Allow configuring the default behaviour to support Lambda@Edge 

### ISSUE THREAD

**Issue by mmccall10** [serverless-stack/serverless-stack#441]
Lambda@Edge cannot be added to the StaticSite's CloudFront default behavior because it requires modifying the default behavior and the origin is required.

**Comment by fwang** [comment]
You can now customize `defaultBehavior` in v0.28.0. Here's an example https://docs.serverless-stack.com/constructs/StaticSite#configuring-the-default-behavior

And here's an example of configuring Lambda@Edge https://docs.serverless-stack.com/constructs/StaticSite#using-lambdaedge
