### ISSUE TITLE
Add C# support

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#447]
What we need to understand before getting started:
- [ ] what build commands are you using to build your C# Lambda functions currently?
- [ ] are you currently building the C# handlers inside a docker container?
- [ ] are the build commands different on a Mac vs Windows vs Linux system?
- [ ] does C# have the concept of a package manager (ie. npm, pip)? If yes, what are the commonly used ones? Which one are you using?

TODO:
- [ ] Function: allow .net runtime
- [ ] sst build: build .net function
- [ ] sst start: watch for .net code
- [ ] sst start: build .net function on code change
- [ ] sst start: add a bootstrap file to invoke .net handler
- [ ] sst start: return errors in native .net format
- [ ] test on windows
- [ ] create-serverless-stack: add a .net starter template
- [ ] create-serverless-stack: update cli to take the .net language
- [ ] doc: create-serverless-app cli takes language python
- [ ] doc: Function takes .net runtime

---
_Requested by Jeffrey, [Brinsley](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1624435458220200), and [Claros](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1626961738340200) on Slack_

**Comment by El-Jefe-Carne** [comment]
>  what build commands are you using to build your C# Lambda functions currently?
The build file only has 3 commands:
dotnet restore
dotnet tool install -g Amazon.Lambda.Tools --framework netcoreapp3.1
dotnet lambda package --configuration Release --framework netcoreapp3.1 --output-package bin/Release/netcoreapp3.1/build.zip

>  are you currently building the C# handlers inside a docker container?
No

> are the build commands different on a Mac vs Windows vs Linux system?
We're using .net core, so no.

> does C# have the concept of a package manager (ie. npm, pip)? If yes, what are the commonly used ones? Which one are you using?
Yes it does. Nuget is the most commonly used one, and is also the one we're using.

**Comment by fwang** [comment]
Thanks @El-Jefe-Carne.

Can I bother you for a sample repo with the .net setup? It can be really dummy, maybe just uses 1 package installed using Nuget.

**Comment by brinsleylogic** [comment]
Legend! 🙌  🙌  🙌

**Comment by fwang** [comment]
@brinsleylogic Haha I'm flattered! This took me a while.. had to take a crash course on C# 😂

C# is not supported in [v0.38.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.38.0)!
```cs
  new sst.Function(this, "Fn", {
    runtime: "dotnetcore3.1",
    srcPath: "src/MyApp",
    handler: "MyApp::MyApp.Api::ListNotes",
  });
```

More details here - https://docs.serverless-stack.com/constructs/Function#functionprops

**Comment by brinsleylogic** [comment]
Read through the commit earlier after your initial merge, looks good! We'll probably check it out next week!
