### ISSUE TITLE
Allow passing pre-bundled code to sst.Function

### ISSUE THREAD

**Issue by harrycollin** [serverless-stack/serverless-stack#450]
I need to be able to pass a zip to sst.Function instead of letting it build itself. I need to make it like this because of some custom python-packages which don't exist on pip. It is talked about [here](https://leandeep.com/custom-python-packages-with-aws-lambda-and-cdk/). 

Hopefully, there is an easier alternative to this though since this approach could break the live-lambda-environment when it comes to hot-reloading of changes to code.

**Comment by harrycollin** [comment]
This might be solvable using lambda layers instead.

**Comment by fwang** [comment]
Hey @harrycollin, let me think about this and get back to you.

**Comment by harrycollin** [comment]
Hey @fwang, I was able to work around this issue with Lambda Layers. Whether it's worth further investigating is up to you. Perhaps other people have encountered this.

**Comment by fwang** [comment]
Yeah I think that's the best solution as well.

Glad you got it to work!
