### ISSUE TITLE
Support top level async

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#451]
@thdxr mentioned in slack:

> Using top level await requires use of esm which means setting type: "module" to true.  This makes it so require statements cannot be used.
> As part of the deploy process a script gets generated at .build/run.js which does use require statements and is unable to run.  Possibly can fix it by renaming it to .build/run.cjs

Link to Slack discussion: https://serverless-stack.slack.com/archives/C01JG3B20RY/p1623769542372000
Link to AWS announcement of top level async: https://aws.amazon.com/about-aws/whats-new/2021/02/aws-lambda-now-supports-node-js-14/

**Comment by thdxr** [comment]
This paves the way for creating an easy way to load SSM/Secrets Manager parameters at startup
