### ISSUE TITLE
ApolloApi Custom Resource name

### ISSUE THREAD

**Issue by geekmidas** [serverless-stack/serverless-stack#452]
It would be nice if we could add a custom name for the `ApolloApi` it seems like we can't do that at the moment or at least the Typescript compiler does see it

```ts
  new ApolloApi(this, 'api', {
    apolloApiName: 'some-api-name'
    ...
  })
```

**Comment by fwang** [comment]
Hey @geekmidas, `ApolloApi` extends the `Api` - https://docs.serverless-stack.com/constructs/Api

``` ts
 new ApolloApi(this, 'api', {
    apolloApiName: 'some-api-name'
    customDomain: "api.domain.com",
    ...
  })
```

Let me know if that works for you.

**Comment by geekmidas** [comment]
@fwang I resorted to a different method in order to get the name. It might be a typescript issue if that is meant to work. I just ended up using the API directly.

**Comment by fwang** [comment]
hmm.. did you get a TypeScript error when you tried to set the `customDomain` in `ApolloApi`?

**Comment by geekmidas** [comment]
@fwang the issue is not the custom domain, but the custom name. You cannot have 
`apolloApiName` At the moment.

**Comment by fwang** [comment]
@geekmidas Oh man my bad, misread your post all this time. This should work:
```js
new ApolloApi(this, 'api', {
  httpApi: {
    apiName: 'some-api-name',
  },
  ...
})
```

**Comment by geekmidas** [comment]
@fwang Thanks. I would like to start contributing to the project. Where do I start?

**Comment by geekmidas** [comment]
@fwang Thanks man. Hopefully I start contributing soon.

**Comment by fwang** [comment]
Appreciate your offer to help!

Come join our Slack community https://launchpass.com/serverless-stack
You can also check out the roadmap https://github.com/serverless-stack/serverless-stack/projects/1 and feel free to pick up anything off the board

**Comment by geekmidas** [comment]
@fwang Thank you very much. I will definitely be part of the team real soon.
