### ISSUE TITLE
__dirname points to the build output path, not src path

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#460]
Currently, `__dirname` points to output directory instead of the source directory.

For example, this points to `<sst app>/.build/lib/file.sql`
``` js
path.join(__dirname, 'file.sql')
```
The desired location is `<sst app>/file.sql`

_A discussion on this topic in esbuild issues https://github.com/evanw/esbuild/issues/859_

**Comment by fwang** [comment]
The best workaround for now is to use `process.cwd()`:
```js
path.join(process.cwd(), 'file.sql')
```

Where `process.cwd()` points to the root of your SST app, ie. where your `sst.json` sits.

**Comment by iquabius** [comment]
Working with Prisma and Nexus in an [Nx](https://nx.dev) workspace I used the following to have both `sst start` and `nx serve myapi` correctly generate files:

```ts
import { makeSchema } from "nexus"
import * as path from "path"

// On my setup SST runs from root of repository/workspace
const isRunningFromSst = /.*\.build.*/.test(__dirname)
const appDirectory = isRunningFromSst
  ? path.join(process.cwd(), "apps/myapi")
  : process.cwd() // Nx already runs `myapi:serve` from apps/myapi

export const schema = makeSchema({
  type: [/***/],
  outputs: {
    schema: path.join(appDirectory, "src/schema.graphql"),
    typegen: path.join(appDirectory, "src/app/generated/nexus.ts"),
  },
  contextType: {
    module: path.join(appDirectory, "src/app/context.ts"),
    export: "ResolverContext",
  },
  sourceTypes: {/***/},
})
```
