### ISSUE TITLE
Review doc for StaticSite 

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#464]
Added 2 examples for overriding `defaultBehavior` and using `Lambda@Edge` with explanations on how Lambda@Edge works.

Reivew the doc changes: https://github.com/serverless-stack/serverless-stack/pull/463

**Comment by jayair** [comment]
Updated https://github.com/serverless-stack/serverless-stack/commit/42f19a689db973c2991409853229a1c39df2da18
