### ISSUE TITLE
Review doc: referencing SSM value as domain name

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#466]
Review copy for the two examples:
- `sst.Api`: https://docs.serverless-stack.com/constructs/Api#loading-domain-name-from-ssm-parameter
- `sst.ApiGatewayV1Api`: https://docs.serverless-stack.com/constructs/ApiGatewayV1Api#loading-domain-name-from-ssm-parameter

**Comment by jayair** [comment]
https://github.com/serverless-stack/serverless-stack/commit/6d16d6c42d2bfd236808b0e9a3e9ac1fb806c047
https://github.com/serverless-stack/serverless-stack/commit/9d6cde898141308cd4d82c5e52dda253f106d0b0
