### ISSUE TITLE
Access to current AWS Account ID

### ISSUE THREAD

**Issue by dkershner6** [serverless-stack/serverless-stack#473]
There is a common use case where something conditionally gets deployed depending on what account it is headed into. (i.e. Route53 might be in the account or it may need to go cross-account).

As far as I can tell, there is no way to access accountId when working in an sst.App (app.account is undefined, though it does exist, this is presumably because `env.account` does not get populated).

Would it be difficult to populate this property?

**Comment by dkershner6** [comment]
I was able to work around this using `process.env.CDK_DEFAULT_ACCOUNT`, and I guess this is actually how it works in the normal CDK, I just always specified.

I still think this is likely to be in line with the design principles of this app, as it is generally more opinionated and helpful than the CDK itself.

**Comment by fwang** [comment]
Hey @dkershner6, good point! Let me add it in the next release.

**Comment by fwang** [comment]
This change is in [v0.29.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.29.0)!

**Comment by fwang** [comment]
Merged into master. Will be in the next release!
