### ISSUE TITLE
how to allow s3 notification events to save picture to dynamodb

### ISSUE THREAD

**Issue by fxyong** [serverless-stack/serverless-stack#474]
i've declared a s3Stack with a notification function that will invoke upon item picture is uploaded to s3 bucket.
however, in the notification function, i am trying to save some of the image metadata (url, filename etc) to a dynamoDB.

```js
export async function savePhotoToDB(item) {
  console.log(`ASSET TABLE NAME: ${process.env.ASSET_TABLE_NAME}`);
  const params = {
    // Get the table name from the environment variable
    TableName: process.env.ASSET_TABLE_NAME,
    Item: item,
  };
  await dynamoDb.put(params).promise();
}
```
`process.env.ASSET_TABLE_NAME` always return undefined. 
how should i define it in my s3Stack so that i can access it in the above function which will trigger upon file uploaded to s3 bucket?

**Comment by fwang** [comment]
Hi @fxyong, can you share ur SST code for the `s3Stack`?

**Comment by fxyong** [comment]
`import * as cdk from "@aws-cdk/core";
import * as s3 from "@aws-cdk/aws-s3";
import * as sst from "@serverless-stack/resources";
import * as iam from "@aws-cdk/aws-iam";
import { NodejsFunction } from "@aws-cdk/aws-lambda-nodejs";
import * as lambda from "@aws-cdk/aws-lambda";

export default class S3Stack extends sst.Stack {
  s3Bucket;
  constructor(scope, id, props) {
    super(scope, id, props);

    const { assetTable } = props;

    // https://bobbyhadz.com/blog/aws-cdk-s3-bucket-example
    // 👇 create bucket
    const s3Bucket = new sst.Bucket(this, "s3-bucket", {
      s3Bucket: {
        bucketName: "my-todo-bucket-485834533",
        // removalPolicy: cdk.RemovalPolicy.DESTROY,
        // autoDeleteObjects: true,
        // versioned: false,
        publicReadAccess: false,
        // encryption: s3.BucketEncryption.S3_MANAGED,
        cors: [
          {
            allowedMethods: [
              s3.HttpMethods.GET,
              s3.HttpMethods.POST,
              s3.HttpMethods.PUT,
            ],
            allowedOrigins: ["http://localhost:3000"],
            allowedHeaders: ["*"],
          },
        ],
        /*
      lifecycleRules: [
        {
          abortIncompleteMultipartUploadAfter: cdk.Duration.days(90),
          expiration: cdk.Duration.days(365),
          transitions: [
            {
              storageClass: s3.StorageClass.INFREQUENT_ACCESS,
              transitionAfter: cdk.Duration.days(30),
            },
          ],
        },
      ],
      */
      },
      /*
      defaultFunctionProps: {
        environment: {
          ASSET_TABLE_NAME: assetTable.dynamodbTable.tableName,
        },
      },
      */
      notifications: [
        {
          function: "src/note-service/processAsset.main",

          /*environment: {
            ASSET_TABLE_NAME: assetTable.dynamodbTable.tableName,
          },
          */
          notificationProps: {
            events: [s3.EventType.OBJECT_CREATED],
            /*
            environment: {
              ASSET_TABLE_NAME: assetTable.dynamodbTable.tableName,
            },
            */
          },
        },
      ],
    });

    const getPresignedUrlFunction = new NodejsFunction(
      this,
      "pre-signed-url-s3",
      {
        runtime: lambda.Runtime.NODEJS_12_X,
        memorySize: 1024,
        timeout: cdk.Duration.seconds(5),
        handler: "main",
        //entry: path.join(__dirname, '/../src/get-presigned-url-s3/index.ts'),
        entry: "src/note-service/getPresignedUrl.js",
        environment: {
          BUCKET_NAME: s3Bucket.s3Bucket.bucketName,
          //ASSET_TABLE_NAME: assetTable.dynamodbTable.tableName,
        },
      }
    );

    // grant access to bucket
    s3Bucket.s3Bucket.grantRead(new iam.AccountRootPrincipal());
    s3Bucket.s3Bucket.grantPut(getPresignedUrlFunction);
    s3Bucket.s3Bucket.grantPutAcl(getPresignedUrlFunction);
    s3Bucket.attachPermissions([s3Bucket, assetTable]);
    // Export values
    new cdk.CfnOutput(this, "AttachmentsBucketName", {
      value: s3Bucket.s3Bucket.bucketName,
    });

    this.s3Bucket = s3Bucket;
  }
}
`

**Comment by fxyong** [comment]
i've tried setting 
`
environment: {
          ASSET_TABLE_NAME: assetTable.dynamodbTable.tableName,
        },
`
in 3 different places (now commented away as above). none of these 3 places allows me to pick up the value using
process.env.ASSET_TABLE_NAME.

**Comment by fwang** [comment]
Try this:
```js
...

      notifications: [
        {
          function: {
            handler: "src/note-service/processAsset.main",
            environment: {
              ASSET_TABLE_NAME: assetTable.dynamodbTable.tableName,
            },
          },
          notificationProps: {
            events: [s3.EventType.OBJECT_CREATED],
          },
        },
      ],

...
```
