### ISSUE TITLE
Add support for Database seeding and migration

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#483]
One proposed solution is to run DB migrations inside a custom resource.

## Proposed Solution
```js
new sst.Run(this, "DBMigration", {
  script: "src/migrations/script.main",
});
```
The `sst.Run` construct creates a Lambda function with the script and a CloudFormation custom resource that runs the Lambda function on CloudFormation deployment.

### Does the script run on every deploy?
No, the same script only runs once. If the `script` property is changed, it will get run again. Note that, if you change the script from `scriptA.main` to `scriptB.main` and then back to `scriptA.main` again, `scriptA.main` will get run again.

### How do I make sure the same DB migration does not get run twice?
The same script does not get run twice, see the question `Does the script run on every deploy?`. However, you can also add a check in your script by storing a list of successfully run scripts in ur DB/S3 bucket, and skip if the current script has been run.

### How do I control when the script is run during the deployment?
By default, `sst.Run` does not depend on other constructs in your stack, so it gets run as soon as the CF stack starts to deploy. Note that since other constructs don't depend on `sst.Run` either, they might be deployed while the script is running.

You can enforce the order by setting dependencies. Like:
```js
const api = new sst.Api(..);
const script = new sst.Run(..);

// run script BEFORE Api is deployed
api.node.addDependency(script);

// run script AFTER Api is deployed
script.node.addDependency(api);
```

Please leave your thoughts?

**Comment by ashishpandey001** [comment]
Yep, this looks interesting. Another point to explore is how could other tools which are more DB or platform-specific utilise this and generate the history to be stored.

**Comment by harshit9715** [comment]
Hey @fwang , Check out [aws-cdk-dynamodb-seeder](https://www.npmjs.com/package/aws-cdk-dynamodb-seeder).

It works for me. But I get this version mismatch warning.

![DeepinScreenshot_select-area_20210719171225](https://user-images.githubusercontent.com/55243567/126154950-9d588a9e-fd54-41b4-9af8-19b6bb396a18.png)

**Comment by fwang** [comment]
Hey @harshit9715, interesting! The implementation looks pretty clean.

Btw, do you have a need for something similar to run the DB migrations?

^^I will take a look at the warning. Created an issue here https://github.com/serverless-stack/serverless-stack/issues/584

**Comment by fwang** [comment]
Added the `Script` construct in [v0.41.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.41.0), it can be used to seed database and run database migrations. See examples here - https://docs.serverless-stack.com/constructs/Script#examples
