### ISSUE TITLE
StaticSite: local variable replacment

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#488]

**Comment by jayair** [comment]
On the React side, use the built-in `process.env` support for `REACT_APP_*` variables.

```js
fetch(process.env.REACT_APP_API_URL, { method: "POST" })
```

```html
<title>%REACT_APP_API_URL%</title>
```

In the start script in `package.json`.

```js
"start": "REACT_APP_API_URL=\"https://i0hma2r1yc.execute-api.us-east-1.amazonaws.com\" react-scripts start"
```

On the SST side:

```js
const site = new sst.StaticSite(this, "ReactSite", {
  path: "frontend",
  buildOutput: "build",
  buildCommand: "REACT_APP_API_URL=\"{{ API_URL }}\" npm run build",
  errorPage: sst.StaticSiteErrorOptions.REDIRECT_TO_INDEX_PAGE,
  replaceValues: [
    {
      files: "**/*.js",
      search: "{{ API_URL }}",
      replace: api.url,
    },
    {
      files: "index.html",
      search: "{{ API_URL }}",
      replace: api.url,
    },
  ],
});
```

---

Given the above setup we can create a `ReactStaticSite` construct that looks like:

```js
const site = new sst.ReactStaticSite(this, "ReactSite", {
  path: "frontend",
  env: { REACT_APP_API_URL: api.url },
});
```

It'll do the following for:

- `sst deploy`: Run the build command while setting the env vars to a placeholder (like `{{ SST_API_URL }}`). Then search and replace the environment variables in the html and js files in the custom resource.
- `sst start`: Generate an file with the `path` of the static site and all the environment variables in the `.build` dir.

In React we alter the start script to use a new CLI.

```js
"start": "senv -- react-scripts start"
```

The `senv` CLI will traverse up the tree to look for the `sst.json` and find the file with the environment variables in its `.build` dir. It'll check that its path is the same as the one in the file (to handle cases where there are multiple ReactStaticSite constructs. It'll apply the environment variables to the start script (similar to https://github.com/andrewmclagan/react-env/blob/master/packages/node/src/cli-index.js).
