### ISSUE TITLE
Is there any way to debug Lambda Auth Function (sst.ApiAuthorizationType.CUSTOM)?

### ISSUE THREAD

**Issue by pabacham** [serverless-stack/serverless-stack#500]
I have added a Lambda function as an Auth method following the docs 

`const api = new sst.Api(this, 'Api', {

      defaultPayloadFormatVersion: sst.ApiPayloadFormatVersion.V2,
      defaultFunctionProps,
      defaultAuthorizationType: sst.ApiAuthorizationType.CUSTOM,
      defaultAuthorizer: new HttpLambdaAuthorizer({
        authorizerName: 'BackendApiAuth',
        handler: new sst.Function(this, 'BackendAuthorizer', {
          handler: 'src/auth.main',
        }),
      }),
      routes: {
        'GET /': 'src/lambda.main',
        ...routes,
      },
    });`

but I could not find a way how to debug it locally. I tried either this method https://docs.serverless-stack.com/debugging-with-vscode or just simple console.log but seems like approaches don't work.

**Comment by fwang** [comment]
Hey @pabacham, it should work. Did you get it to work?

**Comment by pabacham** [comment]
@fwang Yes, it was my bad, I didn't path Authorization param, so the function was not even triggered

**Comment by fwang** [comment]
Ah I see. Glad you got it to work!
