### ISSUE TITLE
sst start: child process started by Lambda function are orphaned

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#509]
Observed by Dax:

> Prisma spawns an rust executable to do connection management with the db.  Right now every time a function is invoked it spawns another one.  This shouldn't  be a problem but for some reason when the node process exits the rust binary sticks around.  Restarting sst kills them all and I have to do this periodically as my db connections get exhausted.  Wonder why it's not exiting with the node process

**Comment by thdxr** [comment]
Closing for now some of the work in #672 will address this
