### ISSUE TITLE
No warnings on duplicated routes

### ISSUE THREAD

**Issue by justindra** [serverless-stack/serverless-stack#512]
When you define duplicated routes accidentally, which can happen when your SST app starts getting larger and multiple people are working on it. It would be nice to receive a warning or an error on build. Rather than waiting for it to be caught by CloudFormation.

Sample Code
```typescript
export default class MyStack extends sst.Stack {
  constructor(scope: sst.App, id: string, props?: sst.StackProps) {
    super(scope, id, props);

    // Create a HTTP API
    const api = new sst.Api(this, 'Api', {
      routes: {
        'GET /': 'src/lambda.handler',
        'GET /test': 'src/lambda.handlerEvent',
      },
    });
    
    api.addRoutes(this, {
      'GET /test': 'src/lambda.handlerEvent',
    });

    // Show the endpoint in the output
    this.addOutputs({
      ApiEndpoint: api.url,
    });
  }
}
```

This does not throw any warnings or errors on `sst build` but on `sst deploy` it breaks down during CloudFormation deployment.

**Comment by fwang** [comment]
Hey @justindra, added build time check for duplicate routes in [v0.31.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.31.0)

**Comment by justindra** [comment]
Thanks for the quick turn-around @fwang
