### ISSUE TITLE
New AWS CDK Update 1.111.0 - to use Cloudfront Functions

### ISSUE THREAD

**Issue by riccardogiorato** [serverless-stack/serverless-stack#518]
The AWS CDK is up to 1.111.0 and currently SST is still on 1.105.0.

Is there any chance we can get that updated to be closer to new version? 
I would love to know if this update is possible or when will it be done?
Is there a list of issues linked to this update or depreactions?

We are looking to use Cloudfront Functions and they got fully supported just in the latest versions of CDK.

Would love to help if it's needed some help to update the CDK version in a Pull Request.

**Comment by fwang** [comment]
Hey @riccardogiorato, I'm going to take a look at it today.

**Comment by fwang** [comment]
Hey @riccardogiorato, just released v0.32.0 with CDK 1.111.0.
https://github.com/serverless-stack/serverless-stack/releases/tag/v0.32.0

**Comment by riccardogiorato** [comment]
Love this! I'm incredibly thankful! Thank you @fwang ❤️
