### ISSUE TITLE
Explode the code for Terraform use

### ISSUE THREAD

**Issue by pabacham** [serverless-stack/serverless-stack#526]
The question comes from the DevOps team of our project. The thing is that the dev team is working with SST and everything is good for us, but for keeping the deployment consistency the DevOps team wants to move the infra to Terraform. Is there any way to do that?

**Comment by fwang** [comment]
Hey @pabacham, there isn't an easy way to do this.

SST uses AWS CloudFormation under the hood. If there are tools that can automatically converts a CloudFormation template into Terraform definition, then you will be able to run `sst build` to generate the CloudFormation templates and then convert them into Terraform.

**Comment by pabacham** [comment]
@fwang Got it. Thanks

**Comment by fwang** [comment]
Closing the issue for now. Feel free to re-open if anyone has more questions regarding this.
