### ISSUE TITLE
Add rds.ServerlessCluster (Aurora) to supported Permissions.

### ISSUE THREAD

**Issue by patrick-icario** [serverless-stack/serverless-stack#530]
Right now when you add 
`
function: {
   permissions: [rds.ServerlessCluster]
}
`
You get "Error: The specified permissions are not supported". Would like to add this to the list :).

**Comment by patrick-icario** [comment]
@aws-cdk/aws-rds.ServerlessCluster is the specific name.

**Comment by fwang** [comment]
Hey @patrick-icario, I might be wrong, but I thought Lambda functions don't need IAM permissions to query the RDS DB. What IAM permissions are you thinking to grant the Lambda function in this case?

**Comment by rcoundon** [comment]
Hi Frank, it is possible to create RDS databases that rely on IAM rather than traditional credentials
See [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.html)

**Comment by fwang** [comment]
Got it. Thanks @rcoundon!

@patrick-icario If SST were to grant the Lambda functions with the `rds-db:connect` permission to the RDS cluster, that'd work for you right?

**Comment by pyoung213** [comment]
Hey @fwang sorry didn't get back to you.  Trying to wrap my head around this stuff as its pretty new to me.  I opened up a PR for what I was thinking but still not 100% if this is correct...  I think it is :).  

https://github.com/serverless-stack/serverless-stack/pull/552

Let me know!

**Comment by fwang** [comment]
Released in [v0.33.1](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.33.1)
