### ISSUE TITLE
Trouble getting output file to generate when using `--outputs-file` flag

### ISSUE THREAD

**Issue by cmaycumber** [serverless-stack/serverless-stack#532]
Code in package.json: 
```json
"scripts": {
...
"start": "sst start --outputs-file outputs.json",
"build": "sst build --outputs-file outputs.json",
...
}
```

Code in stack:  

```js
this.addOutputs({
        awsAppsyncGraphqlEndpoint: graphql.url,
        awsAppsyncRegion: "us-east-1",
        awsAppsyncAuthenticationType: "AMAZON_COGNITO_USER_POOLS",
        awsAppsyncApiKey: graphql.graphqlApi.apiKey ?? "",
      });
```

The outputs are printed to the console but I'm unable to get this to produce the `outputs.json` file as intended. Am I doing something incorrect?

**Comment by cmaycumber** [comment]
This seems to be working for me for `sst deploy`. Just not `sst start`. Not working for `sst build` makes since to be so please disregard that unless it's intended to work there as well.

**Comment by fwang** [comment]
Hey @cmaycumber, how are you planning to use the outputs file for `sst start`?

**Comment by cmaycumber** [comment]
> Hey @cmaycumber, how are you planning to use the outputs file for `sst start`?

I think I actually got it working with my use case, so I'll go ahead and close this one. Originally it was used to create an autogenerated file used to create a file that Amplify consumes on the frontend. But after some thought, this was better suited for us to be generated solely after a deployment.
