### ISSUE TITLE
Missing `aws-cdk` dependencies cause weird build errors

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#544]
Tobias in Slack ran into an issue where he forgot to list `@aws-cdk/aws-cloudfront` and `@aws-cdk/aws-lambda` in `package.json`, and the build error shows:
```
Error: ENOENT: no such file or directory, copyfile '/xxx/node_modules/@aws-cdk/core/lib/custom-resource-provider/nodejs-entrypoint.js' -> '/xxx/bridy/.build/lib/edge-function/__entrypoint__.js'
```

**Comment by fwang** [comment]
`aws-cdk` v2 will be a mono-package, and users won't have to include individual packages.

**Comment by riccardogiorato** [comment]
We had this same error when trying to build a "lambda@edge" directly with Serverless Stack.
Adding "@aws-cdk/aws-cloudfront" solved our issue during the build.

**Comment by fwang** [comment]
Updated to CDK v2. Closing this for now.
