### ISSUE TITLE
Documentation is using outdated property

### ISSUE THREAD

**Issue by Vuologist** [serverless-stack/serverless-stack#56]
Problem is on this webpage under the sample lambda: https://docs.serverless-stack.com/installation

I don't believe **entry** is a valid property starting with v0.6.0. The sample app uses handler and I can't find entry in the @serverless-stack/resources.

**Comment by jayair** [comment]
Good catch! We need to go change it. We are using the `handler` format.

**Comment by Vuologist** [comment]
Thanks for resolving this issue! I really appreciate the tutorial your team has put together. It's helped me break into AWS and the serverless space.

**Comment by jayair** [comment]
I'm glad we could help!
