### ISSUE TITLE
sst start: esbuild consumes a lot of memory

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#579]
Link to the thread: https://github.com/serverless-stack/serverless-stack/pull/574#issuecomment-883538903

**Comment by pabacham** [comment]
@fwang is there anything that we can do here?

**Comment by fwang** [comment]
@pabacham I created a PR to always exclude "aws-sdk" from the esbuild build process. I'm going to put in a fix to handle all hoisted modules. But for now, this fix should fix your memory issue.

I will cut a release later today.

**Comment by fwang** [comment]
@pabacham Can you give [v0.35.2](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.35.2) a try and see if the memory issue is fixed?

**Comment by pabacham** [comment]
@fwang 60MB now :) Fixed
