### ISSUE TITLE
ApolloApi [Breaking Change]: construct now creates 2 lambdas not 1 

### ISSUE THREAD

**Issue by riccardogiorato** [serverless-stack/serverless-stack#601]
Caused by a recent bug fix in this PR: #591 

The recent change to ApolloApi creates 2 lambdas compare to just a single lambda.

I have always seen "Apollo Servers" being built with just 1 single lambda to reuse more efficiently connections/warm-lambdas and also because having a single endpoint both for GET and POST might be considered a more common way on how to create Apollo Servers.

Is there any showcase of other projects/tips to use 2 lambdas?

Would be it possible to bring back the old behaviour as a default and making the "double lambda" possible only as a optional configuration?

**Comment by fwang** [comment]
Good point. I think it makes sense to keep both GET and POST share the same 1 lambda.

I will try to put in a fix today or tmr.

**Comment by fwang** [comment]
Hey @riccardogiorato, this should be fixed in v0.36.0. Give it a try!

**Comment by riccardogiorato** [comment]
Now it's working wonderfully thank you @fwang !
