### ISSUE TITLE
Function: add option to generate friendly function names

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#617]
---
Requested by:
- [GH discussion](https://github.com/serverless-stack/serverless-stack/discussions/236)
- [Kujtim](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1627507301069600)

**Comment by pabacham** [comment]
@fwang As a suggestion to implement a possibility to use these names in Function descriptions. Ex. "Some awesome description {​​​FunctionName}​​​"

**Comment by fwang** [comment]
@pabacham Good idea! I will keep that in mind ^^

**Comment by thdxr** [comment]
My suggestion is to add `functionNameGenerator: (props: FunctionProps, stack: cdk.Stack) => string` 

It can be used like this
```typescript
app.setDefaultFunctionProps({
 functionNameGenerator: (fun, stack) => `${app.stage}-${app.name}-${stack.stackName}-${fun.handler}`
})
```

This allows people to name functions dynamically based off of details in the function props, like the handler location or runtime.

**Comment by fwang** [comment]
@thdxr Yeah the callback way definitely gives the most flexibility. But I wonder if there's a simpler solution that works for 80% of ppl. For example, I noticed a couple of ppl in Slack are generating the `functionName` from the handler file name (similar to the generator idea). Should we consider make that a flag ppl can set, before having to implement the generate callback?
```js
app.setDefaultFunctionProps({
 functionNameFormat: FunctionNameFormat.FILENAME,
})
```

The tricky part being if ppl have a folder structure like below, just taking the handler file name will thrash.
```
src/
  users/
    list.js
    get.js
  posts/
    list.js
    get.js
```

In the long run, after we figure out a good scheme that works for 80% of ppl, we want to make the scheme the default behavior for SST. (We can leave that decision to later.)

**Comment by thdxr** [comment]
Yeah good point. We can have the generator callback and then provide some default generators. 

```
functionNameGenerator: FunctionName.OPTION1
```

**Comment by fwang** [comment]
You can now pass in a callback for functionName in v0.54.4. Here is an example - https://docs.serverless-stack.com/constructs/Function#functionname
