### ISSUE TITLE
Support fetching ssm values in .env

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#625]
### Issue
CloudFormation doesn't support using SSM secure string parameters as Lambda environment variables

### Solution
```
# .env file
plain={{ssm:plain/prod}}
secret={{ssm-secure:secure/prod}}
```
The SSM is fetched by SST, and process.env.PASSWORD has the resolved value.

### Workaround
Calling `aws-sdk` to fetch SSM value. This is cumbersome b/c you can't use await/async in Construct constructor

```
ssm.getParameter(key).promise().then(result => {
  // Do your stuff
})
```

---
_Requested by [Adrian on Slack](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1627618245001500)

**Comment by thdxr** [comment]
This is a good example of something I think benefits from seperation from the CLI.  We could have a function in `core` with the  responsibility of managing loading environment variables.  The cli (and whatever else) can call into this and be unaware of implementation details

**Comment by simonireilly** [comment]
I like this idea of segregation. I have used https://github.com/segmentio/chamber for this in the past. This might be a source of inspiration for the API 👍

**Comment by thdxr** [comment]
We decided not to implemen thtis for now and wait to understand the needs for this workflow better
