### ISSUE TITLE
Using StaticSite doesn't seem to work if Hozted Zone isn't already created

### ISSUE THREAD

**Issue by sweepy84** [serverless-stack/serverless-stack#641]
New to CDK and SST from Serverless Framework. Trying to follow instructions as per [StatisSite documentation](https://docs.serverless-stack.com/constructs/StaticSite) however I'm getting this error:

> It seems you are configuring custom domains for you URL. And SST is not able to find the hosted zone "domain.com" in your AWS Route 53 account. Please double check and make sure the zone exists, or pass in a different zone.

Now I've tried to create the hosted zone before creating the new site but it seems that it still fails. Even when I create it in a different stack and use the "addDependency" feature. It appears that SST looks for the hosted zone and ignores any other code.

Not sure if this is a problem where i have to manaully create the hosted zone first of if im doing something wrong. 

Should be able to pass a hosted zone that im creating as part of the stack.

**Comment by thdxr** [comment]
Good point we can add an option to pass in an existing HostedZone. This likely isn't working because `StaticSite` is using `route53.HostedZone.fromLookup` to find the zone and it isn't there when this is being resolved.

**Comment by thdxr** [comment]
Sorry looking into this further it looks like this is already supported.  You should be able to set the `customDomain.hostedZone` prop to a route53.IHostedZone you created elsewhere in your app

**Comment by thdxr** [comment]
Looks like this is actually a bug and it's fixed in this PR #614

**Comment by thdxr** [comment]
This was merged and release in 0.37.2
