### ISSUE TITLE
Does Cognito federated logins work with outside providers?

### ISSUE THREAD

**Issue by cmaycumber** [serverless-stack/serverless-stack#645]
We can't seem to get the Federated Identities populated in our deployed Cognito user pools.

Defined top-level inside of our Auth stack.

```
apple: { servicesId: '***' },
      google: {
        clientId: '***',
      },
```

Is this supposed to be linked to our Cognito user pools or are we supposed to handle these in a different way?

**Comment by fwang** [comment]
Hey @cmaycumber, the `Auth` construct configures the authentication providers in Cognito Identity Pool. See attached screenshots.

<img width="1169" alt="Screen Shot 2021-08-04 at 10 10 00 PM" src="https://user-images.githubusercontent.com/83515/128280045-42954961-6a02-405e-8b0f-d2e3d1bfa13f.png">

A couple of questions if you can clarify:
- How are you using the `Auth` construct?
- How are you authenticating your API endpoint? Using IAM or JWT?

**Comment by thdxr** [comment]
Hey @cmaycumber are you still having issues with this? Feel free to reopen the issue if so
