### ISSUE TITLE
ApolloApi function doesn't have default role after upgrade from v0.35.1 to v0.36.0

### ISSUE THREAD

**Issue by iquabius** [serverless-stack/serverless-stack#647]
Below is the relevant part of my `GraphQlApiStack`. After upgrading to version 0.36.0 `graphqlApiPostFn?.role` is falsy because `graphqlApi.getFunction("POST /")` returns `undefined`.

```ts
const graphqlApi = new ApolloApi(this, "Api", {
  server: {
    handler: "apps/api/src/lambda.handler",
    bundle: { /** */ },
    environment: { /** */ },
  },
})

const graphqlApiPostFn = graphqlApi.getFunction("POST /")

if (graphqlApiPostFn?.role) {
  props.dbInstance.secret.grantRead(graphqlApiPostFn.role)
  someSecret.grantRead(graphqlApiPostFn?.role)
} else {
  throw new Error(`For some reason "POST /" handler doesn't have a role`)
}
```

I logged `graphqlApiPostFn.routes` and it shows `[ 'GET /' ]`.

Is this expected with `ApolloApi` having only one function for both `GET` and `POST`?

**Comment by iquabius** [comment]
Well, after being confused for a bit I simply changed from `"POST /"` to `"GET /"` since now `ApolloApi` uses the same function for both routes:

```diff
- const graphqlApiPostFn = graphqlApi.getFunction("POST /")
+ const graphqlApiPostFn = graphqlApi.getFunction("GET /")
```

Maybe an abstraction over `Api.getFunction()` would make accessing the function more straight forward. Something like a public `ApolloApi.function` property:


```diff
- const graphqlApiPostFn = graphqlApi.getFunction("POST /")
+ const graphqlApiPostFn = graphqlApi.function
```

**Comment by fwang** [comment]
@iquabius Good point. Let me put something in.

**Comment by fwang** [comment]
Hey @iquabius, added `serverFunction` property for `sst.ApolloApi` in v0.38.0. Here's a link to the doc - https://docs.serverless-stack.com/constructs/ApolloApi#serverfunction
