### ISSUE TITLE
StaticSite: speed up CloudFront update/invalidation

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#673]
Currently, on `sst deploy` it takes CloudFront several minutes to update the distribution and then invalidate the cache. Let's use this issue to gather some potential ways to speed it up.

---
_Requested by [brent on Slack](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1628603782339000)_

**Comment by thdxr** [comment]
I personally liked this feature because I know once I get the build complete alert from CI that I know for sure it was all invalidated.  The python custom resource in static site explicitly waits for the invalidation to finish - maybe can make this an option to disable?

**Comment by fwang** [comment]
Yeah, I agree, I think we should always wait. 2 things are slow currently:
1. updating the distribution to point to the new S3 folder
2. invalidating cache

I'm not sure why 1. takes ~1min. If it's just CloudFormation being slow, we could move updating the distrubution's s3 Origin to the custom resource and update it via CloudFront API. Not a good practice, but if that cuts down 1 min per deployment and is safe, I'd go for it.

**Comment by warwickgrigg** [comment]
Would more flexibility for fileOptions include/exclude combinations help?  I've found myself effectively copying files multiple times just to get the cacheControl combinations I've wanted, whereas I could target groups of files more precisely if I could specify  exclude/include combinations of arbitrary length and order (as s3 cp allows)

**Comment by fwang** [comment]
Removed the use of S3 folder and added an option to not wait for invalidation.
