### ISSUE TITLE
API functions should be able to override default authorizer

### ISSUE THREAD

**Issue by ffxsam** [serverless-stack/serverless-stack#682]
## Description

I have the following definition for my API:

```ts
    const api = new sst.Api(this, 'RestAPI', {
      defaultAuthorizationType: sst.ApiAuthorizationType.JWT,
      defaultAuthorizer: new HttpUserPoolAuthorizer({
        userPool: props.cognitoAuth.cognitoUserPool!,
        userPoolClient: props.cognitoAuth.cognitoUserPoolClient!,
      }),
      cors: true,
      httpApi: {
        description: 'REST API',
      },
      routes: generateRoutes(this, 'src/services/rest-api/functions/', routes),
    });
```

My routes are defined as such:

```ts
export const routes: sst.ApiProps['routes'] = {
  'GET /things': {
    handler: 'get-things.main',
    authorizationType: sst.ApiAuthorizationType.NONE,
  },
  'POST /things': 'create-thing.main',
};
```

## Expectation

When I deploy this, I would expect the `GET /things` route to not have an authorizer.

## Actual Result

There's an authorizer on the route:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/12532733/129149148-d16f5693-cf81-4400-98d0-aa2635ed2bbd.png">

I would expect, with the route definitions above, that I can override a single function's authorization type.

## Use Case

Most of my routes are private and need authentication, but a small handful will be fully public.

**Comment by rcoundon** [comment]
I came across this too. This would be really useful

**Comment by simonireilly** [comment]
@ffxsam that's a strange one, I can see lots of tests for this behaviour in the code base already.

If you have the stack can you run `sst diff`?

Wondering if there was a change set skipped somehow 🤔

Could you share the generateRoutes function?

**Comment by ffxsam** [comment]
Aha, thank you! Yes, that's quite confusing and I never would've guessed that. 😅
