### ISSUE TITLE
Example with Serverless Framework?

### ISSUE THREAD

**Issue by malpaso** [serverless-stack/serverless-stack#7]
Hi, is there an example available somewhere of Serverless Framework running with SST? How does the Serverless Framework know about resources created by the SST?

**Comment by jayair** [comment]
@malpaso Hi there, I replied in on Gitter as well.

The repo we create over on [Serverless Stack](https://serverless-stack.com) has now been updated to use SST — https://github.com/AnomalyInnovations/serverless-stack-demo-api

We also added a couple of chapters that might help: https://serverless-stack.com/chapters/using-aws-cdk-with-serverless-framework.html & https://serverless-stack.com/chapters/connect-serverless-framework-and-cdk-with-sst.html

**Comment by jayair** [comment]
I added these to the README as well. Closing this for now!
