### ISSUE TITLE
Better source map support

### ISSUE THREAD

**Issue by thdxr** [serverless-stack/serverless-stack#701]
Right now sourcemaps are placed by default alongside the lambda code but for people using things like Sentry they will want to upload those seperately (and may not even want it in the bundle uploaded to AWS).

#### Requests
- https://serverless-stack.slack.com/archives/C01JG3B20RY/p1629128753065500?thread_ts=1629077794.053600&cid=C01JG3B20RY

**Comment by fwang** [comment]
[Adrian also mentioned in Slack](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1630560264208800)
> I’ve been using AWS Console to compare my old/new resources, and all looks fine, the only thing I noticed is my Lambdas size are 2x now, from 2MB on SLS to 4MB on SST.
> I believe might the due the `.map` file is included in the bundle now, and before with SLS might not be there.
> Is there a real need to include `.map` file? I’m not familiarized how to take advantage of it.

**Comment by thdxr** [comment]
Fixed this with #843
