### ISSUE TITLE
Document app.setDefaultRemovalPolicy

### ISSUE THREAD

**Issue by thdxr** [serverless-stack/serverless-stack#725]
#718 

I added some initial docs maybe want to call out that this is a dangerous options more

**Comment by thdxr** [comment]
I think an example like this maybe should go in there
```
import { RemovalPolicy } from "@aws-cdk/core";

export default function main(app: sst.App): void {
  app.setDefaultRemovalPolicy(RemovalPolicy.DESTROY);
}
```

**Comment by jayair** [comment]
Yup made scary. https://docs.serverless-stack.com/constructs/App#setdefaultremovalpolicy
