### ISSUE TITLE
Middy example

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#735]
Ashishkumar Pandey mentioned:
>  Could you please add middyjs in this mix as well? The validator, body parser, error handler, event normalizer, header normalizer and response serializer plugins bring a lot of value and reduce some decent amount of boilerplate as well.

Also some examples in this thread https://serverless-stack.slack.com/archives/C01JG3B20RY/p1629325865150900

**Comment by willfarrell** [comment]
Let me know if you need any help with this. 

Might be a good starting place -> https://github.com/middyjs/middy/tree/release/3.x/docs/patterns

**Comment by willfarrell** [comment]
Looks good! Note: `ajv.compile()` is only needed if you want different options to be used, our default options are different from the ajv ones to better suit how lambda is used.

```
{
  strict: true,
  coerceTypes: 'array', // important for query string params
  allErrors: true,
  useDefaults: 'empty',
  messages: false // allow i18n
}
```

**Comment by jayair** [comment]
Oh I see. Let me pull in @Manitej66 who helped put this example together. Maybe we can fix that.

**Comment by fwang** [comment]
Hey @willfarrell, does it help to speed things up if we precompiled the schema, and use the compiled schema inside the Lambda function? Or is that not necessary?

**Comment by willfarrell** [comment]
> **Important** Compiling schemas on the fly will cause a 50-100ms performance hit during cold start for simple JSON Schemas. Precompiling is highly recommended.

That's why I made https://github.com/willfarrell/middy-ajv :)

**Comment by fwang** [comment]
Ah gotcha!

@Manitej66 can we update the example with:
- [ ] Remove`ajv.compile()`
- [ ] Add a note saying:
  > Important Compiling schemas on the fly will cause a 50-100ms performance hit during cold start for simple JSON Schemas. Precompiling is highly recommended.
- [ ] Link to https://github.com/willfarrell/middy-ajv

**Comment by fwang** [comment]
@Manitej66 Do we use this quote style in other chapters? It looks weird, let's make it normal text, and also add link to  https://github.com/willfarrell/middy-ajv

<img width="1041" alt="Screen Shot 2022-02-25 at 3 23 05 AM" src="https://user-images.githubusercontent.com/83515/155680841-d4d4297c-493e-4f16-bcd4-36eaab4f3a34.png">
