### ISSUE TITLE
Do not generate "AWS::CDK::Metadata" resources in CloudFormation template

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#737]
`AWS::CDK::Metadata` resource is used for analytics purposes, and when its value changes, deployment takes time even the real resources are not changed.

To not generate this resource, pass `--no-version-reporting` to CDK CLI commands. `cdk synth` and `cdk deploy` accept this command for sure. Need to check which other CDK commands take this option. (ie. cdk diff?)

**Comment by thdxr** [comment]
cdk diff and bootstrap also accepted it so implemented it there as well
