### ISSUE TITLE
Using `--outputs-file` with `sst start` does not produce an `output.json`

### ISSUE THREAD

**Issue by Pr0gramWizard** [serverless-stack/serverless-stack#755]
We would like to use the outputs from `sst start` to do some e2e testing for our current project.  
According to the [docs](https://docs.serverless-stack.com/packages/cli#options) this should be possible.  
But passing the `--outputs-file` parameter in the cli does not generate an `outputs.json` file.  

There was already an issue regarding this problem #532 but it was closed. 
The issue #263 linked to a pull request #265 but it doesn't seem to call the appropriate function `writeOutputsFile` that is called in the `deploy` script.

Is this the intended behavior or are we doing something wrong?

**Comment by fwang** [comment]
Hey @Pr0gramWizard, this is fixed in v0.40.5!

Give it a try and let me know if it works for you!

**Comment by Pr0gramWizard** [comment]
Yes it works now!
Thank you very much.
