### ISSUE TITLE
Allow specifying output file full path in bundle

### ISSUE THREAD

**Issue by thdxr** [serverless-stack/serverless-stack#760]
#### Requests
- https://serverless-stack.slack.com/archives/C01JG3B20RY/p1630023996056400?thread_ts=1630015691.049900&cid=C01JG3B20RY

**Comment by ffxsam** [comment]
Hey @fwang @thdxr - any updates on this? I think this will be a hugely beneficial update, since Sentry can't resolve source maps as things stand now.

**Comment by thdxr** [comment]
Added it to my todos for this week

**Comment by ffxsam** [comment]
Thanks, Dax! It'll be great to have this as we open up our final beta.
