### ISSUE TITLE
WebSocketApi: support Lambda authorizer

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#775]
---
_Requested by [Hubert](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1630411840152000)_

**Comment by pa-dentally** [comment]
I'd like to second the request for this one too.  Pusher was recommended to me for doing streaming updates to our Angular clients but WebSocketApi already works serverless, so thought I might use that instead.  However, I could do with a custom authorizer so I can use the JWT authorization logic I use for my ApolloGraph stack, etc.
