### ISSUE TITLE
WebSocketApi CORS error

### ISSUE THREAD

**Issue by tysoncadenhead** [serverless-stack/serverless-stack#782]
I'm getting a CORS error when I try to use the WebSocketApi with my frontend running on the my local host. On an ApiGatewayApi, I can pass in `cors: true` to enable CORS, but I can't find anything similar for websockets. Am I missing something?

**Comment by fwang** [comment]
Hey @tysoncadenhead, sorry for the late reply. Please correct me if I'm wrong, I think CORS doesn't apply to WebSocket.

**Comment by tysoncadenhead** [comment]
You're right! Sorry I should have closed this out. The error was from me trying to use socket.io with API Gateway and they apparently don't play nice. I switched to the native WebSocket API and the CORS error went away.
