### ISSUE TITLE
Next.js construct

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#783]
Related discussion #213 

---
Requested by:
- [Abdul on Slack](https://serverless-stack.slack.com/archives/C01UJ8MDHEH/p1630715838021200)
> I'm using version 11. The features I'm using are mainly incremental static regeneration, SSR and AMP.  It also has a headless CMS it fetches content from.

- Mike on Slack

**Comment by atalebagha** [comment]
+1 Much needed!

**Comment by cfraz89** [comment]
https://serverless-nextjs.com/docs/cdkconstruct works.

Just have to watch out for issue https://github.com/serverless-stack/serverless-stack/issues/733, so you need in your package.json:

```json
    "@aws-cdk/aws-s3-deployment": "1.114.0",
    "@aws-cdk/aws-s3": "1.114.0",
    "@aws-cdk/aws-logs": "1.114.0",
```

**Comment by fwang** [comment]
Yeah I'm working a version that supports auto-Next.js environment variable replacement, similar that for [StaticSite](https://docs.serverless-stack.com/constructs/StaticSite#environment).

Should have something soon. I will keep you guys updated.
