### ISSUE TITLE
Trying to understand how SST works

### ISSUE THREAD

**Issue by srikanthsrnvs** [serverless-stack/serverless-stack#803]
We're currently running our infra on GCloud functions, moving to AWS. Came across SST because of the live deployment feature set, but I'm having issues.

1. I've created a set of endpoints following the guide here https://serverless-stack.com/chapters/create-a-hello-world-api.html
2. I've deployed them to prod using `npx sst deploy --stage prod`
3. I've tested them remotely, and they work.

The issue however is that I have to keep my local terminal running all the time. If I kill my local server, the remote endpoints return a status 500. I'm pretty sure I'm understanding this wrong, or doing something wrong - but can't figure out what.

Also, I get logs locally using `console.log()` - how do I get these logs remotely?

**Comment by jayair** [comment]
Hi there!

So when you run `sst start` it proxies requests from the remote endpoint to your local machine. If you kill that process locally and hit those endpoints again, you'll get an error.

When you want to deploy your app to prod, you run `sst deploy --stage prod`. This creates a completely separate environment.

For the logs, if you are not running locally, you'll need to look at the logs in the CloudWatch console in AWS. It's not easy to use but we are thinking of addressing this in the future.

Hope that makes sense!

PS: [Join us over on Slack](https://launchpass.com/serverless-stack), and we can help you get started.

**Comment by thdxr** [comment]
Solved this issue over slack
