### ISSUE TITLE
WebsocketApi: Support routeResponseSelectionExpression

### ISSUE THREAD

**Issue by garretcharp** [serverless-stack/serverless-stack#831]
The `routeResponseSelectionExpression` variable allows the response body that the function handler returns to be sent to the client rather than having to use the management client API.

I tried looking into how to do this myself but it seems very complicated so haven't actually implemented anything myself but what I do know is you need to use CfnRoute from API-gateway v2 to set the routeResponseSelectionExpression variable. (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.CfnRoute.html)

**Comment by masahji** [comment]
We actually have the same need. I'm surprised that this doesn't come up more often for other "Cfn" or even "Cdk" interface attributes. The `.cdk` escape hatch has been useful for us; but it isn't available for resources that have been created internally and then forgotten by SST. For example here:

https://github.com/serverless-stack/serverless-stack/blob/e3f62239bbf65df2c210cb3d2906b7de86bbb50f/packages/resources/src/WebSocketApi.ts#L565

We have no way of getting to the `route` instance, which would be useful for getting to additional features (like adding CfnRoute variables) not exposed by SST.

**Comment by masahji** [comment]
I have created a PR that would help here:

https://github.com/serverless-stack/serverless-stack/pull/1690

In the meantime, here's a hacky workaround:

```
    const routeId = `Route_${wsApi.getFunction('/my/route/path')?.node.id}`;
    if (routeId) {
      const route = wsApi.node.findChild(routeId);
      const cfnRoute = route.node.defaultChild as CfnRoute;
      cfnRoute.routeResponseSelectionExpression = '$default';
    }
```

**Comment by fwang** [comment]
In v1.2.8, you can call `getRoute()` to get the underlying CDK route object. Here's an example https://docs.serverless-stack.com/constructs/WebSocketApi#getroute
