### ISSUE TITLE
Api: allow customize access log retention

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#856]
For example, setting access log retention. Allow passing in log group properties to the `accessLog` param.

Requests:
- https://serverless-stack.slack.com/archives/C01JG3B20RY/p1632604722467800

**Comment by pa-dentally** [comment]
I'm not sure if this is the right place to suggest this, but it would be nice if you could set a default for all of the functions.  Having to set it for each one when you might want them all the same would make it too easy for mistakes to slip in.  A new property on defaultFunctionProps might work really nicely?

**Comment by junaway** [comment]
Proposed specs :

- [ ] Research : Alex Debrie's [reference post about API Gateway logs](https://www.alexdebrie.com/posts/api-gateway-access-logs/).
- [ ] Research : How to verify log configuration in synthesized stack.
- [ ] Research : How SST currently handles API Gateway logs and/or log groups.
- [ ] Research : Alternatives and best way to expose access log configuration in SST.
- [ ] Implement : Basic (custom format) Api (HTTP API) access logs.
- [ ] Implement : [optional] Other Api access log formats (?)
- [ ] Test : Api with and without access Logs (custom format)
