### ISSUE TITLE
Support Node.js 14.x Runtime

### ISSUE THREAD

**Issue by ryanmalesic** [serverless-stack/serverless-stack#86]
AWS just released the Node.JS 14.x Runtime. AWS-CDK has merged the related PR (aws/aws-cdk#12861) to master. Still has not been released. 

When released, sst should update to support this runtime to allow for the new language features (Nullish Coalescing and Optional Chaining).

**Comment by jayair** [comment]
SST supports and ES and TS. We can test out and support these without changing the underlying runtime. I'll need to test what we support right now.

**Comment by ryanmalesic** [comment]
> SST supports and ES and TS. We can test out and support these without changing the underlying runtime. I'll need to test what we support right now.

i mean runtimes for lambda handlers, not the sst code itself

i think all that needs to happen is the aws-cdk dependency needs bumped to the version where NodeJs 14.x is an option for lambda runtimes. obviously any breaking changes in doing so need resolved. 

the new version of the aws-cdk has not been released yet though so it is a waiting game.

**Comment by jayair** [comment]
Yup let's keep an eye on it. If you notice it gets merged. Leave a message here and @fwang will upgrade the version and we'll cut a new release.

**Comment by ryanmalesic** [comment]
V1.89.0 was released yesterday with the nodejs14.x runtime

**Comment by jayair** [comment]
Yup I just noticed it as well. We'll update the version soon. Thanks for letting us know!

**Comment by ryanmalesic** [comment]
Support still isn't complete because of this section of validation in the Function code: 

```
// Validate NodeJS runtime
    if (
      ![
        lambda.Runtime.NODEJS,
        lambda.Runtime.NODEJS_10_X,
        lambda.Runtime.NODEJS_12_X,
        lambda.Runtime.NODEJS_4_3,
        lambda.Runtime.NODEJS_6_10,
        lambda.Runtime.NODEJS_8_10,
      ].includes(runtime)
    ) {
      throw new Error(
        `The specified runtime is not supported for sst.Function. Only NodeJS runtimes are currently supported.`
      );
    }
```

NODEJS_14_X is not there.

**Comment by jayair** [comment]
Oh right. Good catch, want to add it in and submit a PR?

**Comment by karhidle** [comment]
any reason why the default wasn't updated here: https://github.com/serverless-stack/serverless-stack/blob/ff7268fa69cf19cc0310cd0f2c3c10cb013570ec/packages/resources/src/Function.ts#L83 ?

**Comment by jayair** [comment]
@karhidle Let's hold off on the default for a little bit. In the past AWS hasn't done a great job with their runtime releases. https://hichaelmart.medium.com/reviewing-the-aws-lambda-nodejs10-x-runtime-84de1e500aac

If things seem okay with 14, we'll make it the default soon.
