### ISSUE TITLE
Update CDK to 1.125.0, to support ARM based Lambdas

### ISSUE THREAD

**Issue by JasonCraftsCode** [serverless-stack/serverless-stack#874]
AWS just released [ARM support](https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/) for Lambda's and other compute resources on the Graviton2 processor.  Which is up to 20% faster and 20% cheaper.

**Comment by fwang** [comment]
Updated in v0.45.0!
