### ISSUE TITLE
Function: allow imported IConstructs in attachPermissions

### ISSUE THREAD

**Issue by dkershner6** [serverless-stack/serverless-stack#875]
Currently, a list of constructs are supported to be handed into attachPermissions: https://docs.serverless-stack.com/util/Permissions#supported-constructs

Mostly sst constructs, but a handful of CDK ones.  For the CDK ones, only the actual construct is supported, not one that is "found" via a `from` method, i.e. `fromTableArn`.  This returns an `ITable` rather than a `Table`, and the attachPermissions throws a TypeScript error: `Type 'ITable' is missing the following properties from type 'Construct': onValidate, onPrepare, onSynthesize, validate, and 2 more.ts(2740)`.

Would it be possible to support `I` interfaces?  My thought is "yes", since they also have the `grant` methods on them.  Currently a policy statement must be created from scratch.

Thank you!

Edit: I just tried it using a `@ts-expect-error` and it seems to work.

**Comment by thdxr** [comment]
This is a good point, we should be looking for the interfaces and not the class. Will fix this

**Comment by fwang** [comment]
Also requested by Sam https://serverless-stack.slack.com/archives/C01JG3B20RY/p1638828949084500

**Comment by fwang** [comment]
Hey @dkershner6, this is now supported in v0.53.4
