### ISSUE TITLE
sst start: set log retention in debug stack

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#883]
Let's default the log retention to 1 week.

Request:
- Sam https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1633395915262300

**Comment by junaway** [comment]
Proposed specs :

- [ ] Research: How is debug-stack-specific lambda timeout currently handled in SST?
- [ ] Research: How is log retention currently handled in CDK/SST?

- [ ] Implement: Add a command option in 'sst start' to set the log retention period, including: a list of allowed values and a proper default value (7 days as per the issue description).
- [ ] Implement: Add logic in 'Function' to force the debug log retention period if in 'live dev' mode.
- [ ] Implement: [optional] Expose the list of allowed values from @aws-cdk/aws-logs in 'Function' as enum.
- [ ] Implement: [optional] Validate log retention value for each 'Function' and round up to nearest allowed value.

- [ ] Test: Add a test with a baseline period of 14 days and 'live dev' mode option set to false. => 14 days.
- [ ] Test: Add a test with a baseline period of 14 days and 'live dev' mode option set to true. => 7 days.
- [ ] Test: Add a test with a baseline period of 14 days and a 'live dev' mode period of 7 days. => 7 days.
- [ ] Test: Add a test with a baseline period of 14 days and a 'live dev' mode period of 30  days. => 14 days.

- [ ] Doc: Document the added command option in the CLI Doc.
