### ISSUE TITLE
OSX: sst start fails with 'Module not found' if folder path includes spaces

### ISSUE THREAD

**Issue by JensRoland** [serverless-stack/serverless-stack#916]
Following along with the DynamoDB guide on https://serverless-stack.com/examples/how-to-use-dynamodb-in-your-serverless-app.html I end up getting an error running `sst start`.

I created my repo in a folder like:

`/Users/me/Documents/Coding Projects/My Serverless App/rest-api-dynamodb`

When I run `npx sst start` it ends up failing because it cannot find the "module" `Projects/My`.

I can just move my repo to somewhere like `/Users/me/Documents/FINE_WE_CAN_PARTY_LIKE_ITS_1979/rest-api-dynamodb` but I shouldn't have to.

**Comment by fwang** [comment]
Hey @JensRoland, thanks for reporting this. Do you think it's the spaces in the directory names?

**Comment by phausken** [comment]
- [ ] Research: How do other JS CLIs deal with this problem? Is there a quick solution in Node's file IO?
- [ ] Task: Make the fix, or handroll a solution in the unlikely event no solution exists
- [ ] Test: `sst start` works with a directory with spaces
- [ ] Test: `sst start` still works on directories with no spaces
- [ ] Doc: None needed, this is expected functionality with any CLI

**Comment by fwang** [comment]
Hey @phausken I had to take a look into this issue as a couple of other folks got this as well.

**Comment by fwang** [comment]
Hey @JensRoland this is fixed in v0.60.9

**Comment by JensRoland** [comment]
Wonderful - great job!!

**Comment by TaylorRadke** [comment]
I have just come across this issue, but for Windows instead of OSX.

**Comment by jayair** [comment]
Which version of SST is this?
