### ISSUE TITLE
ECONNRESET when using new lambda runtime server and live debugging after 5s

### ISSUE THREAD

**Issue by mbld** [serverless-stack/serverless-stack#981]
Hello, first of all I really love the option of live development and debugging of lambdas with serverless stack, great work!

After updating to a more recent version of SST, I am running into an ECONNRESET error after 5s of debugging a lambda function with 'sst start' and using breakpoints. I spent some time on debugging and want to share my thoughts about the issue. Also I found a workaround which works for me. It might be a solution but not sure if this is the ideal way to solve it.

### Setup
- macOS: BigSur 11.6
- SST: 0.50.1
- CDK: 1.126.0
- IntelliJ: 2021.2.2 Ultimate
- node: v16.10.0

### How to reproduce
1. Install SST
2. Create a new SST project with 'npx create-serverless-stack@latest my-sst-app --language typescript'. Error should also happen with JavaScript but did not check.
3. Start live debugging with 'npx sst start' in IntelliJ by following [this example](https://github.com/serverless-stack/serverless-stack/issues/627)
4. Set a breakpoint inside of the default lambda function
5. Access your API with browser/curl/etc.
5. Wait at least 5s before letting the lambda function run to completion in the debugger.
6. You will get the following error output in the terminal `Uncaught Exception      {"errorType":"Error","errorMessage":"read ECONNRESET","code":"ECONNRESET","errno":-54,"syscall":"read","stack":["Error: read ECONNRESET","    at TCP.onStreamRead (node:internal/stream_base_commons:220:20)","    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)"]}`
7. Browser/curl will show an error of the AWS-Gateway after 30s

### Assumption
The ECONNRESET error happens because of the connection between the lambda RuntimeClient and RuntimeServer on the local machine. Also it happens only with SST >= v0.47, so I assume it is related to the new lambda runtime server. It took some time to figure out what happens, because I am quite new to SST and also not a nodejs expert :) Capturing the network traffic between runtime server and client shows that the server closes the TCP connection after 5s. When the lambda execution is continued in the debugger after the server closed the connection, the runtime client tries to re-use the closed TCP connection and gets the ECONNRESET.

The assumption is that we are hitting the problem described at https://nodejs.org/api/http.html#requestreusedsocket.

> When sending request through a keep-alive enabled agent, the underlying socket might be reused. But if server closes connection at unfortunate time, client may run into a 'ECONNRESET' error.

In our situation the 'unfortunate time' is nearly always the case, because the nodejs event loop is blocked by the debugger/breakpoint. This results in the server closing the TCP connection after 5s and whenever the execution continues, it hits this 'unfortunate time' by using a closed TCP connection.

### Workaround
I fixed it for me by turning off 'keepAlive' for the runtime client by setting this to false: https://github.com/serverless-stack/aws-lambda-nodejs-runtime-interface-client/blob/main/src/RuntimeClient/RuntimeClient.ts#L81 This works because the client does not try to re-use the TCP connection but instead creates a new one all the time. Maybe not ideal but works for me.

**Comment by fwang** [comment]
Hey @mbld, thanks for digging into this issue! 

Let me loop in @thdxr, he's looking into this exact issue.

**Comment by thdxr** [comment]
Wow that's amazing work. I was looking into this issue and hadn't figured out the source of it. I'll fix and get a release out

**Comment by thdxr** [comment]
Looks like there's a keepAliveMsecs and timeout option that we can turn up. I'll experiment and see if they work
