### ISSUE TITLE
Allow to add a Lambda function as Data Source in AWS AppSync

### ISSUE THREAD

**Issue by AntoniusGolly** [serverless-stack/serverless-stack#998]
AWS Appsyncs allows to resolve fields with individual resolvers. Also [Lambda functions can be added as data sources](https://medium.com/open-graphql/aws-appsync-with-lambda-data-sources-643fabcc598b).

![image](https://user-images.githubusercontent.com/3856505/140520507-c2cc46f7-25d0-4c46-b183-ccd542e2a6b3.png)

Currently, it seems that this functionality is missing in SST.

https://docs.serverless-stack.com/constructs/AppSyncApi#using-other-data-sources

I believe [serverless can do it](https://dev.to/aws-builders/aws-appsync-todo-apis-with-aws-lambda-resolvers-using-serverless-framework-ob2). 

Am I missing something or is that a limitation to SST?

**Comment by thdxr** [comment]
Hey, does specifying the datasource up here not do what you're looking for: https://docs.serverless-stack.com/constructs/AppSyncApi#using-the-minimal-config

**Comment by AntoniusGolly** [comment]
I should elaborate. Thanks for reaching out.

I want to use AppSync for schema stitching. That means behind the one AppSync endpoint I want to configure a schema which fields are resolved by multiple microservices. Lambda functions, served by various teams. We don't have a monorepo. 

When you manually create an AppSync schema you can add any of your Lambdas by ARN. Actually, when you click through the GUI it will let you chose from dropdowns of Lambdas of your zone. 

I want one service be responsible for creating this schema. This should be done by a serverless framework. Ideally, that schema is scripted and not created manually. 

I learnt about SST and was wondering if I can add "external" lambdas as a data source, by ARN. 

Alternatively, I can only rely on the manual configuration which definitely works. Or we move to a monorepo.

**Comment by thdxr** [comment]
Ah gotcha.  So we expose the raw AppSync construct so you can do this.
```
sstAppSyncInstance.graphqlApi.addLambdaDataSource("lambda", <import_function>)
```

**Comment by AntoniusGolly** [comment]
Great. Will try and report back. 
Thanks alot for the hint.

**Comment by AntoniusGolly** [comment]
Almost there. I understand now better how the native cdk is exposed. 

However, I am facing a stupid TS error which I cannot get rid of.

```
import * as sst from "@serverless-stack/resources";

/// const api = new sst.AppSyncApi(........

const getLambda = new sst.Function.fromFunctionArn(
    this,
    'external-lambda-from-arn',
    'arn:aws:lambda:eu-central-1:000000000000:function:service-production-status'
)

api.graphqlApi.addLambdaDataSource("getDataSource", getLambda)
```

gives the error `'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.` on the `fromFunctionArn` call.

[This](https://bobbyhadz.com/blog/aws-cdk-import-existing-lambda) example with Typescript uses the native cdk. Is there also a way to use it with TS and your package?
